#!/bin/bash
set -e
set -o pipefail
set -u
#
#
TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions
"${rscripts}"/cleanup

# use our creates sql statements for the old database
export SQL_DDL_DIR="${current_test_directory}/bareos_15_db_2004_ddl"
"${rscripts}"/setup

# use the default ddl directory with the current sql definitions
unset SQL_DDL_DIR

"${scripts}/update_bareos_tables" -f
