<?php

/**
 *
 * Barbossa - A Web-Frontend to manage Bareos
 * 
 * @link      http://github.com/fbergkemper/barbossa for the canonical source repository
 * @copyright Copyright (c) 2013-2014 dass-IT GmbH (http://www.dass-it.de/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Log details';
$this->headTitle($title);

?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title">Log <?php echo $this->escapeHtml($log->logid); ?> Details</h3>
</div>

<div class="panel-body">
<table class="table">

<tr>
	<td>Log ID</td><td><a href="<?php echo $this->url('log', array('action' => 'details', 'id' => $log->logid)); ?>"><?php echo $this->escapeHtml($log->logid); ?></a></td>
</tr>

<tr>
	<td>Job ID</td><td><a href="<?php echo $this->url('job', array('action' => 'details', 'id' => $log->jobid)); ?>"><?php echo $this->escapeHtml($log->jobid); ?></a></td>
</tr>

<tr>	
	<td>Time</td><td><?php echo $this->escapeHtml($log->time); ?></td>
</tr>

<tr>
	<td>Text</td><td><?php echo nl2br($this->escapeHtml($log->logtext)); ?></td>
</tr>

</table>
</div>

</div>
