<?php

$title = 'Log details';
$this->headTitle($title);

?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title">Log <?php echo $this->escapeHtml($log->logid); ?> Details</h3>
</div>

<div class="panel-body">
<table class="table">

<tr>
	<td>Log ID</td><td><a href="<?php echo $this->url('log', array('action' => 'details', 'id' => $log->logid)); ?>"><?php echo $this->escapeHtml($log->logid); ?></a></td>
</tr>

<tr>
	<td>Job ID</td><td><a href="<?php echo $this->url('job', array('action' => 'details', 'id' => $log->jobid)); ?>"><?php echo $this->escapeHtml($log->jobid); ?></a></td>
</tr>

<tr>	
	<td>Time</td><td><?php echo $this->escapeHtml($log->time); ?></td>
</tr>

<tr>
	<td>Text</td><td><?php echo nl2br($this->escapeHtml($log->logtext)); ?></td>
</tr>

</table>
</div>

</div>
