<?php

$title = 'Log';
$this->headTitle($title);

?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<div class="panel panel-default">
<div class="panel-body">

<table class="table table-striped table-hover" style="font-size: 9pt;">

<tr>
	<th>Log</th>
	<th>Timestamp</th>
	<th>Message</th>
	<th>Job</th>
</tr>

<?php foreach ($this->paginator as $log) : ?>

<tr>

	<td><?php echo $this->escapeHtml($log->logid); ?></td>
	<td width="150"><?php echo $this->escapeHtml($log->time); ?></td>
	<td><?php echo nl2br($this->escapeHtml($log->logtext)); ?></td>
	<td><a href="<?php echo $this->url('job', array('action' => 'details', 'id' => $log->jobid)); ?>"><?php echo $this->escapeHtml($log->jobid); ?></a></td>
	
</tr>

<?php endforeach; ?>

</table>

</div>
</div>

<?php

echo $this->paginationControl(
			$this->paginator, 
			'Elastic',
			array('partial/paginator.phtml', 'Log'),
			array('route' => 'log')
		);

?>

