<?php

$title = 'Log';
$this->headTitle($title);

?>

<h2><?php echo $title; ?></h2>
<hr />

<table class="table table-striped table-hover">

<tr>
	<th>Log</th>
	<th>Timestamp</th>
	<th>Message</th>
	<th>Job</th>
</tr>

<?php foreach ($this->paginator as $log) : ?>

<tr>

	<td><?php echo $this->escapeHtml($log->logid); ?></td>
	<td width="150"><?php echo $this->escapeHtml($log->time); ?></td>
	<td><?php echo $this->escapeHtml($log->logtext); ?></td>
	<td><a href="<?php echo $this->url('job', array('action' => 'details', 'id' => $log->jobid)); ?>"><?php echo $this->escapeHtml($log->jobid); ?></a></td>
	
</tr>

<?php endforeach; ?>

</table>

<?php

echo $this->paginationControl(
			$this->paginator, 
			'Elastic',
			array('partial/paginator.phtml', 'Log'),
			array('route' => 'log')
		);

?>
