<?php

$title = 'Log';
$this->headTitle($title);

?>

<table class="table">

<tr>
	<th>Log ID</th>
	<th>Job ID</th>
	<th>Time</th>
	<th>Text</th>
</tr>

<?php foreach ($this->paginator as $log) : ?>

<tr>

	<td><a href="<?php echo $this->url('log', array('action' => 'details', 'id' => $log->logid)); ?>"><?php echo $this->escapeHtml($log->logid); ?></a></td>
	<td><a href="<?php echo $this->url('job', array('action' => 'details', 'id' => $log->jobid)); ?>"><?php echo $this->escapeHtml($log->jobid); ?></a></td>
	<td><?php echo $this->escapeHtml($log->time); ?></td>
	<td><?php echo $this->escapeHtml($log->logtext); ?></td>

</tr>

<?php endforeach; ?>

</table>

<?php

echo $this->paginationControl(
			$this->paginator, 
			'Elastic',
			array('partial/paginator.phtml', 'Log'),
			array('route' => 'log')
		);

?>
