<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 * 
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2014 dass-IT GmbH (http://www.dass-it.de/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Logs for job ' . $this->jobid;
$this->headTitle($title);

?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<div class="panel panel-default">
<div class="panel-body">

<table class="table table-striped table-hover" style="font-size: 9pt;">

<tr>
	<th>Timestamp</th>
	<th>Log</th>
	<th>Job</th>
	<th>Message</th>
</tr>

<?php foreach($this->log as $logitem) : ?>

<tr>
	<td><?php echo $this->escapeHtml($logitem->time); ?></td>
	<td><?php echo $this->escapeHtml($logitem->logid); ?></td>
	<td><?php echo $this->escapeHtml($logitem->jobid); ?></td>
	<td><?php echo nl2br($this->escapeHtml($logitem->logtext)); ?></td>
</tr>

<?php endforeach; ?>

</table>

</div>
</div>
