<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 * 
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2014 dass-IT GmbH (http://www.dass-it.de/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 * @author	  Frank Bergkemper
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Storage';
$this->headTitle($title);

?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<div class="row">

<div class="col-md-12">
<div class="panel panel-default">
    
<div class="panel-body">

<table class="table table-striped table-bordered" style="font-size: 9pt;">

<tr>
	<th>ID</th>
	<th>Name</th>
	<th>Autochanger</th>
</tr>

<?php foreach($storages as $storage) : ?>

<tr>

	<td><a href="<?php echo $this->url('storage', array('action'=>'details', 'id'=>$storage->storageid)); ?>"><?php echo $this->escapeHtml($storage->storageid); ?></a></td>
	<td><a href="<?php echo $this->url('storage', array('action'=>'details', 'id'=>$storage->storageid)); ?>"><?php echo $this->escapeHtml($storage->name); ?></a></td>
	<td>
	<?php if($storage->autochanger > 0) : ?>
		<span class="glyphicon glyphicon-list-alt"></span>
		<a href="<?php echo $this->url('storage', array('action'=>'autochanger', 'id'=>$storage->storageid)); ?>" title="<?php echo $this->escapeHtml("View slots"); ?>">
		<?php echo $this->escapeHtml("View slots"); ?>
		</a>
	<?php else : ?>
		<?php echo $this->escapeHtml("-"); ?>
	<?php endif; ?>
	</td>

</tr>

<?php endforeach; ?>

</table>

</div>
</div>
</div>

</div>
