<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2015 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 * @author	  Frank Bergkemper
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Storages';
$this->headTitle($title);

?>

<div class="row">

<div class="col-md-12">
<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title">Storages</h3>
</div>

<div class="panel-body">

<p>
Storages per page:
<a href="<?php echo $this->url('storage', array('limit' => '10', null, null, true)); ?>">10</a> |
<a href="<?php echo $this->url('storage', array('limit' => '25', null, null, true)); ?>">25</a> |
<a href="<?php echo $this->url('storage', array('limit' => '50', null, null, true)); ?>">50</a> |
<a href="<?php echo $this->url('storage', array('limit' => '100', null, null, true)); ?>">100</a>
</p>

<table class="table table-bordered table-condensed">

<tr>
	<th class="bg-primary"><?php echo $this->translate("Storage"); ?></th>
	<th class="bg-primary"><?php echo $this->translate("Name"); ?></th>
	<th class="bg-primary"><?php echo $this->translate("Autochanger"); ?></th>
</tr>

<?php foreach($paginator as $storage) : ?>

<tr>
	<td><?php echo $this->escapeHtml($storage['storageid']); ?></td>
	<td><?php echo $this->escapeHtml($storage['name']); ?></td>
	<td><?php echo $this->escapeHtml($storage['autochanger']); ?></td>
</tr>

<?php endforeach; ?>

</table>

<?php

echo $this->paginationControl(
                        $this->paginator,
                        'Elastic',
                        array('partial/paginator.phtml', 'Storage'),
                        array('route' => 'storage')
                );

?>

</div>
</div>
</div>
</div>
