<?php

$title = 'Storage';
$this->headTitle($title);

?>

<h2><?php echo $title; ?></h2>
<hr />

<table class="table table-striped table-hover">

<tr>
	<th>ID</th>
	<th>Name</th>
	<th>Autochanger</th>
</tr>

<?php foreach($storages as $storage) : ?>

<tr>

	<td><a href="<?php echo $this->url('storage', array('action'=>'details')); ?>"><?php echo $this->escapeHtml($storage->storageid); ?></a></td>
	<td><?php echo $this->escapeHtml($storage->name); ?></td>
	<td><?php echo $this->escapeHtml($storage->autochanger); ?></td>

</tr>

<?php endforeach; ?>

</table>
