#!/bin/sh
#
# Script file to update the Bacula version
#
out=/tmp/$$
VERSION=`sed -n -e 's/^#define VERSION.*"\(.*\)"$/\1/p' /home/kern/bacula/k/bacula/src/version.h`
DATE=`sed -n -e 's/^#define BDATE.*"\(.*\)"$/\1/p' /home/kern/bacula/k/bacula/src/version.h`
. /home/kern/bacula/release/bacula-docs-5.2.13/manuals/do_echo
sed -f ${out} /home/kern/bacula/release/bacula-docs-5.2.13/manuals/version.tex.in >version.tex
rm -f ${out}
