#!/bin/bash
set -e
set -o pipefail
set -u
#
# Let bareos run a scheduled backup
#   then restore it.
#
TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

start_test

currenttime=$(date +"%H:%M")

echo "Schedule {
  Name = \"TestCycle\"
  Run = Level=Full daily at $currenttime
}" >"$conf"/bareos-dir.d/schedule/TestCycle.conf

cat <<END_OF_DATA >$tmp/bconcmds
@$out ${NULL_DEV}
messages
@$out $tmp/setup.out
setdebug level=100 storage=File trace=1
setdebug level=100 director trace=1
setdebug level=100 client trace=1
reload
@sleep 1
@$out $tmp/log1.out
status director
status client
status storage=File
wait
messages
@#
@# now do a restore
@#
@$out $tmp/log2.out
wait
restore client=bareos-fd fileset=SelfTest where=$tmp/bareos-restores select all done yes
wait
messages
quit
END_OF_DATA

run_bconsole
check_for_zombie_jobs storage=File

check_two_logs
check_restore_diff "${BackupDirectory}"
end_test
