#!/bin/bash
set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

#
# Run test to check correct output of #`status scheduler job=...`
# of a copy job whose client is disabled
#

start_test

enabled_client_log="$tmp"/enabled_client_log.out
disabled_client_log="$tmp"/disabled_client_log.out

cat <<END_OF_DATA >$tmp/bconcmds
messages
@$out $enabled_client_log
enable client=bareos-fd
status scheduler job=copy

@$out $disabled_client_log
disable client=bareos-fd
status scheduler job=copy
wait
messages
quit
END_OF_DATA

run_bconsole

#check that `status scheduler job=...` returns scheduled copy jobs
expect_grep "TestCycle .* Level=Full" \
            "$enabled_client_log" \
            "No scheduled jobs for an enabled job were found!"

expect_not_grep "TestCycle .* Level=Full" \
                "$disabled_client_log" \
                "a scheduled job for a disabled client was listed!"

end_test
