.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BACULA-TRAY-MONITOR 1 "May 10, 2006" "Kern Sibbald" "Network backup, recovery and verification"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
 bacula-tray-monitor \- Bacula's 'System Tray' monitor
.SH SYNOPSIS
.B bacula-tray-monitor
.RI [options]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B bacula-tray-monitor
command, a simple monitor for the 'system tray' in KDE/GNOME
.PP
.SH OPTIONS
bacula-tray-monitor [\-c config_file] [\-d debug_level] [\-t]
.TP
.B \-c <config>
Specify configuration file.
.TP
.B \-d <nn>
Set debug level to \fInn\fP.
.TP
.B \-t
Test config mode: read configuration and exit.
.TP
.B \-?
Show version and usage of program.
.SH SEE ALSO
.BR bacula-dir (8),
.BR bacula-wxconsole (1)
.BR bls (1),
.BR bextract (1).
.br
.SH AUTHOR
This manual page was written by Jose Luis Tallon
.nh
<jltallon@adv\-solutions.net>.
