.\"                              Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BAT 1 "26 September 2009" "Kern Sibbald" "Backup Archiving REcovery Open Sourced"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
 bat \- Bareos Administration Tool Console
.SH SYNOPSIS
.B bat
.RI [options]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B bat
command, the QT version of the Bareos Administration Tool console.
This is a GUI full featured program similar the bconsole program,
but it is graphical oriented and more features.
.PP
.SH OPTIONS
bat [\-s] [\-c config_file] [\-d debug_level] [\-t]
.TP
.B \-c <config>
Specify configuration file.  Default is bat.conf.
.TP
.B \-d <nn>
Set debug level to \fInn\fP.
.TP
.B \-s
No signals. Used in debugging only.
.TP
.B \-t
Test config mode: read configuration and exit.
.TP
.B \-?
Show version and usage of program.
.SH SEE ALSO
.BR bareos-dir (8),
.BR bls (1),
.BR bextract (1).
.br
.SH AUTHOR
This manual page was written by Kern Sibbald.
