<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2016 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 * @author    Frank Bergkemper
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = _('Dashboard');
$this->headTitle($title);

?>

<div class="row">

   <!-- Jobs during past 24 hours -->
   <div class="col-md-4">

      <div class="panel panel-default">

         <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->translate('Jobs during the past 24 hours') ?></h3>
         </div>

         <div class="panel-body" style="overflow-y: auto;">

            <div class="row-md-6">
               <div class="col-md-4">
                  <table class="table">
                     <tr>
                        <td><a href="<?php echo $this->url('job', array('action' => 'index'), array('query' => array('period' => '1', 'status' => 'running'))); ?>"><?php echo $this->translate("Running"); ?></a></td>
                        <td><span class="badge"><?php echo $this->runningJobs; ?></span></td>
                     </tr>
                     <tr>
                        <td><a href="<?php echo $this->url('job', array('action' => 'index'), array('query' => array('period' => '1', 'status' => 'waiting'))); ?>"><?php echo $this->translate("Waiting"); ?></a></td>
                        <td><span class="badge"><?php echo $this->waitingJobs; ?></span></td>
                     </tr>
                     <tr>
                        <td><a href="<?php echo $this->url('job', array('action' => 'index'), array('query' => array('period' => '1', 'status' => 'successful'))); ?>"><?php echo $this->translate("Successful"); ?></a></td>
                        <td><span class="badge"><?php echo $this->successfulJobs; ?></span></td>
                     </tr>
                     <tr>
                        <td><a href="<?php echo $this->url('job', array('action' => 'index'), array('query' => array('period' => '1', 'status' => 'unsuccessful'))); ?>"><?php echo $this->translate("Unsuccessful"); ?></a></td>
                        <td><span class="badge"><?php echo $this->unsuccessfulJobs; ?></span></td>
                     </tr>
                  </table>
               </div>
               <div class="col-md-2">
                  <div id="chart1" style="width:350px; height:250px;"></div>
               </div>
            </div>

         </div>

      </div>

   </div>

   <!-- LIST JOBS LAST -->
   <div class="col-md-8">

      <div class="panel panel-default">

         <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->translate('Jobs last status'); ?></h3>
         </div>

         <div class="panel-body">
            <table class="table table-hover" id="jobs-last-status">
               <thead class="bg-primary">
                  <th><?php echo $this->translate("Job"); ?></th>
                  <th><?php echo $this->translate("Status"); ?></th>
                  <th><?php echo $this->translate("Name"); ?></th>
                  <th><?php echo $this->translate("Client"); ?></th>
                  <th><?php echo $this->translate("Level"); ?></th>
                  <th><?php echo $this->translate("Start"); ?></th>
                  <th><?php echo $this->translate("End"); ?></th>
               </thead>
            </table>
         </div>

      </div>

   </div>

</div>

<?php
   echo $this->headScript()->prependFile($this->basePath() . '/js/jqplot.pointLabels.min.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/jqplot.categoryAxisRenderer.min.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/jqplot.barRenderer.min.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/jqplot.pieRenderer.min.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.jqplot.min.js');
   echo $this->headLink()->prependStylesheet($this->basePath() . '/css/jquery.jqplot.min.css');

   echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.dataTables.min.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/dataTables.plugins.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/dataTables.bootstrap.min.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/dataTables.functions.js');
   echo $this->headLink()->prependStylesheet($this->basePath() . '/css/dataTables.bootstrap.min.css');
?>

<script type="text/javascript">

   function chart1() {

      var data = [
         ['<?php echo $this->translate('Running'); ?>', <?php echo $this->runningJobs; ?>],
         ['<?php echo $this->translate('Waiting'); ?>', <?php echo $this->waitingJobs; ?>],
         ['<?php echo $this->translate('Successful'); ?>', <?php echo $this->successfulJobs; ?>],
         ['<?php echo $this->translate('Unsuccessful'); ?>', <?php echo $this->unsuccessfulJobs; ?>]
      ];

      var plot1 = jQuery.jqplot(
         'chart1',
         [data],
         {
            seriesColors: [ "#5bc0de", "#cccccc", "#5cb85c", "#d9534f" ],
            seriesDefaults: {
               renderer: jQuery.jqplot.PieRenderer,
               rendererOptions: {
                  fill: true,
                  showDataLabels: true,
               },
               shadow: false,
            },
            legend:{
               show: true,
               location: 'se',
            },
            grid: {
               background: '#ffffff',
               drawGridLines: false,
               drawBorder: false,
               borderColor: 'transparent',
               shadowColor: 'transparent',
            }
         }
      );

   }

   $(document).ready(

      function() {

            chart1();

            var table = $('#jobs-last-status').DataTable({
               "ajax": {
                  "url": "<?php echo $this->url('dashboard', array('action' => 'getData'), null); ?>",
                  "dataSrc": ""
               },
               "language": {
                  "url": "<?php echo $this->basePath() . '/js/dataTables/language/'; ?>" + getLocale('<?php echo $_SESSION['bareos']['locale']; ?>')
               },
               "columns" : [
                  { "data": "jobid" },
                  { "data": "jobstatus" },
                  { "data": "name" },
                  { "data": "client" },
                  { "data": "level" },
                  { "data": "starttime" },
                  { "data": "endtime" }
               ],
               "paging": true,
               "ordering": true,
               "info": true,
               "pagingType": "full_numbers",
               "stateSave": true,
               "order": [[0, 'desc']],
               "columnDefs": [
                  {
                     "targets": 0,
                     "render": function(data, type, full, meta) {
                        return '<a href="<?php echo $this->basePath() . '/job/details/'; ?>'+data+'">'+data+'</a>';
                     }
                  },
                  {
                     "targets": 1,
                     "render": function(data, type, full, meta) {
                        return formatJobStatus(data);
                     }
                  },
                  {
                     "targets": 3,
                     "render": function(data, type, full, meta) {
                        return '<a href="<?php echo $this->basePath() . '/client/details/'; ?>'+data+'">'+data+'</a>';
                     }
                  },
                  {
                     "targets": 4,
                     "render": function(data, type, full, meta) {
                        return formatJobLevel(data);
                     }
                  }
               ]
            });
      }

   );

</script>

