#!/bin/bash
#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2025 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

myname=$(basename "$0")

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

start_test

echo "Full Data" > "${DB_FILE}"

"${SQLCMD}" -S "${COMPUTERNAME}" -E -b -v myDB=DBFileStreamTest db_data_dir= "${DB_DATA_DIR}" -i sqlfiles/SQL_db_filestream_create.sql
"${SQLCMD}" -S "${COMPUTERNAME}" -E -b -v myDB=DBFileStreamTest -i sqlfiles/SQL_create_bareos_login_user.sql
"${SQLCMD}" -S "${COMPUTERNAME}" -E -b -v myDB=DBFileStreamTest -i sqlfiles/SQL_create_schema_tables_stream.sql
"${SQLCMD}" -S "${COMPUTERNAME}" -E -b -v myDB=DBFileStreamTest -i sqlfiles/SQL_load_data.sql
"${SQLCMD}" -S "${COMPUTERNAME}" -E -b -v myDB=DBFileStreamTest my_file= "${DB_FILE}" -i sqlfiles/SQL_load_data_stream.sql

end_test
