#!/bin/bash
set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

myname=$(basename "$0")

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

set -x
"${SQLCMD}" -S ${COMPUTERNAME} -E -b -v myDB=DBNormalTest -i sqlfiles/SQL_db_normal_drop_create.sql
"${SQLCMD}" -S ${COMPUTERNAME} -E -b -v myDB=DBNormalTest -i sqlfiles/SQL_create_bareos_login_user.sql
"${SQLCMD}" -S ${COMPUTERNAME} -E -b -v myDB=DBNormalTest -i sqlfiles/SQL_create_schema_tables.sql
"${SQLCMD}" -S ${COMPUTERNAME} -E -b -v myDB=DBNormalTest -i sqlfiles/SQL_load_data.sql
