#!/bin/bash
set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

myname=$(basename "$0")

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

"${SQLCMD}" -S ${COMPUTERNAME} -E -b -v myDB=DBNormalTest -i sqlfiles/SQL_create_bareos_login_user.sql
