#!/bin/bash
set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

myname=$(basename "$0")

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

start_test

# update first line in brands
"${SQLCMD}" -Q "UPDATE DBFileStreamTest.tests.samples SET sample_name='Bareos' WHERE sample_id=1"
# Add a second filestream
"${SQLCMD}" -Q "INSERT (INTO DBFileStreamTest.tests.filestreams (fstreams_id, fstream_name, fstream_binary) VALUES (NEWID(),('sample_two', (SELECT * FROM OPENROWSET (BULK 'C:\Windows\write.exe',SINGLE_BLOB) AS fstream_binary))"

mkdir -p "${tmp}/data"
echo "$0" >"${tmp}/data/${myname}"

cat <<END_OF_DATA >"${tmp}/bconcmds"
@$out ${NULL_DEV}
messages
@$out ${tmp}/${myname}.log
run job=backup-DBFileStream level=Incremental yes
wait
messages
quit
END_OF_DATA

run_bconsole

check_for_zombie_jobs storage=File

expect_grep "IClientVirtualDeviceSet2::GetConfiguration successful: 0 (NOERROR)"
            "${tmp}/${myname}.log"
            "\"IClientVirtualDeviceSet2::GetConfiguration successful: 0 (NOERROR)\" not found in log"

end_test
