<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 * 
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2014 dass-IT GmbH (http://www.dass-it.de/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 * @author    Frank Bergkemper
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Pool details';
$this->headTitle($title);

?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<div class="row">

<div class="col-md-12">
<div class="panel panel-default">
	  
<div class="panel-heading">
<h3 class="panel-title">General Information</h3>
</div>
    
<div class="panel-body">

<table class="table table-striped table-hover" style="font-size: 9pt;">

<tr>
	<th>Pool</th>
	<th>Name</th>
	<th>Type</th>
	<th><div align="right">Volumes</div></th>
	<th><div align="right">Maximum volumes</div></th>
	<th><div align="right">Volume retention</div></th>
	<th><div align="right">Maximum volume jobs</div></th>
	<th><div align="right">Maximum volume files</div></th>
	<th><div align="right">Maximum volume bytes</div></th>
	
	
</tr>

<tr>

	<td><?php echo $this->escapeHtml($pool->poolid); ?></td>
	<td><?php echo $this->escapeHtml($pool->name); ?></td>
	<td><?php echo $this->escapeHtml($pool->pooltype); ?></td>
	<td><div align="right"><?php echo $this->escapeHtml($pool->numvols); ?></div></td>
	<td><div align="right"><?php echo $this->escapeHtml($pool->maxvols); ?></div></td>
	<td><div align="right"><?php echo $this->printRetention($pool->volretention) . " days"; ?></div></td>
	<td><div align="right"><?php echo $this->escapeHtml($pool->maxvoljobs); ?></div></td>
	<td><div align="right"><?php echo $this->escapeHtml($pool->maxvolfiles); ?></div></td>
	<td><div align="right"><?php echo $this->printBytes($pool->maxvolbytes); ?></div></td>

</tr>

</table>

</div>
</div>
</div>

</div>

<!-- VOLUMES -->
<div class="row">

<div class="col-md-12">
<div class="panel panel-default">
    
<div class="panel-heading">
<h3 class="panel-title">Volumes</h3>
</div>
    
<div class="panel-body">

<table class="table table-striped table-hover" style="font-size: 9pt;">

<tr>
	<th>Volume</th>
	<th>Name</th>
	<th>Storage</th>
	<th>Type</th>
	<th>Last written</th>
	<th>Status</th>
	<th><div align="right">Retention</div></th>
	<th><div align="right">Maximum bytes</div></th>
	<th><div align="right">Current bytes</div></th>
	<th><div align="right">Free bytes</div></th>
	
</tr>

<?php foreach($this->media as $volume) : ?>

<tr>

	<td><a href="<?php echo $this->url('media', array('action'=>'details', 'id' => $volume->mediaid)); ?>"><?php echo $this->escapeHtml($volume->mediaid); ?></a></td>
	<td><?php echo $this->escapeHtml($volume->volumename); ?></td>
	<td><a href="<?php echo $this->url('storage', array('action'=>'details')); ?>"><?php echo $this->escapeHtml($volume->storageid); ?></a></td>
	<td><?php echo $this->escapeHtml($volume->mediatype); ?></td>
	<td><div title="<?php echo $volume->lastwritten; ?>"><?php echo $this->printHumanReadableTimeperiod($volume->lastwritten, "fuzzy"); ?></div></td>
	<td><?php echo $this->escapeHtml($volume->volstatus); ?></td>
	<td><div align="right"><?php echo $this->printExpiration($volume->volretention, $volume->lastwritten, $volume->volstatus); ?></div></td>
	<td><div align="right"><?php echo $this->printBytes($volume->maxvolbytes); ?></div></td>
	<td><div align="right"><?php echo $this->printBytes($volume->volbytes); ?></div></td>
	<td><div align="right"><?php echo $this->printBytes($volume->maxvolbytes - $volume->volbytes); ?></div></td>
	
</tr>

<?php endforeach; ?>

</table>

</div>
</div>
</div>

</div>
