<?php

/**
 *
 * Barbossa - A Web-Frontend to manage Bareos
 * 
 * @link      http://github.com/fbergkemper/barbossa for the canonical source repository
 * @copyright Copyright (c) 2013-2014 dass-IT GmbH (http://www.dass-it.de/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Pool '. $pool->poolid .' details';
$this->headTitle($title);

?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<div class="row">

<div class="col-md-12">
<div class="panel panel-default">
	  
<div class="panel-heading">
<h3 class="panel-title">General Information</h3>
</div>
    
<div class="panel-body">

<table class="table table-striped table-hover" style="font-size: 9pt;">

<tr>
	<th>Pool ID</th>
	<th>Pool name</th>
	<th>Pool type</th>
	<th>Volumes</th>
	<th>Maximum volumes</th>
	<th>Volume retention</th>
	<th>Maximum volume jobs</th>
	<th>Maximum volume files</th>
	<th>Maximum volume bytes</th>
	
	
</tr>

<tr>

	<td><?php echo $this->escapeHtml($pool->poolid); ?></td>
	<td><?php echo $this->escapeHtml($pool->name); ?></td>
	<td><?php echo $this->escapeHtml($pool->pooltype); ?></td>
	<td><?php echo $this->escapeHtml($pool->numvols); ?></td>
	<td><?php echo $this->escapeHtml($pool->maxvols); ?></td>
	<td><?php echo $this->printRetention($pool->volretention) . " days"; ?></td>
	<td><?php echo $this->escapeHtml($pool->maxvoljobs); ?></td>
	<td><?php echo $this->escapeHtml($pool->maxvolfiles); ?></td>
	<td><?php echo $this->printBytes($pool->maxvolbytes); ?></td>

</tr>

</table>

</div>
</div>
</div>

</div>

<!-- VOLUMES -->
<div class="row">

<div class="col-md-12">
<div class="panel panel-default">
    
<div class="panel-heading">
<h3 class="panel-title">Volumes</h3>
</div>
    
<div class="panel-body">

<table class="table table-striped table-hover" style="font-size: 9pt;">

<tr>
	<th>Volume</th>
	<th>Name</th>
	<th>Storage</th>
	<th>Type</th>
	<th>Last written</th>
	<th>Status</th>
	<th>Retention</th>
	<th>Maximum bytes</th>
	<th>Current bytes</th>
	<th>Free bytes</th>
	
</tr>

<?php foreach($this->media as $volume) : ?>

<tr>

	<td><a href="<?php echo $this->url('media', array('action'=>'details', 'id' => $volume->mediaid)); ?>"><?php echo $this->escapeHtml($volume->mediaid); ?></a></td>
	<td><?php echo $this->escapeHtml($volume->volumename); ?></td>
	<td><a href="<?php echo $this->url('storage', array('action'=>'details')); ?>"><?php echo $this->escapeHtml($volume->storageid); ?></a></td>
	<td><?php echo $this->escapeHtml($volume->mediatype); ?></td>
	<td><?php echo $this->printDate($volume->lastwritten); ?></td>
	<td><?php echo $this->escapeHtml($volume->volstatus); ?></td>
	<td><?php echo $this->printRetention($volume->volretention) . " days"; ?></td>
	<td><?php echo $this->printBytes($volume->maxvolbytes); ?></td>
	<td><?php echo $this->printBytes($volume->volbytes); ?></td>
	<td><?php echo $this->printBytes($volume->maxvolbytes - $volume->volbytes); ?></td>
	
</tr>

<?php endforeach; ?>

</table>

</div>
</div>
</div>

</div>