<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 * 
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2014 dass-IT GmbH (http://www.dass-it.de/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 * @author    Frank Bergkemper
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Pools';
$this->headTitle($title);

?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<div class="row">

<div class="col-md-12">
<div class="panel panel-default">
    
<div class="panel-body">

<table class="table table-striped table-hover" style="font-size: 9pt;">

<tr>
	<th>Pool</th>
	<th>Name</th>
	<th>Type</th>
	<th><div align="right">Volumes</div></th>
	<th><div align="right">Maximum volumes</div></th>
	<th><div align="right">Volume retention</div></th>
	<th><div align="right">Maximum volume jobs</div></th>
	<th><div align="right">Maximum volume files</div></th>
	<th><div align="right">Maximum volume bytes</div></th>	
	
</tr>

<?php foreach($pools as $pool) : ?>

<tr>

	<td><a href="<?php echo $this->url('pool', array('action'=>'details', 'id' => $pool->poolid)); ?>"><?php echo $this->escapeHtml($pool->poolid); ?></a></td>
	<td><a href="<?php echo $this->url('pool', array('action'=>'details', 'id' => $pool->poolid)); ?>"><?php echo $this->escapeHtml($pool->name); ?></a></td>
	<td><?php echo $this->escapeHtml($pool->pooltype); ?></td>
	<td><div align="right"><?php echo $this->escapeHtml($pool->numvols); ?></div></td>
	<td><div align="right"><?php echo $this->escapeHtml($pool->maxvols); ?></div></td>
	<td><div align="right"><div align="right"><?php echo $this->printRetention($pool->volretention) . " days"; ?></div></td>
	<td><div align="right"><?php echo $this->escapeHtml($pool->maxvoljobs); ?></div></td>
	<td><div align="right"><?php echo $this->escapeHtml($pool->maxvolfiles); ?></div></td>
	<td><div align="right"><?php echo $this->printBytes($pool->maxvolbytes); ?></div></td>

</tr>

<?php endforeach; ?>

</table>

</div>
</div>
</div>

</div>


