<?php

$title = 'Pool';
$this->headTitle($title);

?>

<h2><?php echo $title; ?></h2>
<hr />

<div class="row">

<div class="col-md-12">
<div class="panel panel-default">
    
<div class="panel-body">

<table class="table table-striped table-hover" style="font-size: 9pt;">

<tr>
	<th>Pool ID</th>
	<th>Pool name</th>
	<th>Pool type</th>
	<th>Volumes</th>
	<th>Maximum volumes</th>
	<th>Volume retention</th>
	<th>Maximum volume jobs</th>
	<th>Maximum volume files</th>
	<th>Maximum volume bytes</th>	
	
</tr>

<?php foreach($pools as $pool) : ?>

<tr>

	<td><a href="<?php echo $this->url('pool', array('action'=>'details', 'id' => $pool->poolid)); ?>"><?php echo $this->escapeHtml($pool->poolid); ?></a></td>
	<td><a href="<?php echo $this->url('pool', array('action'=>'details', 'id' => $pool->poolid)); ?>"><?php echo $this->escapeHtml($pool->name); ?></a></td>
	<td><?php echo $this->escapeHtml($pool->pooltype); ?></td>
	<td><?php echo $this->escapeHtml($pool->numvols); ?></td>
	<td><?php echo $this->escapeHtml($pool->maxvols); ?></td>
	<td><?php echo $this->printRetention($pool->volretention) . " days"; ?></td>
	<td><?php echo $this->escapeHtml($pool->maxvoljobs); ?></td>
	<td><?php echo $this->escapeHtml($pool->maxvolfiles); ?></td>
	<td><?php echo $this->printBytes($pool->maxvolbytes); ?></td>

</tr>

<?php endforeach; ?>

</table>

</div>
</div>
</div>

</div>


