<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2015 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 * @author    Frank Bergkemper
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = _('Pools');
$this->headTitle($title);

?>

<ul class="nav nav-tabs">
   <li><a href="<?php echo $this->url('storage', array('action'=>'index')); ?>"><?php echo $this->translate('Devices'); ?></a></li>
   <li class="active"><a href="<?php echo $this->url('pool', array('action'=>'index')); ?>"><?php echo $this->translate('Pools'); ?></a></li>
   <li><a href="<?php echo $this->url('media', array('action'=>'index')); ?>"><?php echo $this->translate('Volumes'); ?></a></li>
</ul>

<br />

<div class="row">

<div class="col-md-12">
<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title"><?php echo $this->translate("Pools"); ?></h3>
</div>

<div class="panel-body">

<table class="table table-hover" id="pools">

<thead class="bg-primary">
   <th><?php echo $this->translate("Name"); ?></th>
   <th><?php echo $this->translate("Type"); ?></th>
   <th><?php echo $this->translate("Volumes"); ?></th>
   <th><?php echo $this->translate("Maximum volumes"); ?></th>
   <th><?php echo $this->translate("Volume retention"); ?></th>
   <th><?php echo $this->translate("Maximum volume jobs"); ?></th>
   <th><?php echo $this->translate("Maximum volume bytes"); ?></th>
</thead>

</table>

</div>
</div>
</div>
</div>

<?php
   echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.dataTables.min.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/dataTables.bootstrap.min.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/dataTables.plugins.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/dataTables.functions.js');
   echo $this->headLink()->prependStylesheet($this->basePath() . '/css/dataTables.bootstrap.min.css');
?>

<script>

var table= $('#pools').DataTable( {
   "ajax": {
      "url": "<?php echo $this->url('pool', array('action' => 'getData'), null) . '?data=all'; ?>",
      "dataSrc": ""
   },
   "language": {
         "url": "<?php echo $this->basePath() . '/js/dataTables/language/'; ?>" + getLocale('<?php echo $_SESSION['bareos']['locale']; ?>')
   },
   "columns" : [
      { "data": "name" },
      { "data": "pooltype" },
      { "data": "numvols" },
      { "data": "maxvols" },
      { "data": "volretention" },
      { "data": "maxvoljobs" },
      { "data": "maxvolbytes", "type": "file-size" },
      { "data": "volretention" }
   ],
   "paging": true,
   "ordering": true,
   "info": true,
   "pagingType": "full_numbers",
   "stateSave": true,
   "order": [[0, 'asc']],
   "columnDefs": [
      {
         "targets": 0,
         "render": function(data, type, full, meta) {
            return '<a href="<?php echo $this->basePath() . '/pool/details/'; ?>'+data+'">'+data+'</a>';
         }
      },
      {
         "targets": 4,
         "orderData": 7,
         "render": function(data, type, full, meta) {
            return formatRetention(data);
         }
      },
      {
         "targets": 6,
         "render": function(data, type, full, meta) {
            return formatBytes(data);
         }
      },
      {
         "targets": 7,
         "visible": false,
         "searchable": false
      }
   ]
} );

</script>
