.. index::
   :pair: Release Notes; bareos-$VERSION

.. _bareos-$VERSION:

bareos-VERSION
~~~~~~~~~~~~~

================ ===============================================
Code Release     $DATE_OF_GIT_TAG
Database Version $DBVERSION (unchanged)
Release Ticket   :issue:``
Url              http://download.bareos.org/bareos/release/18.2/
                 http://download.bareos.com/bareos/release/18.2/
================ ===============================================

This release contains several bugfixes and enhancements. Excerpt:

-  :issue:``
-  :issue:``
