Specifies the Name that the Director will use when asking to backup or restore to or from to this device. This is the logical Device name, and may be any string up to 127 characters in length. It is generally a good idea to make it correspond to the English name of the backup device. The physical name of the device is specified on the :config:option:`sd/device/ArchiveDevice`\  directive. The name you specify here is also used in your Director’s configuration file on the
:ref:`DirectorResourceStorage` in its Storage resource.

