<?php
  $title = 'Director version';
  $this->headTitle($title);
?>

<h2><?php echo $title; ?></h2>
<hr />

<div class="row">

  <div class="col-md-3">

	  <div class="panel panel-default">
	  
	      <div class="panel-heading">
		  <h3 class="panel-title"><?php echo $this->translate('Director'); ?></h3>
	      </div>
    
	      <div class="panel-body">
	      
	      <table class="table table-striped table-hover">
		<tr><td><a href="<?php echo $this->url('director', array('action'=>'index')); ?>"><?php echo $this->translate('Director status'); ?></a></td></tr>
		<tr><td><a href="<?php echo $this->url('director', array('action'=>'messages')); ?>"><?php echo $this->translate('Director messages'); ?></a></td></tr>
		<tr><td><a href="<?php echo $this->url('director', array('action'=>'scheduler')); ?>"><?php echo $this->translate('Director scheduler status'); ?></a></td></tr>
		<tr><td><a href="<?php echo $this->url('director', array('action'=>'version')); ?>"><?php echo $this->translate('Director version'); ?></a></td></tr>
	      </table>
	      
	      </div>
	      
	  </div>
	  
  </div>

  <div class="col-md-9">
  
    <pre style="font-size: 8pt; color: #00ff00; background-color: #333333;">
    <code>
    <?php
      foreach($this->directorOutput as $row) {
	echo $row ."<br />";
      }
    ?>
    </code>
    </pre>
  
  </div>

</div>
