<?php
  $title = 'Director version';
  $this->headTitle($title);
?>

<h2><?php echo $title; ?></h2>
<hr />

<ul class="nav nav-tabs">
	<li><a href="<?php echo $this->url('director', array('action'=>'index')); ?>"><?php echo $this->translate('Director status'); ?></a></li>
	<li><a href="<?php echo $this->url('director', array('action'=>'messages')); ?>"><?php echo $this->translate('Director messages'); ?></a></li>
	<li><a href="<?php echo $this->url('director', array('action'=>'scheduler')); ?>"><?php echo $this->translate('Director scheduler status'); ?></a></li>
	<li class="active"><a href="<?php echo $this->url('director', array('action'=>'version')); ?>"><?php echo $this->translate('Director version'); ?></a></li>
</ul>

<br />

<div class="row">

  <div class="col-md-12">
  
    <pre style="font-size: 8pt;">
    <code>
    <?php
      foreach($this->directorOutput as $row) {
	echo $row ."<br />";
      }
    ?>
    </code>
    </pre>
  
  </div>

</div>
