#!/bin/sh
#
# Run all root tests
#
echo " "
echo " " >>test.out
echo "Start root tests"
echo "Start root tests" >>test.out
rm -f dumps/*
./run tests/dev-test-root
./run tests/etc-test-root
./run tests/lib-test-root
./run tests/usr-tape-root
echo "End root tests"
echo "End root tests" >>test.out
