#!/bin/sh
#
# Run all tape tests
#
echo "Start autochanger tests"
echo "Start autochanger tests" >>test.out
rm -f dumps/*

./run tests/incremental-changer
./run tests/two-pool-changer
./run tests/two-volume-changer
./run tests/vol-duration-changer

echo "End autochanger tests"
echo "End autochanger tests" >>test.out
