#!/bin/sh
#
# test only the disk based regression scripts
#
set -a

# Include full output
LANG=C
echo "Begin experimental-all `date`"
save_debug=${REGRESS_DEBUG}
REGRESS_DEBUG=1
export REGRESS_DEBUG
rm -rf Testing
rm -f dumps/*
scripts/config_dart
nice ctest -D Experimental -R "^(disk|tape|changer):"
rtn=$?
i=0
while [ $i -le 5 ]; do
   if [ $rtn = 0 ] || [ "$rtn" = "8" ]; then
      break;
   fi
   echo "Submit failed, waiting 5 mins"
   sleep 300
   echo "ctest failed re-running Submit"
   ctest -D ExperimentalSubmit
   rtn=$?
   i=`expr $i + 1`
done
REGRESS_DEBUG=${save_debug}
echo "End experimental-all `date`"
