#!/bin/sh
#
# This script automatically builds the ADD_TEST commands by
# searching for them in the old files
#

for run in all-non-root-2tape all-non-root-tape all-non-root all-root all-tape-and-file ; do
    for test in `grep -h tests/ ${run}-tests | grep -v '^#' | sed -e 's,^.*tests/,,'` ; do
        echo ADD_TEST\(${run}:${test} \"@regressdir@/tests/${test}\"\)
    done
done
