#!/bin/sh
./starttime
export REGRESS_DEBUG=1
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 ; do
  echo "$i. Doing $1 at `date +%R:%S`"
  nice $1 >1
  r=$?
  if [ $r -ne 0 ] ; then
     echo "Exit $r"
     exit 1
  fi
done
./endtime
