#!/bin/sh
#
# Run a simple backup of the Bareos build directory then create some
#   new files, do an Incremental and restore those two files.
#
# This script uses the autochanger and two drives
#
TestName="2drive-incremental-changer"
JobName="2drive2tape"
. scripts/functions

require_tape_drive
require_autochanger
require_second_drive

scripts/copy-2drive-confs
scripts/cleanup-2drive

change_jobname localhost-fd $JobName

echo "${cwd}/tmp/build" >${cwd}/tmp/file-list
if test ! -d ${cwd}/tmp/build ; then
   mkdir -p ${cwd}/tmp/build
fi
cp -p ${cwd}/build/src/dird/*.c ${cwd}/tmp/build
cd ${cwd}/tmp
echo "${cwd}/tmp/build/ficheriro1.txt" >restore-list
echo "${cwd}/tmp/build/ficheriro2.txt" >>restore-list
cd ${cwd}

# Turn off Prefer Mounted Volumes so we use 2 drives
outf="${cwd}/tmp/sed_tmp"
echo "s%# Prefer Mounted Volumes%  Prefer Mounted Volumes%g" >${outf}
cp ${cwd}/bin/bareos-dir.conf ${cwd}/tmp/1
# Comment the next line out to write everything to one drive
#  otherwise, it writes the two jobs to different drives
sed -f ${outf} ${cwd}/tmp/1 >${cwd}/bin/bareos-dir.conf

start_test

# Write out bconsole commands
cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
label storage=tape volume=TestVolume001 slot=$SLOT1 Pool=Default drive=$DRIVE1
label storage=tape volume=TestVolume002 slot=$SLOT2 Pool=Default drive=$DRIVE2
@#setdebug level=100 storage=tape
run job=NightlySave yes
run job=NightlySave yes
run job=NightlySave yes
run job=NightlySave yes
run job=NightlySave yes
@sleep 3
status storage=tape
wait
list volumes
list jobs
status storage=tape
messages
quit
END_OF_DATA

run_bareos

echo "ficheriro1.txt" >${cwd}/tmp/build/ficheriro1.txt
echo "ficheriro2.txt" >${cwd}/tmp/build/ficheriro2.txt

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
@# Force Incremental on the second Volume
update volume=TestVolume001 VolStatus=Used
status storage=tape
@#setdebug level=400 storage=tape
run level=Incremental job=NightlySave yes
wait
list volumes
status storage=tape
messages
@#
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bareos-restores
7
<${cwd}/tmp/restore-list

yes
wait
messages
quit
END_OF_DATA

run_bconsole
check_for_zombie_jobs storage=tape
stop_bareos

check_two_logs
#
# Delete .c files because we will only restored the txt files
#
rm -f ${cwd}/tmp/build/*.c
check_restore_tmp_build_diff

end_test
