#!/bin/sh
#
# Run eighty jobs at the same time
#
TestName="eighty-simultaneous-jobs-tape"
JobName=EightySimultaneousJobs
. scripts/functions

require_tape_drive

scripts/cleanup-tape
scripts/copy-tape-confs
change_jobname $JobName

# Directory to backup.
# This directory will be created by setup_data().
BackupDirectory="${tmp}/data"

# Use a tgz to setup data to be backuped.
# Data will be placed at "${tmp}/data/".
setup_data data/small.tgz

# the default fileset FS_TESTJOB backups all file and directories defined in "${tmp}/file-list".
echo "${BackupDirectory}" >${tmp}/file-list


start_test

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
label storage=tape volume=TestVolume001 slot=0 pool=Default
@#setdebug level=60 Storage=tape
@#setdebug level=60 client
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
status client
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
status client
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
status client
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
@sleep 2
status dir
status client
@sleep 5
status dir
status client
status storage=tape
messages
wait
messages
@#
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bareos-restores select storage=tape
unmark *
mark *
done
yes
wait
messages
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=tape
stop_bareos

check_two_logs
check_restore_diff
end_test
