#!/bin/sh
#
# Run a simple backup
#   to a tape where we set the minimum and maximum block
#   sizes.
#
TestName="fixed-block-size-tape"
JobName=fixedblocksize
. scripts/functions

require_tape_drive

scripts/cleanup

copy_tape_confs
cp ${cwd}/bin/bareos-sd.conf ${cwd}/tmp/1
echo "s%# Maximum Block Size%  Maximum Block Size%" >${cwd}/tmp/2
echo "s%# Minimum Block Size%  Minimum Block Size%" >>${cwd}/tmp/2
sed -f ${cwd}/tmp/2 ${cwd}/tmp/1 >${cwd}/bin/bareos-sd.conf
if [ $? != 0 ] ; then
   echo " "
   echo " "
   echo "!!!! sed problem in Fixed Block Size test !!!!!"
   echo " "
   exit 1
fi
rm -f ${cwd}/tmp/1 ${cwd}/tmp/2

change_jobname NightlySave $JobName

# Directory to backup.
# This directory will be created by setup_data().
BackupDirectory="${tmp}/data"

# Use a tgz to setup data to be backed up.
# Data will be placed at "${tmp}/data/".
setup_data data/small.tgz

# the default fileset FS_TESTJOB backups all file and directories defined in "${tmp}/file-list".
echo "${BackupDirectory}" >${tmp}/file-list


start_test


cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
setdebug level=51 storage=tape
label storage=tape volume=TestVolume001 slot=0 pool=Default
run job=$JobName yes
wait
messages
@#
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bareos-restores select storage=tape
unmark *
mark *
done
yes
wait
messages
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=tape
stop_bareos

check_two_logs
check_restore_diff
end_test
