#!/bin/sh
#
# Run four jobs at the same time
#
TestName="four-concurrent-jobs-tape"
JobName=FourConcurrentJobs
. scripts/functions

require_tape_drive

scripts/cleanup-tape
scripts/copy-tape-confs

change_jobname $JobName

# Directory to backup.
# This directory will be created by setup_data().
BackupDirectory="${tmp}/data"

# Use a tgz to setup data to be backed up.
# Data will be placed at "${tmp}/data/".
setup_data data/small.tgz

# the default fileset FS_TESTJOB backups all file and directories defined in "${tmp}/file-list".
echo "${BackupDirectory}" >${tmp}/file-list


start_test

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
label storage=tape volume=TestVolume001 slot=0 pool=Default
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
run job=$JobName level=Full Storage=tape yes
@sleep 2
status dir
@sleep 5
status dir
status storage=tape
messages
wait
messages
@$out ${cwd}/tmp/jobmedia.out
list volumes
sql
select JobId,MediaId,StartFile,StartBlock,EndFile,EndBlock from JobMedia;

@#
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bareos-restores select storage=tape
unmark *
mark *
done
yes
wait
messages
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=tape
stop_bareos

check_two_logs
check_restore_diff
end_test
