#!/bin/sh
#
# Run four jobs at the same time, with two Volumes.
#   Set max Vol bytes of first volume
#   to less than total backup to force Bareos to use the second
#   Volume.
#
TestName="four-concurrent-jobs-test"
JobName=Four-concurrent-jobs
. scripts/functions

scripts/cleanup
scripts/copy-test-confs

# Directory to backup.
# This directory will be created by setup_data().
BackupDirectory="${tmp}/data"

# Use a tgz to setup data to be backed up.
# Data will be placed at "${tmp}/data/".
setup_data data/small.tgz

# the default fileset FS_TESTJOB backups all file and directories defined in "${tmp}/file-list".
echo "${BackupDirectory}" >${tmp}/file-list



change_jobname NightlySave $JobName
start_test

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out   ${cwd}/tmp/log1.out
label storage=File1
TestVolume001
label storage=File1
TestVolume002
update Volume=TestVolume001 MaxVolBytes=100000000
@#50000000
@#12
setdebug level=51 Storage=File1
status storage=File1
status client
llist volume=TestVolume001
llist volume=TestVolume002
list nextvol
1
run job=$JobName level=Full Storage=File1
yes
@#reload
llist volume=TestVolume001
llist volume=TestVolume002
list nextvol
1
run job=$JobName level=Full Storage=File1
yes
@#reload
llist volume=TestVolume001
llist volume=TestVolume002
list nextvol
1
run job=$JobName level=Full Storage=File1
yes
@#reload
llist volume=TestVolume001
llist volume=TestVolume002
list nextvol
1
status storage=File1
run job=$JobName level=Full Storage=File1
yes
status storage=File1
status client
@#reload
@#reload
list nextvol
1
@sleep 2
status dir
status client
status storage=File1
llist volume=TestVolume001
llist volume=TestVolume002
@#reload
@sleep 5
messages
@#reload
wait
status client
status storage=File1
@#reload
list nextvol
1
messages
@#
@# now do a restore
@#
@$out ${cwd}/tmp/jobmedia.out
list volumes
sql
select JobId,MediaId,StartFile,StartBlock,EndFile,EndBlock from JobMedia;


@$out   ${cwd}/tmp/log2.out
status client
status storage=File1
setdebug level=100 Storage=File1
restore where=${cwd}/tmp/bareos-restores select storage=File1
unmark *
mark *
done
yes
wait
run job=$JobName level=Full Storage=File1 yes
wait
@#reload
messages
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=File1
stop_bareos

check_two_logs
check_restore_diff
end_test
