#!/bin/sh
#
# Run full tape tests assumes you have an autochanger
#
. ./config

#
# If we have an autoloader, load the tape in slot1
if test ! x$AUTOCHANGER = x/dev/null ; then
   a=`bin/mtx-changer $AUTOCHANGER loaded $SLOT1 $TAPE_DRIVE $DRIVE1`
   if test $a = 0 ; then
      bin/mtx-changer $AUTOCHANGER load $SLOT1 $TAPE_DRIVE $DRIVE1
   fi
fi
echo " "
echo " " >>test.out
echo "Start full tape tests"
echo "Start full tape tests" >>test.out

# Non-autochanger tests
nicd tests/btest-test-tape
nice tests/ansi-label-tape
nice tests/backup-bareos-tape
nice tests/bscan-tape
nice tests/eighty-simultaneous-jobs-tape
nice tests/eot-fail-tape
nice tests/fixed-block-size-tape
nice tests/four-concurrent-jobs-tape
nice tests/four-jobs-tape
nice tests/incremental-2media-tape
nice tests/incremental-tape
nice tests/memory-bug-tape
nice tests/relabel-tape
nice tests/restore-by-file-tape
nice tests/restore-seek-tape
nice tests/small-file-size-tape
nice tests/truncate-bug-tape
nice tests/verify-vol-tape

# Autochanger tests
nice tests/btest-test-changer
nice tests/2drive-incremental-changer
nice tests/bad-label-changer
nice tests/incremental-changer
nice tests/two-pool-changer
nice tests/two-volume-changer
nice tests/vol-duration-changer

# very long
# nice tests/btape-fill-full-tape
# nice tests/btape-fill-full-changer

# requires manual intervention
# nice tests/manual-two-vol-tape

echo "End full non-root tape tests"
echo "End full non-root tape tests" >>test.out
