#!/bin/sh
#
# Run a simple backup. Then create some
#   new files, do an Incremental and restore those two files.
#
# This script uses the autochanger and two tapes
#
TestName="incremental-changer"
JobName=incrementalchanger
. scripts/functions

require_tape_drive
require_autochanger

scripts/cleanup
scripts/copy-2tape-confs
scripts/prepare-two-tapes

# Directory to backup.
# This directory will be created by setup_data().
BackupDirectory="${tmp}/data"

# Use a tgz to setup data to be backuped.
# Data will be placed at "${tmp}/data/".
setup_data data/flat-c.tgz
echo "${BackupDirectory}/ficheriro1.txt" >${tmp}/restore-list
echo "${BackupDirectory}/ficheriro2.txt" >>${tmp}/restore-list

# the default fileset FS_TESTJOB backups all file and directories defined in "${tmp}/file-list".
echo "${BackupDirectory}" >${tmp}/file-list


start_test

# Write out bconsole commands
cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
label storage=tape volume=TestVolume001 slot=$SLOT1 Pool=Default drive=$DRIVE1
label storage=tape volume=TestVolume002 slot=$SLOT2 Pool=Default drive=$DRIVE1
run job=NightlySave yes
wait
messages
quit
END_OF_DATA

run_bareos

echo "ficheriro1.txt" >${BackupDirectory}/ficheriro1.txt
echo "ficheriro2.txt" >${BackupDirectory}/ficheriro2.txt


cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
@# Force Incremental on the second Volume
update volume=TestVolume001 VolStatus=Used
run level=Incremental job=NightlySave yes
wait
messages
@#
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bareos-restores
7
<${cwd}/tmp/restore-list

yes
wait
messages
quit
END_OF_DATA

run_bconsole

check_for_zombie_jobs storage=tape
stop_bareos
check_two_logs
rstat=$?

check_restore_files_diff `cat ${tmp}/restore-list`
end_test
