#!/bin/sh
#
# Run a simple backup with encryption and compression
#   then verify the signatures.
#
TestName="lz4hc-encrypt-test"
JobName=lz4hcTest
. scripts/functions

scripts/cleanup

#
# See if library is linked against libfastlz
#
if ! check_linked_against fastlz; then
   echo "$TestName skipped: not linked for fastlz compression"
   exit 0
fi

scripts/copy-crypto-confs


# Directory to backup.
# This directory will be created by setup_data().
BackupDirectory="${tmp}/data"

# Use a tgz to setup data to be backed up.
# Data will be placed at "${tmp}/data/".
setup_data data/small.tgz

# the default fileset FS_TESTJOB backups all file and directories defined in "${tmp}/file-list".
echo "${BackupDirectory}" >${tmp}/file-list


start_test

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
label storage=File volume=TestVolume001
run job=$JobName yes
wait
messages
list volumes
@#
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
@# setdebug level=0 fd
restore where=${cwd}/tmp/bareos-restores storage=File
5
mark *
done
yes
wait
messages
quit
END_OF_DATA

run_bareos
sleep 2
check_for_zombie_jobs storage=File
stop_bareos

check_two_logs
check_restore_diff
end_test
