#!/bin/sh
#
# Run a simple backup
#   to a tape where the maximum tape file size is set to 1M
#   then restore a few files from it.  Note, by setting the maximum
#   file size to 1M, it runs very slow. There are about 64 files that
#   are created during each of the two backups.
#
TestName="restore-by-file-tape"
JobName=restorebyfile
. scripts/functions

require_tape_drive

scripts/cleanup-tape
scripts/copy-tape-confs


cp ${cwd}/bin/bareos-sd.conf ${cwd}/tmp/1
sed "s%# Maximum File Size%  Maximum File Size%" ${cwd}/tmp/1 >${cwd}/bin/bareos-sd.conf

change_jobname NightlySave $JobName

# Directory to backup.
# This directory will be created by setup_data().
BackupDirectory="${tmp}/data"

# Use a tgz to setup data to be backuped.
# Data will be placed at "${tmp}/data/".
setup_data data/small.tgz

# the default fileset FS_TESTJOB backups all file and directories defined in "${tmp}/file-list".
echo "${BackupDirectory}" >${tmp}/file-list

number_of_files_to_restore=5
find "${BackupDirectory}" -type f | head -n ${number_of_files_to_restore} | sort | uniq >${tmp}/restore-list


start_test

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out   ${cwd}/tmp/log1.out
label storage=tape volume=TestVolume001 slot=0 pool=Default
run job=$JobName level=Full yes
wait
messages
@#
@# now do a restore
@#
@$out   ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bareos-restores storage=tape file=<${cwd}/tmp/restore-list
yes
wait
messages
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=tape
stop_bareos

dstat=0
#
# We need to stop and start Bareos to
#  test appending to a previously written tape
#
check_restore_files_diff `cat ${tmp}/restore-list`

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out   ${cwd}/tmp/log1.out
run job=$JobName  level=Full yes
wait
messages
@#
@# now do a restore
@#
@$out   ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bareos-restores
7
<${cwd}/tmp/restore-list

yes
wait
messages
quit
END_OF_DATA

#
# Bareos was stopped, but we must restart it to
#  test appending to a previously written tape
#
run_bareos
check_for_zombie_jobs storage=tape
stop_bareos

check_two_logs

check_restore_files_diff `cat ${tmp}/restore-list`

end_test
