#!/bin/sh
#
# Run a simple backup  using the compressed option
#   then restore it.
#

TestName="restore-by-file-test"
JobName=restorebyfile
. scripts/functions

scripts/cleanup
scripts/copy-test-confs
change_jobname CompressedTest $JobName

# Directory to backup.
# This directory will be created by setup_data().
BackupDirectory="${tmp}/data"

# Use a tgz to setup data to be backuped.
# Data will be placed at "${tmp}/data/".
setup_data data/small.tgz

# the default fileset FS_TESTJOB backups all file and directories defined in "${tmp}/file-list".
echo "${BackupDirectory}" >${tmp}/file-list

number_of_files_to_restore=5
find "${BackupDirectory}" -type f | head -n ${number_of_files_to_restore} | sort | uniq >${tmp}/restore-list


start_test

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
label storage=File volume=TestVolume001
run job=$JobName yes
wait
messages
@#
@# now run 10 restores
@#
@$out ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bareos-restores storage=File
7
<${cwd}/tmp/restore-list

yes
wait
restore where=${cwd}/tmp/bareos-restores storage=File
7
<${cwd}/tmp/restore-list

yes
wait
restore where=${cwd}/tmp/bareos-restores storage=File
7
<${cwd}/tmp/restore-list

yes
wait
restore where=${cwd}/tmp/bareos-restores storage=File
7
<${cwd}/tmp/restore-list

yes
wait
restore where=${cwd}/tmp/bareos-restores storage=File
7
<${cwd}/tmp/restore-list

yes
wait
restore where=${cwd}/tmp/bareos-restores storage=File
7
<${cwd}/tmp/restore-list

yes
wait
restore where=${cwd}/tmp/bareos-restores storage=File
7
<${cwd}/tmp/restore-list

yes
wait
restore where=${cwd}/tmp/bareos-restores storage=File
7
<${cwd}/tmp/restore-list

yes
wait
restore where=${cwd}/tmp/bareos-restores storage=File
7
<${cwd}/tmp/restore-list

yes
wait
restore where=${cwd}/tmp/bareos-restores storage=File
7
<${cwd}/tmp/restore-list

yes
wait
restore where=${cwd}/tmp/bareos-restores storage=File
7
<${cwd}/tmp/restore-list

yes
wait
messages
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=File
stop_bareos

check_two_logs
check_restore_files_diff `cat ${tmp}/restore-list`
end_test
