#!/bin/sh
#
# Run a simple backup . Create three
#   tapes, each in a different pool, then run two jobs both of which
#   want the tape that is not loaded.  Note, they both have
#   prefers non-mounted tapes.  This should expose bug #801
#
# This script uses the virtual disk autochanger and two drives
#
TestName="three-pool-disk"
JobName="threepooldisk"
. scripts/functions

scripts/cleanup
scripts/copy-2disk-drive-confs
scripts/prepare-disk-changer
CLIENT=2drive2disk


# Directory to backup.
# This directory will be created by setup_data().
BackupDirectory="${tmp}/data"

# Use a tgz to setup data to be backed up.
# Data will be placed at "${tmp}/data/".
setup_data data/small.tgz

# the default fileset FS_TESTJOB backups all file and directories defined in "${tmp}/file-list".
echo "${BackupDirectory}" >${tmp}/file-list


change_jobname NightlySave $JobName
start_test

# Turn off Prefer Mounted Volumes so we use 2 drives
outf="${cwd}/tmp/sed_tmp"
echo "s%# Prefer Mounted Volumes%  Prefer Mounted Volumes%g" >${outf}
cp ${cwd}/bin/bareos-dir.conf ${cwd}/tmp/1
# Comment the next line out to write everything to one drive
#  otherwise, it writes the two jobs to different drives
sed -f ${outf} ${cwd}/tmp/1 >${cwd}/bin/bareos-dir.conf

# Write out bconsole commands
cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@out /dev/null
messages
@$out ${cwd}/tmp/log1.out
@#setdebug level=200 storage=tape
@#setdebug level=200 client=$CLIENT
label storage=tape volume=TestVolume001 slot=1 Pool=Default drive=0
label storage=tape volume=TestVolume002 slot=2 Pool=Full    drive=0
label storage=tape volume=TestVolume003 slot=3 Pool=Inc     drive=1
status storage=tape
run job=$JobName level=Full Pool=Default yes
run job=$JobName level=Full Pool=Default yes
run job=$JobName level=Full Pool=Default yes
run job=$JobName level=Full Pool=Default yes
run job=$JobName level=Full Pool=Default yes
setdebug level=200 storage=tape
@sleep 10
status storage=tape
list volumes
wait
list volumes
list jobs
status storage=tape
messages
quit
END_OF_DATA

# exit

run_bareos
cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@out /dev/null
messages
@#
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bareos-restores select all storage=tape done
yes
wait
messages
quit
END_OF_DATA

run_bconsole

check_for_zombie_jobs storage=tape
stop_bareos

check_two_logs
check_restore_diff

end_test
