#!/bin/sh
#
# Run a simple connection test
#   with the tray-monitor.
#
TestName="tray-monitor-connection-test"
. scripts/functions

scripts/cleanup
scripts/copy-confs
tray_monitor_binary="${bin}/bareos-tray-monitor"

start_test

# check if tray-monitor binary was built
if [ ! -f ${tray_monitor_binary} ]; then
    set_error "Could not find executable ${tray_monitor_binary}"
    end_test
    exit 1
fi

rm -f bin/bareos-dir.conf
rm -f bin/bareos-fd.conf
rm -f bin/bareos-sd.conf
rm -f bin/tray-monitor.conf

/bin/cp -f ${rconfigs}/${TestName}/bareos-dir.conf.tray-monitor-connection-test.tls-psk ${bin}/bareos-dir.conf
/bin/cp -f ${rconfigs}/${TestName}/bareos-fd.conf.tray-monitor-connection-test.tls-psk ${bin}/bareos-fd.conf
/bin/cp -f ${rconfigs}/${TestName}/bareos-sd.conf.tray-monitor-connection-test.tls-psk ${bin}/bareos-sd.conf
/bin/cp -f ${rconfigs}/${TestName}/bareos-tray-monitor.conf.tray-monitor-connection-test.tls-psk ${bin}/tray-monitor.conf

run_bareos
${tray_monitor_binary} -rc -c ${bin}/tray-monitor.conf
estat_tls_psk=$?
stop_bareos

/bin/cp -f ${rconfigs}/${TestName}/bareos-dir.conf.tray-monitor-connection-test.cleartext ${bin}/bareos-dir.conf
/bin/cp -f ${rconfigs}/${TestName}/bareos-fd.conf.tray-monitor-connection-test.cleartext ${bin}/bareos-fd.conf
/bin/cp -f ${rconfigs}/${TestName}/bareos-sd.conf.tray-monitor-connection-test.cleartext ${bin}/bareos-sd.conf
/bin/cp -f ${rconfigs}/${TestName}/bareos-tray-monitor.conf.tray-monitor-connection-test.cleartext ${bin}/tray-monitor.conf

run_bareos
${tray_monitor_binary} -rc -c ${bin}/tray-monitor.conf
estat_cleartext=$?
stop_bareos

export estat
let estat=estat_tls_psk+estat_cleartext

end_test

