OS:
  ULC_rpm:
    "OpenSSL_1.1":
      TYPE: scripted
      IMAGE: "rhel8"
      BUILD_SCRIPT: CD/rpm/build-ulc.sh
      FINISH_SCRIPT: CD/rpm/finish-ulc.sh
      CUSTOM_TEST_IMAGES: [ Rocky-8, Rocky-9, Fedora-37, SLE-15_sp6 ]
      ARCH:
        - x86_64
        - aarch64
    "OpenSSL_3.0":
      TYPE: scripted
      IMAGE: "rhel9"
      BUILD_SCRIPT: CD/rpm/build-ulc.sh
      FINISH_SCRIPT: CD/rpm/finish-ulc.sh
      CUSTOM_TEST_IMAGES: [ Rocky-9, Fedora-41, SLE-15_sp6, Mageia-9 ]
      ARCH:
        - x86_64
        - aarch64
    "OpenSSL_3.0":
      TYPE: scripted
      IMAGE: "rhel10"
      BUILD_SCRIPT: CD/rpm/build-ulc.sh
      FINISH_SCRIPT: CD/rpm/finish-ulc.sh
      CUSTOM_TEST_IMAGES: [ Rocky-9, Fedora-41, SLE-15_sp6, Mageia-9 ]
      ARCH:
        - x86_64
        - aarch64
        - x86_64
  EL:
    "10":
      TYPE: rpm
      IMAGE: rhel10
      CUSTOM_TEST_IMAGES: [ Rocky, Alma, Oracle, Stream, RHEL ]
      ARCH:
        - x86_64
        - aarch64
    "9":
      TYPE: rpm
      IMAGE: rhel9
      CUSTOM_TEST_IMAGES: [ Rocky, Alma, Oracle, Stream, RHEL ]
      ARCH:
        - x86_64
        - aarch64
    "8":
      TYPE: rpm
      IMAGE: rhel8
      CUSTOM_TEST_IMAGES: [ Rocky, Alma, Oracle, RHEL ]
      ARCH:
        - x86_64
