OS:
  Sanitize:
    "F42":
      TYPE: scripted
      IMAGE: fedora42
      BUILD_SCRIPT: bareos/devtools/build-and-test-with-sanitize.sh
      FINISH_SCRIPT: CD/sanitize/finish-sanitize.sh
      ARCH:
        - x86_64
  ULC_rpm:
    "OpenSSL_1.1":
      TYPE: scripted
      IMAGE: "rhel8"
      BUILD_SCRIPT: CD/rpm/build-ulc.sh
      FINISH_SCRIPT: CD/rpm/finish-ulc.sh
      CUSTOM_TEST_IMAGES: [ Rocky-9, SLE-15_sp6 ]
      ARCH:
        - x86_64
        - aarch64
    "OpenSSL_3.0":
      TYPE: scripted
      IMAGE: "rhel9"
      BUILD_SCRIPT: CD/rpm/build-ulc.sh
      FINISH_SCRIPT: CD/rpm/finish-ulc.sh
      CUSTOM_TEST_IMAGES: [ SLE-15_sp6, Mageia-9 ]
      ARCH:
        - x86_64
        - aarch64
  ULC_deb:
    "OpenSSL_1.1":
      TYPE: scripted
      IMAGE: "ubuntu20.04"
      BUILD_SCRIPT: CD/deb/build-ulc.sh
      FINISH_SCRIPT: CD/deb/finish-ulc.sh
      CUSTOM_TEST_IMAGES: [ "Debian-11" ]
      ARCH:
        - x86_64
        - aarch64
    "OpenSSL_3.0":
      TYPE: scripted
      IMAGE: "ubuntu22.04"
      BUILD_SCRIPT: CD/deb/build-ulc.sh
      FINISH_SCRIPT: CD/deb/finish-ulc.sh
      CUSTOM_TEST_IMAGES: [ "Ubuntu-24.04", "Debian-12" ]
      ARCH:
        - x86_64
        - aarch64
  xUbuntu:
    "24.04":
      TYPE: deb
      IMAGE: "ubuntu24.04"
      ARCH:
        - x86_64
    "22.04":
      TYPE: deb
      IMAGE: "ubuntu22.04"
      ARCH:
        - x86_64
  SUSE:
    "15":
      TYPE: rpm
      IMAGE: sle155
      CUSTOM_TEST_IMAGES: [ SLE-15_SP3, SLE-15_SP6, openSUSE-Leap_15.6 ]
      ARCH:
      - x86_64
  Fedora:
    "42":
      TYPE: rpm
      IMAGE: fedora42
      ARCH:
      - x86_64
    "41":
      TYPE: rpm
      IMAGE: fedora41
      ARCH:
      - x86_64
  Debian:
    "13":
      TYPE: deb
      IMAGE: "debian13"
      ARCH:
        - x86_64
    "12":
      TYPE: deb
      IMAGE: "debian12"
      ARCH:
        - x86_64
    "11":
      TYPE: deb
      IMAGE: "debian11"
      ARCH:
        - x86_64
  EL:
    "10":
      TYPE: rpm
      IMAGE: rhel10
      CUSTOM_TEST_IMAGES: [ RHEL ]
      ARCH:
        - x86_64
        - aarch64
    "9":
      TYPE: rpm
      IMAGE: rhel9
      CUSTOM_TEST_IMAGES: [ Stream, RHEL ]
      ARCH:
        - x86_64
        - aarch64
    "8":
      TYPE: rpm
      IMAGE: rhel8
      CUSTOM_TEST_IMAGES: [ RHEL ]
      ARCH:
        - x86_64
  FreeBSD:
    "14":
      TYPE: freebsd
      ARCH:
        - amd64
    "13":
      TYPE: freebsd
      ARCH:
        - amd64
  MacOS:
    "10.13.6":
      TYPE: macos
      ARCH:
        - x64
  win:
    native:
      TYPE: win-native
      BUILD_SCRIPT: CD/windows/build-ninja.bat
      STAGES:
        - win-native-64-release
      ARCH:
       - x86_64
      WINVERSIONS:
         - windows-11-64
