OS:
  Sanitize:
    "F43":
      TYPE: scripted
      IMAGE: fedora43
      BUILD_SCRIPT: bareos/devtools/build-and-test-with-sanitize.sh
      FINISH_SCRIPT: CD/sanitize/finish-sanitize.sh
      ARCH:
        - x86_64
  Debian:
    "13":
      TYPE: deb
      IMAGE: "debian13"
      ARCH:
        - x86_64
