OS:
  Debian:
    "13":
      TYPE: deb
      IMAGE: "debian13"
      ARCH:
        - x86_64
  EL:
    "10":
      TYPE: rpm
      IMAGE: rhel10
      CUSTOM_TEST_IMAGES: [ RHEL ]
      ARCH:
        - x86_64
  win:
    native:
      TYPE: win-native
      BUILD_SCRIPT: CD/windows/build-ninja.bat
      STAGES:
        - win-native-64-release
      ARCH:
       - x86_64
      WINVERSIONS:
         - windows-11-64
