OS:
  ULC_deb:
    "OpenSSL_1.1":
      TYPE: scripted
      IMAGE: "ubuntu20.04"
      BUILD_SCRIPT: CD/deb/build-ulc.sh
      FINISH_SCRIPT: CD/deb/finish-ulc.sh
      CUSTOM_TEST_IMAGES: [ "Debian-11" ]
      ARCH:
        - x86_64
        - aarch64
    "OpenSSL_3.0":
      TYPE: scripted
      IMAGE: "ubuntu22.04"
      BUILD_SCRIPT: CD/deb/build-ulc.sh
      FINISH_SCRIPT: CD/deb/finish-ulc.sh
      CUSTOM_TEST_IMAGES: [ "Ubuntu-24.04", "Debian-12" ]
      ARCH:
        - x86_64
        - aarch64
  xUbuntu:
    "24.04":
      TYPE: deb
      IMAGE: "ubuntu24.04"
      ARCH:
        - x86_64
  Debian:
    "13":
      TYPE: deb
      IMAGE: "debian13"
      ARCH:
        - x86_64
