OS:
  Sanitize:
    "F41":
      TYPE: scripted
      IMAGE: fedora41
      BUILD_SCRIPT: bareos/devtools/build-and-test-with-sanitize.sh
      FINISH_SCRIPT: CD/sanitize/finish-sanitize.sh
      ARCH:
        - x86_64
  win:
    native:
      TYPE: win-native
      STAGES:
        - win-native-64-release
      ARCH:
       - x86_64
      WINVERSIONS:
         - windows-11-64
