OS:
  Sanitize:
    "F41":
      TYPE: scripted
      IMAGE: fedora41
      BUILD_SCRIPT: bareos/devtools/build-and-test-with-sanitize.sh
      FINISH_SCRIPT: CD/sanitize/finish-sanitize.sh
      ARCH:
        - x86_64
  ULC_rpm:
    "OpenSSL_1.1":
      TYPE: scripted
      IMAGE: "rhel8"
      BUILD_SCRIPT: CD/rpm/build-ulc.sh
      FINISH_SCRIPT: CD/rpm/finish-ulc.sh
      CUSTOM_TEST_IMAGES: [ Rocky-8, Rocky-9, Fedora-37, SLE-15_sp6 ]
      ARCH:
        - x86_64
        - aarch64
    "OpenSSL_3.0":
      TYPE: scripted
      IMAGE: "rhel9"
      BUILD_SCRIPT: CD/rpm/build-ulc.sh
      FINISH_SCRIPT: CD/rpm/finish-ulc.sh
      CUSTOM_TEST_IMAGES: [ Rocky-9, Fedora-41, SLE-15_sp6, Mageia-9 ]
      ARCH:
        - x86_64
        - aarch64
  ULC_deb:
    "OpenSSL_1.1":
      TYPE: scripted
      IMAGE: "ubuntu20.04"
      BUILD_SCRIPT: CD/deb/build-ulc.sh
      FINISH_SCRIPT: CD/deb/finish-ulc.sh
      CUSTOM_TEST_IMAGES: [ "Ubuntu-20.04", "Debian-10", "Debian-11" ]
      ARCH:
        - x86_64
        - aarch64
    "OpenSSL_3.0":
      TYPE: scripted
      IMAGE: "ubuntu22.04"
      BUILD_SCRIPT: CD/deb/build-ulc.sh
      FINISH_SCRIPT: CD/deb/finish-ulc.sh
      CUSTOM_TEST_IMAGES: [ "Ubuntu-22.04", "Ubuntu-24.04", "Debian-12" ]
      ARCH:
        - x86_64
        - aarch64
  xUbuntu:
    "24.04":
      TYPE: deb
      IMAGE: "ubuntu24.04"
      ARCH:
        - x86_64
    "22.04":
      TYPE: deb
      IMAGE: "ubuntu22.04"
      ARCH:
        - x86_64
    "20.04":
      TYPE: deb
      IMAGE: "ubuntu20.04"
      ARCH:
        - x86_64
  SUSE:
    "15":
      TYPE: rpm
      IMAGE: sle155
      CUSTOM_TEST_IMAGES: [ SLE-15_SP3, SLE-15_SP4, openSUSE-Leap_15.4, SLE-15_SP5, openSUSE-Leap_15.5, SLE-15_SP6, openSUSE-Leap_15.6 ]
      ARCH:
      - x86_64
  Fedora:
    "41":
      TYPE: rpm
      IMAGE: fedora41
      ARCH:
      - x86_64
    "40":
      TYPE: rpm
      IMAGE: fedora40
      ARCH:
      - x86_64
  Debian:
    "12":
      TYPE: deb
      IMAGE: "debian12"
      ARCH:
        - x86_64
    "11":
      TYPE: deb
      IMAGE: "debian11"
      ARCH:
        - x86_64
  EL:
    "9":
      TYPE: rpm
      IMAGE: rhel9
      CUSTOM_TEST_IMAGES: [ Rocky, Alma, Oracle, Stream, RHEL ]
      ARCH:
        - x86_64
        - aarch64
    "8":
      TYPE: rpm
      IMAGE: rhel8
      CUSTOM_TEST_IMAGES: [ Rocky, Alma, Oracle, RHEL ]
      ARCH:
        - x86_64
  FreeBSD:
    "14.0":
      TYPE: freebsd
      ARCH:
        - amd64
    "13.3":
      TYPE: freebsd
      ARCH:
        - amd64
    "13.2":
      TYPE: freebsd
      ARCH:
        - amd64
  MacOS:
    "10.13.6":
      TYPE: macos
      ARCH:
        - x64
  win:
    native:
      TYPE: win-native
      STAGES:
        - win-native-64-release
      ARCH:
       - x86_64
      WINVERSIONS:
         - windows-11-64
