---
# quality gates to configure Jenkins build pipeline
coverage:
  lines:
    healthy: 70
    unhealthy: 38
    unstable: 40

SLE_12_SP5:
  ctest_unstable: 9
  warnings_unhealthy: 1
  warnings_healthy: 0

Debian_10:
  ctest_unstable: 9
  warnings_unhealthy: 1
  warnings_healthy: 0

default:
  ctest_unstable: 0
  warnings_unhealthy: 1
  warnings_healthy: 0
