---
# quality gates to configure Jenkins build pipeline
coverage:
  lines:
    healthy: 70
    unhealthy: 38
    unstable: 40

default:
  ctest_unstable: 0
  warnings_unhealthy: 1
  warnings_healthy: 0
