#!/bin/sh
#
# Run all tests
#
echo " "
echo " " >>test.out
echo "Start non-root disk tests"
echo "Start non-root disk tests" >>test.out
rm -f dumps/*
./run tests/acl-xattr-test
./run tests/action-on-purge-test
./run tests/allowcompress-test
./run tests/allowed-scriptdir-test
./run tests/allowed-jobcommand-test
./run tests/accurate-test
./run tests/auto-label-test
./run tests/backup-bareos-test
./run tests/backup-bareos-passive-test
./run tests/bextract-test
./run tests/bconsole-test
./run tests/base-job-test
./run tests/big-vol-test
./run tests/bscan-test
./run tests/bsr-opt-test
./run tests/comment-test
./run tests/compressed-test
./run tests/lzo-test
./run tests/compress-encrypt-test
./run tests/lzo-encrypt-test
./run tests/concurrent-jobs-test
./run tests/copy-job-test
./run tests/copy-jobspan-test
./run tests/copy-uncopied-test
./run tests/copy-upgrade-test
./run tests/copy-volume-test
./run tests/data-encrypt-test
./run tests/data-encrypt-aes256-test
./run tests/data-encrypt-blowfish-test
./run tests/data-encrypt-camellia256-test
./run tests/delete-test
./run tests/encrypt-bug-test
./run tests/estimate-test
./run tests/exclude-dir-test
./run tests/fifo-test
./run tests/fileregexp-test
./run tests/backup-to-null
./run tests/regexwhere-test
# The following two can uses *lots* of disk space
#   so they are normally turned off, but if you have
#   at least two GB free, you can run them
#./run tests/sparse-encrypt-test
#./run tests/gigaslam-sparse-test
./run tests/differential-test
./run tests/four-concurrent-jobs-test
./run tests/four-jobs-test
./run tests/incremental-test
./run tests/query-test
./run tests/recycle-test
./run tests/restore2-by-file-test
./run tests/restore-by-file-test
./run tests/restore-disk-seek-test
./run tests/runscript-test
./run tests/source-addr-test
./run tests/stats-test
./run tests/six-vol-test
./run tests/span-vol-test
./run tests/maxbytes-test
./run tests/maxtime-test
./run tests/maxuseduration-test
./run tests/maxvol-test
./run tests/maxvol2-test
./run tests/messages-test
./run tests/sparse-compressed-test
./run tests/sparse-lzo-test
./run tests/sparse-test
./run tests/strip-test
./run tests/two-jobs-test
./run tests/two-vol-test
./run tests/verify-cat-test
./run tests/verify-vol-test
./run tests/verify-voltocat-test
./run tests/weird-files2-test
./run tests/weird-files-test
./run tests/migration-job-test
./run tests/migration-job-purge-test
./run tests/migration-jobspan-test
./run tests/migration-volume-test
./run tests/migration-time-test
./run tests/multi-storage-test
./run tests/prune-test
#./run tests/prune-config-test
./run tests/prune-migration-test
./run tests/prune-copy-test
./run tests/prune-base-job-test
./run tests/hardlink-test
./run tests/tls-duplicate-job-test
./run tests/tls-test
./run tests/tls-client-initiated-connection-backup-test
./run tests/virtual-changer-test
./run tests/virtual-backup-test
./run tests/quota-softquota-test
./run tests/quota-hardquota-test
./run tests/quota-includefailed-test
./run tests/bandwidth-limit-per-client-test
./run tests/rerun-test
./run tests/status-schedule-test
./run tests/subscription-test
./run tests/lz4-encrypt-test
./run tests/lz4-test
./run tests/lz4hc-encrypt-test
./run tests/lz4hc-test
./run tests/lzfast-encrypt-test
./run tests/lzfast-test
./run tests/config-add-client-test
echo "End non-root disk tests"
echo "End non-root disk tests" >>test.out

#
# The following are Virtual Disk Autochanger tests
echo " "
echo " " >>test.out
echo "Start non-root virtual disk autochanger tests"
echo "Start non-root virtual disk autochanger tests" >>test.out
#./run tests/three-pool-recycle-test
./run tests/two-pool-test
./run tests/fast-two-pool-test
./run tests/two-volume-test
./run tests/incremental-2disk
./run tests/2drive-incremental-2disk
./run tests/scratch-pool-test
./run tests/scratchpool-pool-test
./run tests/2drive-concurrent-test
./run tests/incremental-2media
./run tests/three-pool-test
./run tests/2drive-3pool-test
./run tests/2drive-swap-test
echo "End non-root virtual disk autochanger tests"
echo "End non-root virtual disk autochanger tests" >>test.out
