#!/bin/sh
#
# Run all root tests
#
echo " "
echo " " >>test.out
echo "Start root tests"
echo "Start root tests" >>test.out
rm -f dumps/*
tests/dev-test-root
tests/etc-test-root
tests/lib-test-root
tests/usr-tape-root
echo "End root tests"
echo "End root tests" >>test.out
