#!/bin/sh
#
# Run all tape tests
#
. ./config

#
# If we have an autoloader, load the tape in slot1
if test ! x$AUTOCHANGER = x/dev/null ; then
   a=`bin/mtx-changer $AUTOCHANGER loaded $SLOT1 $TAPE_DRIVE $DRIVE1`
   if test $a = 0 ; then
      bin/mtx-changer $AUTOCHANGER load $SLOT1 $TAPE_DRIVE $DRIVE1
   fi
fi
echo " "
echo " " >>test.out
echo "Start all non-root tape tests"
echo "Start all non-root tape tests" >>test.out
rm -f dumps/*
./run tests/scsi-crypto-test
./run tests/ansi-label-tape
./run tests/backup-bareos-tape
./run tests/bscan-tape
./run tests/block-size-tape
./run tests/fixed-block-size-tape
./run tests/four-concurrent-jobs-tape
./run tests/four-jobs-tape
./run tests/incremental-tape
./run tests/relabel-tape
./run tests/restore-by-file-tape
./run tests/small-file-size-tape
./run tests/truncate-bug-tape
./run tests/verify-vol-tape
# ./run tests/manual-two-vol-tape
echo "End all non-root tape tests"
echo "End all non-root tape tests" >>test.out
