#!/bin/sh
#
# Run a sample of tests. These tests should be relatively short
#   so that developers can test before committing
#
echo " "
echo " " >>test.out
echo "Start sample non-root disk tests"
echo "Start sample non-root disk tests" >>test.out
rm -f dumps/*
nice tests/acl-xattr-test
nice tests/action-on-purge-test
nice tests/allowcompress-test
nice tests/auto-label-test
nice tests/backup-bareos-test
nice tests/base-job-test
nice tests/bextract-test
nice tests/bconsole-test
nice tests/comment-test
nice tests/compressed-test
nice tests/compress-encrypt-test
nice tests/concurrent-jobs-test
nice tests/copy-job-test
nice tests/encrypt-bug-test
nice tests/estimate-test
nice tests/lockmgr-test
nice tests/exclude-dir-test
nice tests/fifo-test
nice tests/fileregexp-test
nice tests/backup-to-null
nice tests/regexwhere-test
nice tests/differential-test
nice tests/four-jobs-test
nice tests/incremental-test
nice tests/query-test
nice tests/recycle-test
nice tests/restore2-by-file-test
nice tests/restore-by-file-test
nice tests/restore-disk-seek-test
nice tests/next-vol-test
nice tests/strip-test
nice tests/two-vol-test
nice tests/verify-vol-test
nice tests/weird-files2-test
nice tests/weird-files-test
nice tests/migration-job-test
nice tests/messages-test
nice tests/multi-storage-test
nice tests/prune-test
nice tests/hardlink-test
nice tests/tls-test
nice tests/virtual-backup-test
echo "End sample non-root disk tests"
echo "End sample non-root disk tests" >>test.out

#
# The following are Disk Autochanger tests
echo " "
echo " " >>test.out
echo "Start sample non-root disk autochanger tests"
echo "Start sample non-root disk autochanger tests" >>test.out
#nice tests/three-pool-recycle-test
nice tests/fast-two-pool-test
nice tests/two-volume-test
nice tests/2drive-concurrent-test
nice tests/incremental-2media
nice tests/2drive-3pool-test
nice tests/2drive-swap-test
echo "End sample non-root disk autochanger tests"
echo "End sample non-root disk autochanger tests" >>test.out
