#!/bin/sh
./starttime
echo " " >test.out
hostname >>test.out
echo " " >>test.out
cat build/config.out >>test.out
echo " " >>test.out
echo "Test results" >>test.out
echo " " >>test.out
./starttime
./all-disk-tests
./all-tape-tests
./all-changer-tests
echo " "
echo "End do_all tests"
echo "End do_all tests" >>test.out
scripts/cleanup
hostname >>test.out
cat test.out
./endtime
