#!/bin/sh
./starttime
if [ ! -f bin/tape_options ] ; then
  touch bin/tape_options
fi
echo " " >test.out
cat build/config.out >>test.out
echo " " >>test.out
echo "Test results" >>test.out
echo " " >>test.out
./starttime
nice ./all-disk-tests
nice ./all-tape-tests
nice ./all-changer-tests
echo " "
echo "End do_all tests"
echo "End do_all tests" >>test.out
scripts/cleanup
cat test.out
./endtime
