#!/bin/sh
echo " " >test.out
cat build/config.out >>test.out
echo " " >>test.out
echo "Test results" >>test.out
echo " " >>test.out
./starttime
nice ./all-disk-tests
echo " "
echo "End do_file tests"
echo "End do_file tests" >>test.out
scripts/cleanup
cat test.out
./endtime
