#!/bin/bash
set -e
set -o pipefail
set -u
#
# Run a backup and cancel it.
# Check that metadata is still saved with checkpoints.
#
TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

backupjob=backup-bareos-fd

backup_log=$tmp/strees-backup.out
csvlog=csvfile.csv

rm -f $backup_log
rm -f $csvlog

echo "runnumber,duration" >> $csvlog

cat << END_OF_DATA >"$tmp/bconcmds"
@$out ${NULL_DEV}
messages
@$out $backup_log
run job=${backupjob} level=Full yes
wait
messages
quit
END_OF_DATA

start_test

for i in {1..10}; do
    rm -f $backup_log
    run_bconsole
    elapsedtime=$(grep 'Elapsed time:       ' $backup_log | sed -n -e 's/^.*time:       //p')
    echo "$i,${elapsedtime}" >> $csvlog
    rm storage/*
done

end_test
