#!/usr/bin/env python3
#
#   BAREOS - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2026-2026 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

import argparse
import hmac
import os
import secrets
import signal
import socket
import ssl
import sys
import time
from pathlib import Path


PROTOCOL_HELLO = "BAREOS-SETUP 1"


def parse_args():
    parser = argparse.ArgumentParser(
        description="Serve the first-slice Bareos client enrollment endpoint."
    )
    parser.add_argument(
        "--connection-direction",
        choices=("client-connects", "director-connects"),
        default="client-connects",
    )
    parser.add_argument("--listen-address", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=10443)
    parser.add_argument("--connect-back-address")
    parser.add_argument("--connect-back-port", type=int)
    parser.add_argument("--connect-timeout", type=int, default=30)
    parser.add_argument("--certificate", required=True)
    parser.add_argument("--key", required=True)
    parser.add_argument("--director-name", required=True)
    parser.add_argument("--director-address", required=True)
    parser.add_argument("--director-port", type=int, default=9101)
    parser.add_argument("--staging-dir", required=True)
    parser.add_argument("--token", required=True)
    parser.add_argument("--shared-password")
    parser.add_argument("--force", action="store_true")
    return parser.parse_args()


def validate_name(field, name):
    if not name:
        raise ValueError(f"{field} must not be empty.")
    if name[0].isspace() or name[-1].isspace():
        raise ValueError(f"{field} must not start or end with whitespace.")
    if len(name) > 127:
        raise ValueError(f"{field} is too long.")
    if "/" in name or "\\" in name:
        raise ValueError(f"{field} must not contain path separators.")


def read_headers(reader):
    headers = []
    while True:
        line = reader.readline()
        if line == b"":
            raise RuntimeError("Client closed the TLS connection.")
        line = line.decode("utf-8").rstrip("\r\n")
        if not line:
            return headers
        if ":" not in line:
            raise ValueError(f"Malformed request header: {line}")
        key, value = line.split(":", 1)
        headers.append((key, value.lstrip()))


def first_header(headers, key, default=None):
    for header_key, header_value in headers:
        if header_key == key:
            return header_value
    return default


def all_headers(headers, key):
    return [value for header_key, value in headers if header_key == key]


def write_atomic(path, content, force):
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not force:
        raise RuntimeError(
            f'Refusing to overwrite existing staged config "{path}". Use --force.'
        )
    temporary = path.with_suffix(path.suffix + ".tmp")
    if force and temporary.exists():
        temporary.unlink()
    with open(temporary, "w", encoding="utf-8") as output:
        output.write(content)
    os.replace(temporary, path)


def build_director_client_config(client_name, address, port, password):
    return (
        "Client {\n"
        f"  Name = {client_name}\n"
        f'  Description = "Generated by bareos-dir-setup-service."\n'
        f"  Address = {address}\n"
        f'  Password = "{password}"\n'
        f"  Port = {port}\n"
        "}\n"
    )


def build_fd_director_config(director_name, password):
    return (
        "Director {\n"
        f"  Name = {director_name}\n"
        f'  Password = "{password}"\n'
        f'  Description = "Generated by bareos-dir-setup-service."\n'
        "}\n"
    )


def send_error(writer, message):
    payload = message.encode("utf-8")
    writer.write(b"ERROR 1\n")
    writer.write(f"message_length: {len(payload)}\n".encode("utf-8"))
    writer.write(b"\n")
    writer.write(payload)
    writer.flush()


def handle_connection(connection, peer_address, args):
    reader = connection.makefile("rb")
    writer = connection.makefile("wb")
    try:
        hello = reader.readline()
        if hello == b"":
            raise RuntimeError("Client closed the TLS connection.")
        if hello.decode("utf-8").rstrip("\r\n") != PROTOCOL_HELLO:
            raise ValueError("Unsupported enrollment protocol.")

        headers = read_headers(reader)
        token = first_header(headers, "token")
        if token is None:
            raise ValueError("Missing token header.")
        if not hmac.compare_digest(token, args.token):
            raise ValueError("Enrollment token rejected.")

        client_name = first_header(headers, "client_name")
        validate_name("client_name", client_name)

        fd_port = first_header(headers, "fd_port")
        if fd_port is None:
            raise ValueError("Missing fd_port header.")
        fd_port = int(fd_port)
        if fd_port <= 0 or fd_port > 65535:
            raise ValueError("fd_port must be between 1 and 65535.")

        advertise_addresses = [addr for addr in all_headers(headers, "advertise_address") if addr]
        client_address = advertise_addresses[0] if advertise_addresses else peer_address[0]
        if not client_address:
            raise ValueError("Could not determine a client address to stage.")

        password = args.shared_password or secrets.token_urlsafe(33)
        stage_path = (
            Path(args.staging_dir)
            / "bareos-dir.d"
            / "client"
            / f"{client_name}.conf"
        )
        stage_content = build_director_client_config(
            client_name, client_address, fd_port, password
        )
        write_atomic(stage_path, stage_content, args.force)

        fd_config = build_fd_director_config(args.director_name, password).encode("utf-8")
        writer.write(b"OK 1\n")
        writer.write(f"director_name: {args.director_name}\n".encode("utf-8"))
        writer.write(f"stage_path: {stage_path}\n".encode("utf-8"))
        writer.write(f"config_length: {len(fd_config)}\n".encode("utf-8"))
        writer.write(b"\n")
        writer.write(fd_config)
        writer.flush()
    except Exception as exc:
        send_error(writer, str(exc))
    finally:
        try:
            writer.close()
        finally:
            reader.close()


def connect_back(args):
    if not args.connect_back_address or not args.connect_back_port:
        raise ValueError(
            "director-connects mode requires --connect-back-address and --connect-back-port."
        )

    deadline = time.monotonic() + args.connect_timeout
    while time.monotonic() < deadline:
        try:
            client = socket.create_connection(
                (args.connect_back_address, args.connect_back_port), timeout=1.0
            )
            client.settimeout(None)
            return client
        except OSError:
            time.sleep(0.2)

    raise RuntimeError(
        "Timed out connecting back to the File Daemon setup tool at "
        f"{args.connect_back_address}:{args.connect_back_port}."
    )


def main():
    args = parse_args()
    validate_name("director_name", args.director_name)

    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    context.load_cert_chain(certfile=args.certificate, keyfile=args.key)

    should_stop = False

    def _handle_signal(_signum, _frame):
        nonlocal should_stop
        should_stop = True

    signal.signal(signal.SIGTERM, _handle_signal)
    signal.signal(signal.SIGINT, _handle_signal)

    if args.connection_direction == "director-connects":
        with connect_back(args) as client:
            peer_address = client.getpeername()
            # The setup service intentionally stays the TLS server even when it
            # opened the TCP connection. The FD tool still verifies this service's
            # certificate fingerprint, so TCP direction does not alter trust.
            with context.wrap_socket(client, server_side=True) as tls_connection:
                handle_connection(tls_connection, peer_address, args)
    else:
        with socket.create_server((args.listen_address, args.port), reuse_port=False) as server:
            server.settimeout(0.5)
            actual_port = server.getsockname()[1]
            print(f"LISTENING {actual_port}", flush=True)

            while not should_stop:
                try:
                    client, peer_address = server.accept()
                except TimeoutError:
                    continue
                except OSError as exc:
                    if should_stop:
                        break
                    raise exc

                with client:
                    with context.wrap_socket(client, server_side=True) as tls_connection:
                        handle_connection(tls_connection, peer_address, args)

    return 0


if __name__ == "__main__":
    sys.exit(main())
