#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2026-2026 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

set -e
set -o pipefail
set -u

# We check that `select jobid=` always selects the right
# jobids.

#shellcheck source=../../environment.in
. ./environment

#shellcheck source=../../scripts/functions
. "${BAREOS_SCRIPTS_DIR}"/functions

# select a full
check_job_ids "3" <<EOF
restore jobid=3 select
EOF

# select a differential
check_job_ids "4,7" <<EOF
restore jobid=7 select
EOF
check_job_ids "4,5" <<EOF
restore jobid=5 select
EOF

# select an incremental
check_job_ids "4,5,6" <<EOF
restore jobid=6 select
EOF

# select inbetween incremental
# make sure that useless diff & inc are skipped (5 & 6)
check_job_ids "4,7,8,10,11" <<EOF
restore jobid=11 select
EOF

# select a job from a different client
check_job_ids "3,12,13" <<EOF
restore jobid=13 select
EOF
