/* autogenerated file by ./create_queryfiles.sh on 2017-01-03 09:38:08 */
#define SQL(...) #__VA_ARGS__
const char *B_DB_MYSQL::queries [] = {
SQL(
SELECT JobId, ObjectLength, ObjectFullLength, ObjectIndex, ObjectType, ObjectCompression, FileIndex, ObjectName, RestoreObject, PluginName
  FROM RestoreObject
 WHERE JobId IN (%s)
   AND ObjectType = %d
 ORDER BY ObjectIndex ASC
),
SQL(
UPDATE Job
   SET JobStatus = 'f', StartTime = SchedTime, EndTime = SchedTime
 WHERE JobStatus = 'C'
),
SQL(
UPDATE Job
   SET JobStatus = 'f', EndTime = StartTime
 WHERE JobStatus = 'R'
),
SQL(
INSERT INTO JobHisto (
	       JobId, Job, Name, Type, Level, ClientId, JobStatus, SchedTime, StartTime, EndTime, RealEndTime, JobTDate,
	       VolSessionId, VolSessionTime, JobFiles, JobBytes, ReadBytes, JobErrors, JobMissingFiles, PoolId, FileSetId,
	       PriorJobId, PurgedFiles,
	       HasBase, Reviewed, Comment
       )
SELECT JobId, Job, Name, Type, Level, ClientId, JobStatus, SchedTime, StartTime, EndTime, RealEndTime, JobTDate, VolSessionId,
       VolSessionTime, JobFiles, JobBytes, ReadBytes, JobErrors, JobMissingFiles, PoolId, FileSetId, PriorJobId, PurgedFiles,
       HasBase,
       Reviewed, Comment
  FROM Job
 WHERE JobStatus IN ('T','W','f','A','E')
   AND NOT EXISTS (
		SELECT JobHisto.JobId
		  FROM JobHisto
		 WHERE JobHisto.Jobid = Job.JobId
       )
   AND JobTDate       < %s
),
SQL(
SELECT *
  FROM Pool
 WHERE PoolId = %s
),
SQL(
SELECT DISTINCT Job.JobId,Job.Name, Client.Name as Client,
Job.StartTime,Job.Type,Job.Level,Job.JobFiles,Job.JobBytes,Job.JobStatus
FROM Job
LEFT JOIN Client ON Client.ClientId=Job.ClientId
LEFT JOIN JobMedia ON JobMedia.JobId=Job.JobId
LEFT JOIN Media ON JobMedia.MediaId=Media.MediaId
LEFT JOIN FileSet ON FileSet.FileSetId=Job.FileSetId
WHERE Job.JobId > 0
%s
ORDER BY StartTime%s;
),
SQL(
SELECT DISTINCT Job.JobId, Job.Job, Job.Name, Job.PurgedFiles, Job.Type, Job.Level,
Job.ClientId, Client.Name as Client, Job.JobStatus, Job.SchedTime, Job.StartTime,
Job.EndTime, Job.RealEndTime, Job.JobTDate, Job.VolSessionId, Job.VolSessionTime,
Job.JobFiles, Job.JobBytes, Job.JobErrors, Job.JobMissingFiles, Job.PoolId,
Pool.Name as PoolName, Job.PriorJobId, Job.FileSetId, FileSet.FileSet
FROM Job
LEFT JOIN Client ON Client.ClientId=Job.ClientId
LEFT JOIN Pool ON Pool.PoolId=Job.PoolId
LEFT JOIN JobMedia ON JobMedia.JobId=Job.JobId
LEFT JOIN Media ON JobMedia.MediaId=Media.MediaId
LEFT JOIN FileSet ON FileSet.FileSetId=Job.FileSetId
WHERE Job.JobId > 0
%s
ORDER BY StartTime%s;
),
SQL(
SELECT DISTINCT COUNT(DISTINCT Job.JobId) as count
FROM Job
LEFT JOIN Client ON Client.ClientId=Job.ClientId
LEFT JOIN JobMedia ON JobMedia.JobId=Job.JobId
LEFT JOIN Media ON JobMedia.MediaId=Media.MediaId
LEFT JOIN FileSet ON FileSet.FileSetId=Job.FileSetId
WHERE Job.JobId > 0
%s
%s;
),
SQL(
SELECT DISTINCT Job.JobId,Job.Name, Client.Name as Client,
Job.StartTime,Job.Type,Job.Level,Job.JobFiles,Job.JobBytes,Job.JobStatus
FROM Job
LEFT JOIN Client ON Client.ClientId=Job.ClientId
LEFT JOIN JobMedia ON JobMedia.JobId=Job.JobId
LEFT JOIN Media ON JobMedia.MediaId=Media.MediaId
LEFT JOIN FileSet ON FileSet.FileSetId=Job.FileSetId
INNER JOIN (
   SELECT MAX(Job.JobId) as MaxJobId
   FROM Job
   LEFT JOIN Client ON Client.ClientId=Job.ClientId
   LEFT JOIN Pool ON Pool.PoolId=Job.PoolId
   LEFT JOIN JobMedia ON JobMedia.JobId=Job.JobId
   LEFT JOIN Media ON JobMedia.MediaId=Media.MediaId
   LEFT JOIN FileSet ON FileSet.FileSetId=Job.FileSetId
   WHERE Job.JobId > 0
   %s
   GROUP BY Job.Name
) LastJob
ON Job.JobId = LastJob.MaxJobId
ORDER BY StartTime%s;
),
SQL(
SELECT DISTINCT Job.JobId, Job.Job, Job.Name, Job.PurgedFiles, Job.Type, Job.Level,
Job.ClientId, Client.Name as Client, Job.JobStatus, Job.SchedTime, Job.StartTime,
Job.EndTime, Job.RealEndTime, Job.JobTDate, Job.VolSessionId, Job.VolSessionTime,
Job.JobFiles, Job.JobBytes, Job.JobErrors, Job.JobMissingFiles, Job.PoolId,
Pool.Name as PoolName, Job.PriorJobId, Job.FileSetId, FileSet.FileSet
FROM Job
LEFT JOIN Client ON Client.ClientId=Job.ClientId
LEFT JOIN Pool ON Pool.PoolId=Job.PoolId
LEFT JOIN JobMedia ON JobMedia.JobId=Job.JobId
LEFT JOIN Media ON JobMedia.MediaId=Media.MediaId
LEFT JOIN FileSet ON FileSet.FileSetId=Job.FileSetId
INNER JOIN (
   SELECT MAX(Job.JobId) as MaxJobId
   FROM Job
   LEFT JOIN Client ON Client.ClientId=Job.ClientId
   LEFT JOIN Pool ON Pool.PoolId=Job.PoolId
   LEFT JOIN JobMedia ON JobMedia.JobId=Job.JobId
   LEFT JOIN Media ON JobMedia.MediaId=Media.MediaId
   LEFT JOIN FileSet ON FileSet.FileSetId=Job.FileSetId
   WHERE Job.JobId > 0
   %s
   GROUP BY Job.Name
) LastJob
ON Job.JobId = LastJob.MaxJobId
ORDER BY StartTime%s;
),
SQL(
SELECT DISTINCT JobMedia.JobId
  FROM JobMedia, Job
 WHERE MediaId      = %s
   AND Job.JobId    = JobMedia.JobId
   AND Job.JobTDate < %s
),
SQL(
DROP TABLE IF EXISTS DelCandidates
),
SQL(
CREATE TEMPORARY TABLE
       DelCandidates (
          JobId INTEGER UNSIGNED NOT NULL, PurgedFiles TINYINT, FileSetId INTEGER UNSIGNED, JobFiles INTEGER UNSIGNED, JobStatus
          BINARY(1)
       )
),
SQL(
CREATE INDEX DelInx1 ON DelCandidates (JobId)
),
SQL(
SELECT JobFiles
  FROM Job
 WHERE JobId = %s
),
SQL(
SELECT JobId, Client.Name as Client, StartTime, Level as JobLevel, JobFiles, JobBytes
  FROM Client, Job
 WHERE Client.ClientId = Job.ClientId
   AND JobStatus IN ('T','W')
   AND Type            = 'B'
 ORDER BY StartTime DESC LIMIT 20
),
SQL(
SELECT DISTINCT JobId, Level, JobFiles, JobBytes, StartTime, VolumeName
  FROM Job
  JOIN JobMedia
 USING (JobId)
  JOIN Media
 USING (MediaId)
 WHERE JobId IN (%s)
 ORDER BY StartTime ASC
),
SQL(
DROP TABLE temp
),
SQL(
DROP TABLE temp1
),
SQL(
INSERT INTO temp1
SELECT Job.JobId, JobTdate
  FROM Job, JobMedia, Media, FileSet
 WHERE Job.ClientId     = %s
   AND Job.StartTime    < '%s'
   AND Level            = 'F'
   AND JobStatus IN ('T','W')
   AND Type             = 'B'
   AND JobMedia.JobId   = Job.JobId
   AND Media.Enabled    = 1
   AND JobMedia.MediaId = Media.MediaId
   AND Job.FileSetId    = FileSet.FileSetId
   AND FileSet.FileSet  = '%s' %s
 ORDER BY Job.JobTDate DESC LIMIT 1
),
SQL(
INSERT INTO temp1
SELECT Job.JobId, JobTdate
  FROM Job, FileSet
 WHERE Job.ClientId    = %s
   AND Job.StartTime   < '%s'
   AND Level           = 'F'
   AND JobStatus IN ('T','W')
   AND Type            = 'B'
   AND Job.FileSetId   = FileSet.FileSetId
   AND FileSet.FileSet = '%s'
 ORDER BY Job.JobTDate DESC LIMIT 1
),
SQL(
INSERT INTO temp
SELECT Job.JobId, Job.JobTDate, Job.ClientId, Job.Level, Job.JobFiles, Job.JobBytes, StartTime, VolumeName, JobMedia.StartFile,
       VolSessionId, VolSessionTime
  FROM temp1, Job, JobMedia, Media
 WHERE temp1.JobId      = Job.JobId
   AND Level            = 'F'
   AND JobStatus IN ('T','W')
   AND Type             = 'B'
   AND Media.Enabled    = 1
   AND JobMedia.JobId   = Job.JobId
   AND JobMedia.MediaId = Media.MediaId
),
SQL(
INSERT INTO temp
SELECT Job.JobId, Job.JobTDate, Job.ClientId, Job.Level, Job.JobFiles, Job.JobBytes, Job.StartTime, Media.VolumeName,
       JobMedia.StartFile, Job.VolSessionId, Job.VolSessionTime
  FROM Job, JobMedia, Media, FileSet
 WHERE Job.JobTDate     > %s
   AND Job.StartTime    < '%s'
   AND Job.ClientId     = %s
   AND JobMedia.JobId   = Job.JobId
   AND Media.Enabled    = 1
   AND JobMedia.MediaId = Media.MediaId
   AND Job.Level        = 'D'
   AND JobStatus IN ('T','W')
   AND Type             = 'B'
   AND Job.FileSetId    = FileSet.FileSetId
   AND FileSet.FileSet  = '%s' %s
 ORDER BY Job.JobTDate DESC LIMIT 1
),
SQL(
INSERT INTO temp
SELECT Job.JobId, Job.JobTDate, Job.ClientId, Job.Level, Job.JobFiles, Job.JobBytes, Job.StartTime, Media.VolumeName,
       JobMedia.StartFile, Job.VolSessionId, Job.VolSessionTime
  FROM Job, JobMedia, Media, FileSet
 WHERE Job.JobTDate     > %s
   AND Job.StartTime    < '%s'
   AND Job.ClientId     = %s
   AND Media.Enabled    = 1
   AND JobMedia.JobId   = Job.JobId
   AND JobMedia.MediaId = Media.MediaId
   AND Job.Level        = 'I'
   AND JobStatus IN ('T','W')
   AND Type             = 'B'
   AND Job.FileSetId    = FileSet.FileSetId
   AND FileSet.FileSet  = '%s' %s
),
SQL(
SELECT DISTINCT Job.JobId, Job.Level, Job.JobFiles, Job.JobBytes, Job.StartTime, Media.VolumeName
  FROM Job, JobMedia, Media
 WHERE Job.JobId IN (%s)
   AND JobMedia.JobId   = Job.JobId
   AND Media.Enabled    = 1
   AND JobMedia.MediaId = Media.MediaId
 ORDER BY StartTime ASC
),
SQL(
SELECT DISTINCT JobId, StartTime
  FROM temp
 ORDER BY StartTime ASC
),
SQL(
SELECT *
  FROM temp1
),
SQL(
SELECT *
  FROM temp
),
SQL(
SELECT DISTINCT FileSet.FileSet
  FROM Job, Client, FileSet
 WHERE Job.FileSetId   = FileSet.FileSetId
   AND Job.ClientId    = %s
   AND Client.ClientId = %s
 ORDER BY FileSet.FileSet
),
SQL(
SELECT MAX(FileSet.FileSetId)
  FROM FileSet
  JOIN Job
 USING (FileSetId)
 WHERE Job.ClientId = %s
 GROUP BY FileSet
),
SQL(
SELECT Job.JobId, File.FileIndex
  FROM Job, File, Path, Filename, Client
 WHERE Job.JobId           =  File.JobId
   AND Job.StartTime       <= '%s'
   AND Path.Path           =  '%s'
   AND Filename.Name       =  '%s'
   AND Client.Name         =  '%s'
   AND Job.ClientId        =  Client.ClientId
   AND Path.PathId         =  File.PathId
   AND Filename.FilenameId =  File.FilenameId
   AND JobStatus IN ('T','W')
   AND Type                =  'B'
 ORDER BY Job.StartTime DESC LIMIT 1
),
SQL(
SELECT Job.JobId, File.FileIndex
  FROM Job, File, Path, Filename, Client
 WHERE Job.JobId IN (%s)
   AND Job.JobId           =  File.JobId
   AND Job.StartTime       <= '%s'
   AND Path.Path           =  '%s'
   AND Filename.Name       =  '%s'
   AND Client.Name         =  '%s'
   AND Job.ClientId        =  Client.ClientId
   AND Path.PathId         =  File.PathId
   AND Filename.FilenameId =  File.FilenameId
 ORDER BY Job.StartTime DESC LIMIT 1
),
SQL(
SELECT JobId, FileIndex
  FROM %s
 ORDER BY JobId, FileIndex ASC
),
SQL(
SELECT FileId, Job.JobId AS JobId, FileIndex, File.PathId AS PathId, File.FilenameId AS FilenameId, LStat, MD5, DeltaSeq,
       Job.JobTDate AS JobTDate
  FROM Job, File, (
      SELECT MAX(JobTDate) AS JobTDate, PathId, FilenameId
        FROM (
            SELECT JobTDate, PathId, FilenameId
              FROM File
              JOIN Job
             USING (JobId)
             WHERE File.JobId IN (%s)
             UNION ALL
            SELECT JobTDate, PathId, FilenameId
              FROM BaseFiles
              JOIN File
             USING (FileId)
              JOIN Job
                ON (BaseJobId    = Job.JobId)
             WHERE BaseFiles.JobId IN (%s)
             ) AS tmp
       GROUP BY PathId, FilenameId
       ) AS T1
 WHERE (
          Job.JobId IN (
         SELECT DISTINCT BaseJobId
           FROM BaseFiles
          WHERE JobId IN (%s)
          )
       OR Job.JobId IN (%s)
       )
   AND T1.JobTDate   = Job.JobTDate
   AND Job.JobId     = File.JobId
   AND T1.PathId     = File.PathId
   AND T1.FilenameId = File.FilenameId
),
SQL(
SELECT FileId, Job.JobId AS JobId, FileIndex, File.PathId AS PathId, File.FilenameId AS FilenameId, LStat, MD5, File.DeltaSeq AS
       DeltaSeq, Job.JobTDate AS JobTDate
  FROM Job, File, (
      SELECT MAX(JobTDate) AS JobTDate, PathId, FilenameId, DeltaSeq
        FROM (
            SELECT JobTDate, PathId, FilenameId, DeltaSeq
              FROM File
              JOIN Job
             USING (JobId)
             WHERE File.JobId IN (%s)
             UNION ALL
            SELECT JobTDate, PathId, FilenameId, DeltaSeq
              FROM BaseFiles
              JOIN File
             USING (FileId)
              JOIN Job
                ON (BaseJobId    = Job.JobId)
             WHERE BaseFiles.JobId IN (%s)
             ) AS tmp
       GROUP BY PathId, FilenameId, DeltaSeq
       ) AS T1
 WHERE (
          Job.JobId IN (
         SELECT DISTINCT BaseJobId
           FROM BaseFiles
          WHERE JobId IN (%s)
          )
       OR Job.JobId IN (%s)
       )
   AND T1.JobTDate   = Job.JobTDate
   AND Job.JobId     = File.JobId
   AND T1.PathId     = File.PathId
   AND T1.FilenameId = File.FilenameId
),
SQL(
SELECT j1.JobId AS JobId, f1.FileId AS FileId, f1.FileIndex AS FileIndex, f1.PathId AS PathId, f1.FilenameId AS FilenameId,
       f1.LStat AS LStat, f1.MD5 AS MD5, j1.JobTDate
  FROM (
      SELECT max(JobTDate) AS JobTDate, PathId, FilenameId
        FROM File
        JOIN Job
       USING (JobId)
       WHERE File.JobId IN (%s)
       GROUP BY PathId, FilenameId
       ) AS t1, Job AS j1, File AS f1
 WHERE t1.JobTDate   = j1.JobTDate
   AND j1.JobId IN (%s)
   AND t1.FilenameId = f1.FilenameId
   AND t1.PathId     = f1.PathId
   AND j1.JobId      = f1.JobId
),
SQL(
CREATE TABLE btemp3%s AS
SELECT JobId, StartTime, EndTime, JobTDate, PurgedFiles
  FROM Job
  JOIN FileSet
 USING (FileSetId)
 WHERE ClientId          = %s
   AND Level             = 'F'
   AND JobStatus IN ('T','W')
   AND Type              = 'B'
   AND StartTime         < '%s'
   AND FileSet.FileSetId = %s
 ORDER BY Job.JobTDate DESC LIMIT 1
),
SQL(
CREATE TEMPORARY TABLE basefile%lld ( Path BLOB NOT NULL, Name BLOB NOT NULL, INDEX (Path(255), Name(255)))
),
SQL(
CREATE TEMPORARY TABLE new_basefile%lld AS
SELECT Path.Path AS Path, Filename.Name AS Name, Temp.FileIndex AS FileIndex, Temp.JobId AS JobId, Temp.LStat AS LStat,
       Temp.FileId AS FileId, Temp.MD5 AS MD5
  FROM ( %s ) AS Temp
  JOIN Filename
 USING (FilenameId)
  JOIN Path
 USING (PathId)
 WHERE Temp.FileIndex > 0
),
SQL(
CREATE TEMPORARY TABLE cpy_tmp AS
SELECT MIN(JobId) AS JobId
  FROM Job
 WHERE Type = '%c'
   AND (
          PriorJobId IN (%s)
       OR PriorJobId IN (
         SELECT PriorJobId
           FROM Job
          WHERE JobId IN (%s)
            AND Type = 'B'
          )
       )
 GROUP BY PriorJobId
),
SQL(
SELECT Job.JobId as JobId, CONCAT(Path.Path, Filename.Name) as Name, StartTime, Type as JobType, JobStatus, JobFiles, JobBytes
  FROM Client, Job, File, Filename, Path
 WHERE Client.Name         = '%s'
   AND Client.ClientId     = Job.ClientId
   AND Job.JobId           = File.JobId
   AND File.FileIndex      > 0
   AND Path.PathId         = File.PathId
   AND Filename.FilenameId = File.FilenameId
   AND Filename.Name       = '%s'
 ORDER BY StartTime DESC LIMIT 20
),
SQL(
CREATE TEMPORARY TABLE
       temp (
	  JobId INTEGER UNSIGNED NOT NULL, JobTDate BIGINT UNSIGNED, ClientId INTEGER UNSIGNED, Level CHAR, JobFiles INTEGER
	  UNSIGNED, JobBytes BIGINT UNSIGNED, StartTime TEXT, VolumeName TEXT, StartFile INTEGER UNSIGNED, VolSessionId INTEGER
	  UNSIGNED, VolSessionTime INTEGER UNSIGNED
       )
),
SQL(
CREATE TEMPORARY TABLE temp1 ( JobId INTEGER UNSIGNED NOT NULL, JobTDate BIGINT UNSIGNED)
),
SQL(
SELECT Job.JobId, File.FileIndex
  FROM Job, File, Path, Filename, Client
 WHERE Job.JobId IN (%s)
   AND Job.JobId           = File.JobId
   AND Path.Path           = '%s'
   AND Client.Name         = '%s'
   AND Job.ClientId        = Client.ClientId
   AND Path.PathId         = File.Pathid
   AND Filename.FilenameId = File.FilenameId
 GROUP BY File.FileIndex
),
SQL(
ORDER BY LastWritten IS NULL,LastWritten DESC,MediaId
),
SQL(
SHOW VARIABLES LIKE 'max_connections'
),
SQL(
CREATE TABLE %s AS
SELECT File.JobId, File.FileIndex, File.FileId
  FROM Job, File, (
      SELECT MAX(JobTDate) AS JobTDate, PathId, FilenameId
        FROM btemp%s
       GROUP BY PathId, FilenameId
       ) AS T1
  JOIN Filename
 USING (FilenameId)
 WHERE T1.JobTDate    = Job.JobTDate
   AND Job.JobId      = File.JobId
   AND T1.PathId      = File.PathId
   AND T1.FilenameId  = File.FilenameId
   AND File.FileIndex > 0
   AND Job.JobId IN (
      SELECT DISTINCT JobId
        FROM btemp%s
       )
),
SQL(
SELECT 'F', T1.PathId, T1.FilenameId, Filename.Name, File.JobId, File.LStat, File.FileId
  FROM Job, File, (
      SELECT MAX(JobTDate) AS JobTDate, PathId, FilenameId
	FROM (
	    SELECT JobTDate, PathId, FilenameId
	      FROM File
	      JOIN Job
	     USING (JobId)
	     WHERE File.JobId IN (%s)
	       AND PathId         =  %s
	     UNION ALL
	    SELECT JobTDate, PathId, FilenameId
	      FROM BaseFiles
	      JOIN File
	     USING (FileId)
	      JOIN Job
		ON (BaseJobId     =  Job.JobId)
	     WHERE BaseFiles.JobId IN (%s)
	       AND PathId         =  %s
	     ) AS tmp
       GROUP BY PathId, FilenameId LIMIT %lld OFFSET %lld
       ) AS T1
  JOIN Filename
 USING (FilenameId)
 WHERE T1.JobTDate    =  Job.JobTDate
   AND Job.JobId      =  File.JobId
   AND T1.PathId      =  File.PathId
   AND T1.FilenameId  =  File.FilenameId
   AND Filename.Name  != ''
   AND File.FileIndex >  0 %s
   AND (
	  Job.JobId IN (
	 SELECT DISTINCT BaseJobId
	   FROM BaseFiles
	  WHERE JobId IN (%s)
	  )
       OR Job.JobId IN (%s)
       )
),
SQL(
LOCK TABLES Path write, batch write, Path as p write
),
SQL(
LOCK TABLES Filename write, batch write, Filename as f write
),
SQL(
UNLOCK TABLES
),
SQL(
INSERT INTO Path (Path)
SELECT a.Path
  FROM (
      SELECT DISTINCT Path
	FROM batch
       ) AS a
 WHERE NOT EXISTS (
      SELECT Path
	FROM Path AS p
       WHERE p.Path = a.Path
       )
),
SQL(
INSERT INTO Filename (Name)
SELECT a.Name
  FROM (
      SELECT DISTINCT Name
	FROM batch
       ) AS a
 WHERE NOT EXISTS (
      SELECT Name
	FROM Filename AS f
       WHERE f.Name = a.Name
       )
),
SQL(
 AND Path2.Path REGEXP '%s'
),
SQL(
 AND Filename.Name REGEXP '%s'
),
SQL(
INSERT INTO Counters (Counter, Counters.MinValue, Counters.MaxValue, CurrentValue, WrapCounter)
VALUES ('%s','%d','%d','%d','%s')
),
SQL(
SELECT Counters.MinValue, Counters.MaxValue, CurrentValue, WrapCounter
  FROM Counters
 WHERE Counter = '%s'
),
SQL(
UPDATE Counters
   SET Counters.MinValue = %d, Counters.MaxValue = %d, CurrentValue = %d, WrapCounter = '%s'
 WHERE Counter           = '%s'
),
SQL(
SELECT SUM(JobBytes)
  FROM Job
 WHERE ClientId  =  %s
   AND JobId     != %s
   AND SchedTime >  '%s'
),
SQL(
SELECT SUM(JobBytes)
  FROM Job
 WHERE ClientId  =  %s
   AND Job.JobId != %s
   AND SchedTime >  '%s'
   AND JobStatus NOT IN ('E','f','A')
),
SQL(
SELECT DISTINCT JobId, StartTime
  FROM Job
 WHERE Type = 'C'
   AND (PriorJobId IN (%s))
 ORDER BY StartTime ASC
),
SQL(
SELECT DISTINCT JobStatus, JobStatusLong, Severity,
       CASE
       WHEN JobStatus in ('T') THEN '0'
       WHEN JobStatus in ('W') THEN '1'
       WHEN JobStatus in ('e', 'f', 'A', 'E') THEN '2'
       END as ExitLevel,
       CASE
       WHEN JobStatus in ('T') THEN 'Ok'
       WHEN JobStatus in ('W') THEN 'Warning'
       WHEN JobStatus in ('e', 'f', 'A', 'E') THEN 'Error'
       END as ExitStatus
  FROM Status %s
 ORDER BY JobStatus
),
NULL };

const char *B_DB_MYSQL::query_names [] = {
"get_restore_objects",
"cleanup_created_job",
"cleanup_running_job",
"fill_jobhisto",
"list_pool",
"list_jobs",
"list_jobs_long",
"list_jobs_count",
"list_jobs_last",
"list_jobs_long_last",
"sel_JobMedia",
"drop_deltabs",
"create_deltabs",
"create_delindex",
"uar_count_files",
"uar_list_jobs",
"uar_print_jobs",
"drop_deltabs",
"uar_del_temp1",
"uar_last_full",
"uar_last_full_no_pool",
"uar_full",
"uar_dif",
"uar_inc",
"uar_list_jobs_by_idlist",
"uar_sel_jobid_temp",
"uar_sel_all_temp1",
"uar_sel_all_temp",
"uar_sel_fileset",
"uar_sel_filesetid",
"uar_jobid_fileindex",
"uar_jobids_fileindex",
"uar_jobid_fileindex_from_table",
"select_recent_version_with_basejob",
"select_recent_version_with_basejob_and_delta",
"select_recent_version",
"create_temp_accurate_jobids",
"create_temp_basefile",
"create_temp_new_basefile",
"uap_upgrade_copies_oldest_job",
"uar_file",
"uar_create_temp",
"uar_create_temp1",
"uar_jobid_fileindex_from_dir",
"sql_media_order_most_recently_written",
"sql_get_max_connections",
"sql_bvfs_select",
"sql_bvfs_list_files",
"batch_lock_path_query",
"batch_lock_filename_query",
"batch_unlock_tables_query",
"batch_fill_path_query",
"batch_fill_filename_query",
"match_query",
"match_query2",
"insert_counter_values",
"select_counter_values",
"update_counter_values",
"get_quota_jobbytes",
"get_quota_jobbytes_nofailed",
"uar_sel_jobid_copies",
"get_jobstatus_details",
NULL };
