#!/bin/bash
#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2026-2026 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.
#
# webui-vue system test – tape autochanger backup
#
# Runs a Full backup to each detected tape autochanger.
# Requires an autochanger to have been configured at cmake time (via
# -Dautodetect-changer=yes or -Dchanger-device=...).  When no changer
# is configured this testrunner is disabled by CMake and never runs.

set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../../environment.in
. ./environment

#shellcheck source=test-config.in
. ./test-config

#shellcheck source=../../scripts/functions
. "${BAREOS_SCRIPTS_DIR}"/functions

start_test

for changer_index in {0..9}; do
  changer_var="CHANGER_DEVICE${changer_index}"
  changer_device="${!changer_var:-}"
  [[ -z "${changer_device}" ]] && break

  print_debug "Running tape backup for autochanger ${changer_index}: ${changer_device}"

  log_out="${tmp}/log-tape-${changer_index}-full.out"

  cat <<END_OF_DATA >"${tmp}/bconcmds-tape-${changer_index}"
@$out ${NULL_DEV}
messages
@$out ${log_out}
label barcodes storage=Tape-${changer_index} pool=TapeFull-${changer_index} slots=1-4 drive=0 yes
run job=backup-tape-${changer_index} level=Full yes
wait
messages
quit
END_OF_DATA

  run_bconsole "${tmp}/bconcmds-tape-${changer_index}"
  check_log "${log_out}"
done

end_test
