#!/bin/bash
#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2026-2026 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.
#
# webui-vue system test – load subscription test data
#
# Inserts synthetic clients, filesets, and jobs (IDs >= 10000) into the
# catalog so the subscription report page has realistic multi-client and
# multi-plugin data.  Mirrors the dataset from
# systemtests/tests/bareos-basic/testrunner-status-subscriptions.
#
set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../../environment.in
. ./environment

#shellcheck source=../../scripts/functions
. "${BAREOS_SCRIPTS_DIR}"/functions

start_test

cat >"${tmp}/bconcmds" <<'END_OF_BCONCMDS'
sqlquery
DELETE FROM Job WHERE JobId >= 10000;
DELETE FROM Client WHERE ClientId >= 10000;
DELETE FROM Fileset WHERE FileSetId >= 10000;
INSERT INTO Client (ClientId, Name, UName) VALUES
(10000, 'file-only', 'synthetic test client'),
(10001, 'two-barri-jobs', 'synthetic test client'),
(10002, 'file-and-plugins', 'synthetic test client'),
(10003, 'native-plugins', 'synthetic test client'),
(10004, 'python-plugins', 'synthetic test client'),
(10005, 'special-syntax', 'synthetic test client');
INSERT INTO Fileset (FileSetId, Fileset, FileSetText, Md5, CreateTime) VALUES
(10000, 'file1', E'{\n{\nFile = "/a"\n}\n}', 'x', now()),
(10001, 'file2', E'{\n{\nFile = "/b"\n}\n}', 'x', now()),
(10002, 'file3', E'{\n{\nFile = "/c"\n}\n}', 'x', now()),
(10003, 'barri1', E'{\n{\nPlugin = "barri"\n}\n}', 'x', now()),
(10004, 'barri2', E'{\n{\nPlugin = "barri:"\n}\n}', 'x', now()),
(10005, 'bpipe1', E'{\n{\nPlugin = "bpipe:reader=\"/bin/prog\""\n}\n}', 'x', now()),
(10006, 'hyper-v1', E'{\n{\nPlugin = "hyper-v:"\n}\n}', 'x', now()),
(10007, 'hyper-v2', E'{\n{\nPlugin = "hyper-v:"\n}\n}', 'x', now()),
(10008, 'hyper-v3', E'{\n{\nPlugin = "hyper-v"\n}\n}', 'x', now()),
(10009, 'mssql1', E'{\n{\nPlugin = "mssqlvdi:"\n}\n}', 'x', now()),
(10010, 'mssql2', E'{\n{\nPlugin = "Mssqlvdi:"\n}\n}', 'x', now()),
(10011, 'mssql3', E'{\n{\nPlugin = "MSSQLVDI:"\n}\n}', 'x', now()),
(10012, 'mssql4', E'{\n{\nPlugin = "mssqlvdi"\n}\n}', 'x', now()),
(10013, 'ldap', E'{\n{\nPlugin = "python:module_name=bareos-fd-ldap"\n}\n}', 'x', now()),
(10014, 'libcloud', E'{\n{\nPlugin = "python:module_name=bareos-fd-libcloud"\n}\n}', 'x', now()),
(10015, 'mariadb', E'{\n{\nPlugin = "python3:module_name=bareos-fd-mariabackup"\n}\n}', 'x', now()),
(10016, 'ovirt', E'{\n{\nPlugin = "python:module_name=bareos-fd-ovirt"\n}\n}', 'x', now()),
(10017, 'percona', E'{\n{\nPlugin = "python:module_name=bareos-fd-percona"\n}\n}', 'x', now()),
(10018, 'postgres', E'{\n{\nPlugin = "python:module_name=bareos-fd-postgres"\n}\n}', 'x', now()),
(10019, 'proxmox', E'{\n{\nPlugin = "python:module_name=bareos-fd-proxmox"\n}\n}', 'x', now()),
(10020, 'qumulo', E'{\n{\nPlugin = "python:module_name=bareos-fd-qumulo"\n}\n}', 'x', now()),
(10021, 'vmware', E'{\n{\nPlugin = "python:module_name=bareos-fd-vmware"\n}\n}', 'x', now()),
(10022, 'nomod-py', E'{\n{\nPlugin = "python3:no_module_name"\n}\n}', 'x', now()),
(10023, 'custom', E'{\n{\nPlugin = "custom-plugin"\n}\n}', 'x', now()),
(10024, 'grpc1', E'{\n{\nPlugin = "grpc:bareos-grpc-fd-plugin-bridge:python3:arg1:arg2:module_name=bareos-fd-bridged"\n}\n}', 'x', now()),
(10025, 'grpc2', E'{\n{\nPlugin = "grpc:my-gprc-plugin:arg1=val1:arg2"\n}\n}', 'x', now()),
(10026, 'noprefix', E'{\n{\nPlugin = "python:arg:module_name=noprefix"\n}\n}', 'x', now());
INSERT INTO Job (JobId, Job, Name, Type, Level, ClientId, JobStatus,
  JobBytes, ReadBytes, FilesetId, SchedTime, StartTime, EndTime) VALUES
(10000,'file1-1','file1','B','F',10000,'T',1000000000,1000,10000,now(),now(),now()),
(10001,'file2-1','file2','B','F',10000,'T',1000,1000000000,10001,now(),now(),now()),
(10002,'file3-1','file3','B','F',10000,'T',1000000000,1000,10002,now(),now(),now()),
(10003,'file1-2','file1','B','F',10000,'T',1000,1000000000,10000,now(),now(),now()),
(10004,'barri1-1','barri1','B','F',10001,'T',1000,1000000000,10003,now(),now(),now()),
(10005,'barri2-1','barri2','B','F',10001,'T',1000,1000000000,10004,now(),now(),now()),
(10006,'barri1-2','barri1','B','F',10001,'T',1000,1000000000,10003,now(),now(),now()),
(10007,'barri2-2','barri2','B','F',10001,'T',1000,1000000000,10004,now(),now(),now()),
(10008,'file1-3','file1','B','F',10002,'T',1000,1000000000,10000,now(),now(),now()),
(10009,'file2-2','file2','B','F',10002,'T',1000,1000000000,10001,now(),now(),now()),
(10010,'bpipe1-1','bpipe1','B','F',10002,'T',1000,1000000000,10005,now(),now(),now()),
(10011,'barri1-3','barri1','B','F',10002,'T',1000,1000000000,10003,now(),now(),now()),
(10012,'bpipe1-2','bpipe1','B','F',10003,'T',1000,1000000000,10005,now(),now(),now()),
(10013,'barri1-4','barri1','B','F',10003,'T',1000,1000000000,10003,now(),now(),now()),
(10014,'barri2-3','barri2','B','F',10003,'T',1000,10000000000,10004,now(),now(),now()),
(10015,'hyper-v1','hyper-v1','B','F',10003,'T',1000,1000000000,10006,now(),now(),now()),
(10016,'hyper-v2','hyper-v2','B','F',10003,'T',1000,10000000000,10007,now(),now(),now()),
(10017,'hyper-v3','hyper-v3','B','F',10003,'T',1000,100000000000,10008,now(),now(),now()),
(10018,'mssql1','mssql1','B','F',10003,'T',1000,1000000000,10009,now(),now(),now()),
(10019,'mssql2','mssql2','B','F',10003,'T',1000,10000000000,10010,now(),now(),now()),
(10020,'mssql3','mssql3','B','F',10003,'T',1000,100000000000,10011,now(),now(),now()),
(10021,'mssql4','mssql4','B','F',10003,'T',1000,1000000000000,10012,now(),now(),now()),
(10022,'ldap','ldap','B','F',10004,'T',1000,90000000,10013,now(),now(),now()),
(10023,'libcloud','libcloud','B','F',10004,'T',1000,800000000,10014,now(),now(),now()),
(10024,'mariadb','mariadb','B','F',10004,'T',1000,7000000000,10015,now(),now(),now()),
(10025,'ovirt','ovirt','B','F',10004,'T',1000,60000000000,10016,now(),now(),now()),
(10026,'percona','percona','B','F',10004,'T',1000,500000000000,10017,now(),now(),now()),
(10027,'postgres','postgres','B','F',10004,'T',1000,4000000000000,10018,now(),now(),now()),
(10028,'proxmox','proxmox','B','F',10004,'T',1000,30000000000000,10019,now(),now(),now()),
(10029,'qumulo','qumulo','B','F',10004,'T',1000,200000000000000,10020,now(),now(),now()),
(10030,'vmware','vmware','B','F',10004,'T',1000,1000000000000000,10021,now(),now(),now()),
(10031,'nomod-py','nomod-py','B','F',10005,'T',1000,1000000000,10022,now(),now(),now()),
(10032,'custom','custom','B','F',10005,'T',1000,1000000000,10023,now(),now(),now()),
(10033,'grpc1','grpc1','B','F',10005,'T',1000,1000000000,10024,now(),now(),now()),
(10034,'grpc2','grpc2','B','F',10005,'T',1000,1000000000,10025,now(),now(),now()),
(10035,'noprefix','noprefix','B','F',10005,'T',1000,1000000000,10026,now(),now(),now());

END_OF_BCONCMDS

run_bconsole

end_test
