#!/bin/sh
#
# Run a simple backup then create some
#   new files, do an Incremental and restore those two files.
#
# This script uses the virtual disk autochanger and two drives
#
TestName="2drive-2disk"
JobName="2drive2disk"

# Directory to backup.
# This directory will be created by setup_data().
BackupDirectory="${tmp}/data"

. scripts/functions

scripts/cleanup

# Use a tgz to setup data to be backuped.
# Data will be placed at "${tmp}/data/".
setup_data data/small.tgz

scripts/copy-2disk-drive-confs
scripts/prepare-disk-changer

CLIENT=2drive2disk

change_jobname localhost-fd $JobName
start_test

# the default fileset FS_TESTJOB backups all file and directories defined in "${tmp}/file-list".
echo "${BackupDirectory}" >${tmp}/file-list

# Turn off Prefer Mounted Volumes so we use 2 drives
outf="${cwd}/tmp/sed_tmp"
echo "s%# Prefer Mounted Volumes%  Prefer Mounted Volumes%g" >${outf}
cp ${cwd}/bin/bareos-dir.conf ${cwd}/tmp/1
# Comment the next line out to write everything to one drive
#  otherwise, it writes the two jobs to different drives
sed -f ${outf} ${cwd}/tmp/1 >${cwd}/bin/bareos-dir.conf

# Write out bconsole commands
cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
setdebug level=3 dir
setdebug level=3 storage=tape
setdebug level=3 client=$CLIENT
label storage=tape volume=TestVolume001 slot=1 Pool=Default drive=1
# label storage=tape volume=TestVolume002 slot=2 Pool=Default drive=1
status storage=tape
setdebug level=120 storage=tape
run job=NightlySave level=Full yes
@sleep 1
run job=NightlySave level=Full yes
@sleep 1
run job=NightlySave level=Full yes
@sleep 1
run job=NightlySave level=Full yes
@sleep 1
run job=NightlySave level=Full yes
@sleep 3
status storage=tape
wait
list volumes
list jobs
status storage=tape
messages
quit
END_OF_DATA

run_bareos

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
@# Force Incremental on the second Volume
# update volume=TestVolume001 VolStatus=Used
status storage=tape
@#setdebug level=120 storage=tape
run level=Incremental job=NightlySave yes
wait
list volumes
status storage=tape
messages
@#
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bareos-restores select all storage=tape done
yes
wait
messages
@output
quit
END_OF_DATA

run_bconsole
check_for_zombie_jobs storage=tape
stop_bareos

check_two_logs
check_restore_diff

end_test
