#!/bin/sh
#
# Attempt to backup from a fifo and restore to a fifo
#
TestName="fifo-test"
JobName=FIFOTest
. scripts/functions

scripts/cleanup
scripts/copy-test-confs
echo "${cwd}/tmp/bfifo" >${cwd}/tmp/file-list

rm -f ${cwd}/tmp/bfifo
mkfifo ${cwd}/tmp/bfifo
# send a file into the fifo
file=encrypt-bug.jpg
cat ${file} >${cwd}/tmp/bfifo&

start_test

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
label storage=File1 volume=TestVolume001
run job=$JobName storage=File1 yes
wait
messages
quit
END_OF_DATA


run_bareos

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@#
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
@#setdebug level=50 client=$CLIENT
restore where=/  select all storage=File1 done
yes
wait
messages
quit
END_OF_DATA

cat <${cwd}/tmp/bfifo >${cwd}/tmp/${file}&

run_bconsole

check_for_zombie_jobs storage=File1
stop_bareos

check_two_logs
diff ${file} ${cwd}/tmp/${file}
dstat=$?
end_test
