#!/bin/sh
#
# Run a simple backup of the Bareos build directory
#   to a tape where we set the minimum and maximum block
#   sizes.
#
TestName="fixed-block-size-tape"
JobName=fixedblocksize
. scripts/functions

require_tape_drive

copy_tape_confs

echo "${cwd}/build" >${cwd}/tmp/file-list

cp ${cwd}/bin/bareos-sd.conf ${cwd}/tmp/1
echo "s%# Maximum Block Size%  Maximum Block Size%" >${cwd}/tmp/2
echo "s%# Minimum Block Size%  Minimum Block Size%" >>${cwd}/tmp/2
sed -f ${cwd}/tmp/2 ${cwd}/tmp/1 >${cwd}/bin/bareos-sd.conf
if [ $? != 0 ] ; then
   echo " "
   echo " "
   echo "!!!! sed problem in Fixed Block Size test !!!!!"
   echo " "
   exit 1
fi
rm -f ${cwd}/tmp/1 ${cwd}/tmp/2

change_jobname NightlySave $JobName
start_test


cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
setdebug level=51 storage=tape
label storage=tape volume=TestVolume001 slot=0 pool=Default
run job=$JobName yes
wait
messages
@#
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bareos-restores select storage=tape
unmark *
mark *
done
yes
wait
messages
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=tape
stop_bareos

check_two_logs
check_restore_diff
end_test
