#!/bin/sh
#
# Test lockmanager
#
TestName="lockmgr-test"
JobName=backup
. scripts/functions

scripts/cleanup
scripts/copy-confs

grep '#define _USE_LOCKMGR 1' $src/src/config.h > /dev/null
if [ $? != 0 ]; then
    echo "lockmanager disabled"
    exit 0
fi

#
# Zap out any schedule in default conf file so that
#  it doesn't start during our test
#
outf="$tmp/sed_tmp"
echo "s%  Schedule =%# Schedule =%g" >${outf}
cp ${conf}/bareos-dir.conf $tmp/1
sed -f ${outf} $tmp/1 >${conf}/bareos-dir.conf

start_test

make -C $src/src/lib lockmgr_test > /dev/null
if [ -f $src/src/lib/.libs/lockmgr_test ]; then
    LD_LIBRARY_PATH=$src/src/lib/.libs $src/src/lib/.libs/lockmgr_test > $tmp/1 2> $tmp/2
else
    $src/src/lib/lockmgr_test > $tmp/1 2> $tmp/2
fi

estat=$?

if [ "$debug" = 1 ]; then
    cat $tmp/1
fi

cat <<END_OF_DATA >$tmp/bconcmds
@$out /dev/null
messages
@$out $tmp/log1.out
.die deadlock storage
.die deadlock dir
quit
END_OF_DATA

run_bareos
stop_bareos

nb=`ls $working/*.traceback $working/*.bactrace | wc -l`
if [ $nb != 4 ]; then
    print_debug "ERROR: Should find 4 traces, not $nb"
    estat=1
fi

notracedump=yes
export notracedump
end_test
