#!/bin/sh
#
# Run a simple backup of the Bareos build directory using the compressed option
#   then restore it.
#
TestName="lz4hc-test"
JobName=lz4hc
. scripts/functions

#
# See if library is linked against libfastlz
#
cnt=`ldd ${bin}/libbareos.so 2>/dev/null | grep -c libfastlz`
if test ${cnt} -lt 1; then
   echo "$TestName skipped: not linked for fastlz compression"
   exit 0
fi

scripts/cleanup
scripts/copy-test-confs
echo "${cwd}/build" >${cwd}/tmp/file-list

# set compatible mode for filedaemon so that lz4hc is allowed
cp ${scripts}/bareos-fd.conf ${scripts}/bareos-fd.conf.tmp
sed  -e 's#FileDaemon {.*#FileDaemon { compatible=no#' < ${scripts}/bareos-fd.conf.tmp > ${scripts}/bareos-fd.conf

start_test

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
status all
status all
messages
label storage=File volume=TestVolume001
run job=lz4hcTest storage=File yes
wait
messages
@#
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bareos-restores select storage=File
unmark *
mark *
done
yes
wait
messages
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=File
stop_bareos

check_two_logs
check_restore_diff
grep " Software Compression" ${cwd}/tmp/log1.out | grep "%" 2>&1 1>/dev/null
if [ $? != 0 ] ; then
   echo "  !!!!! No compression !!!!!"
   bstat=1
fi
end_test
