#!/bin/sh
#
# Run a simple backup of the Bareos build directory using the compressed option
#   then restore it.
#
TestName="lzo-test"
JobName=lzo
. scripts/functions

#
# See if library is linked against liblzo2
#
cnt=`ldd ${cwd}/bin/libbareos.so 2>/dev/null | grep -c liblzo2`
if test ${cnt} -lt 1; then
   echo "$TestName skipped: not linked for lzo2 compression"
   exit 0
fi

scripts/cleanup
scripts/copy-test-confs
echo "${cwd}/build" >${cwd}/tmp/file-list

start_test

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
status all
status all
messages
label storage=File volume=TestVolume001
run job=LZOTest storage=File yes
wait
messages
@#
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bareos-restores select storage=File
unmark *
mark *
done
yes
wait
messages
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=File
stop_bareos

check_two_logs
check_restore_diff
grep " Software Compression" ${cwd}/tmp/log1.out | grep "%" 2>&1 1>/dev/null
if [ $? != 0 ] ; then
   echo "  !!!!! No compression !!!!!"
   bstat=1
fi
end_test
