#!/bin/sh
#
# Run a simple backup of the Bareos build directory then create some
#   new files, do a Differental then a bunch of query commands
#   and finally restore the two files.
#


TestName="query-test"
JobName=query
. scripts/functions

scripts/cleanup
scripts/copy-test-confs
echo "${cwd}/tmp/build" >${cwd}/tmp/file-list
mkdir -p ${cwd}/tmp/build
cp -p ${cwd}/build/src/dird/*.c ${cwd}/tmp/build
cd ${cwd}/tmp
echo "${cwd}/tmp/build/ficheriro1.txt" >restore-list
echo "${cwd}/tmp/build/ficheriro2.txt" >>restore-list
cd ${cwd}

change_jobname CompressedTest $JobName
start_test

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
label storage=File volume=TestVolume001
label storage=File volume=TestVolume002
run job=$JobName yes
wait
messages
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=File
stop_bareos

echo "ficheriro1.txt" >${cwd}/tmp/build/ficheriro1.txt
echo "ficheriro2.txt" >${cwd}/tmp/build/ficheriro2.txt

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
@# Force differental on the second Volume
update volume=TestVolume001 VolStatus=Used
run level=differential job=$JobName yes
wait
messages
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=File
stop_bareos

echo "ficheriro2.txt" >${cwd}/tmp/build/ficheriro2.txt
cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
run level=incremental job=$JobName yes
wait
messages
@#
@# Now do the queries
@#
query
1
ficheriro1.txt
query
2
${cwd}/tmp/build/
ficheriro1.txt
localhost-fd
query
6
TestVolume001
query
7
1
query
8
localhost-fd
query
9
Default
query
10
query
11
query
12
1
@#
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bareos-restores storage=File file=<${cwd}/tmp/restore-list
yes
wait
messages
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=File
stop_bareos

#
# Delete .c files because we will only restored the txt files
#
rm -f ${cwd}/tmp/build/*.c

check_two_logs
check_restore_tmp_build_diff
end_test
