#!/bin/sh
#
# test the reload and test command
#
TestName="reload-test"
. scripts/functions

require_linux
scripts/cleanup
scripts/copy-confs

bstat=0
rstat=0
zstat=0

detect_error()
{
    $bin/bareos-dir -t $conf/bareos-dir.conf 2>&1 >> $tmp/testconf.log
    if [ $? = 0 ]; then
        estat=1
        print_debug "Should detect error on bareos-dir.conf"
    fi
}

do_reload()
{
    cat > $tmp/bcons <<EOF
reload
messages
EOF
    cat $tmp/bcons | $bin/bconsole -c $conf/bconsole.conf 2>&1 >>$tmp/reload.log

    ps $pid > /dev/null
    if [ $? != 0 ]; then
        estat=1
        print_debug "Bareos shouldn't die with a reload"
    fi

    ls -l /proc/$pid/fd | grep bareos-dir.conf
    if [ $? = 0 ]; then
        estat=1
        print_debug "Should not have bareos-dir.conf open"
    fi
}

start_test

# should be ok
$bin/bareos-dir -t $conf/bareos-dir.conf
if [ $? != 0 ]; then
    estat=1
    print_debug "Error on bareos-dir.conf"
fi

$bin/bareos-ctl-dir start >/dev/null
pid=`cat $working/bareos-dir.$BASEPORT.pid`

sleep 2

ls -l /proc/$pid/fd | grep bareos-dir.conf
if [ $? = 0 ]; then
    estat=1
    print_debug "Should not have bareos-dir.conf open"
fi

# should work well
do_reload

# backup the configuration
cp $conf/bareos-dir.conf $tmp/1


print_debug "Adding uncommented string to bareos-dir.conf"
cat >> $conf/bareos-dir.conf<<EOF
This is an error
EOF
detect_error
do_reload


print_debug "Adding empty job res bareos-dir.conf"
cp $tmp/1 $conf/bareos-dir.conf
cat >> $conf/bareos-dir.conf<<EOF
Job {
}
EOF
detect_error
do_reload


print_debug "Adding two identical Jobs to bareos-dir.conf"
cp $tmp/1 $conf/bareos-dir.conf
cat >> $conf/bareos-dir.conf<<EOF
Job {
  Name = "BackupClient1"
  JobDefs = "DefaultJob"
  Write Bootstrap = "/tmp/regress/working/Client1.bsr"
}
Job {
  Name = "BackupClient1"
  JobDefs = "DefaultJob"
  Write Bootstrap = "/tmp/regress/working/Client1.bsr"
}
EOF
detect_error
do_reload


print_debug "Adding second director to bareos-dir.conf"
cp $tmp/1 $conf/bareos-dir.conf
cat >> $conf/bareos-dir.conf<<EOF
Director {
  Name = second-dir
  DIRport = 1101                # where we listen for UA connections
  QueryFile = "/tmp/regress/bin/query.sql"
  WorkingDirectory = "/tmp/regress/working"
  PidDirectory = "/tmp/regress/working"
  Maximum Concurrent Jobs = 1
  Password = "xxx"         # Console password
  Messages = Daemon
}
EOF

detect_error
do_reload




$bin/bareos-ctl-dir stop >/dev/null

end_test
