#!/bin/sh
#
# Run a simple backup of the Bareos build directory
#   to a tape where the maximum tape file size is set to 1M
#   then restore a few files from it.  Note, by setting the maximum
#   file size to 1M, it runs very slow. There are about 64 files that
#   are created during each of the two backups.
#
TestName="restore-by-file-tape"
JobName=restorebyfile
. scripts/functions

require_tape_drive

scripts/cleanup-tape
scripts/copy-tape-confs

echo "${cwd}/build" >${cwd}/tmp/file-list
sed s%\^%${cwd}% ${cwd}/scripts/flist | sort | uniq >${cwd}/tmp/restore2-list

cp ${cwd}/bin/bareos-sd.conf ${cwd}/tmp/1
sed "s%# Maximum File Size%  Maximum File Size%" ${cwd}/tmp/1 >${cwd}/bin/bareos-sd.conf

change_jobname NightlySave $JobName
start_test

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out   ${cwd}/tmp/log1.out
label storage=tape volume=TestVolume001 slot=0 pool=Default
run job=$JobName level=Full yes
wait
messages
@#
@# now do a restore
@#
@$out   ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bareos-restores storage=tape file=<${cwd}/tmp/restore2-list
yes
wait
messages
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=tape
stop_bareos

dstat=0
#
# We need to stop and start Bareos to
#  test appending to a previously written tape
#
for i in `cat ${cwd}/tmp/restore2-list`; do
   diff $i ${cwd}/tmp/bareos-restores$i
   if [ $? != 0 ] ; then
      dstat=1
   fi
done

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out   ${cwd}/tmp/log1.out
run job=$JobName  level=Full yes
wait
messages
@#
@# now do a restore
@#
@$out   ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bareos-restores
7
<${cwd}/tmp/restore2-list

yes
wait
messages
quit
END_OF_DATA

#
# Bareos was stopped, but we must restart it to
#  test appending to a previously written tape
#
run_bareos
check_for_zombie_jobs storage=tape
stop_bareos

check_two_logs

scripts/check_for_zombie_jobs storage=tape
stop_bareos
for i in `cat ${cwd}/tmp/restore2-list`; do
   diff $i ${cwd}/tmp/bareos-restores$i
   if [ $? != 0 ] ; then
      dstat=1
   fi
done

end_test
