#!/bin/sh
#
# Run a simple backup of the Bareos build directory using the Sparse option
#   then restore it.
#
TestName="sparse-autoxflate-test"
JobName=SparseTest
. scripts/functions

scripts/cleanup
scripts/copy-test-confs
echo "${cwd}/build" >${cwd}/tmp/file-list



mv ${cwd}/bin/bareos-sd.conf ${cwd}/bin/bareos-sd.conf.sed

# enable autoxflate plugin
sed 's@# Maximum File Size = 10KB@# autoxflate plugin settings\
  autodeflate = both  # in/out/both\
  autodeflatealgorithm = gzip # gzip / lzo / lzfast / lz4 / lz4hc\
  # autodeflatelevel = 6 # compression level for gzip\
  autoinflate = both  # in/out/both\
@g' < ${cwd}/bin/bareos-sd.conf.sed > ${cwd}/bin/bareos-sd.conf


# enable plugin directory
mv ${cwd}/bin/bareos-sd.conf ${cwd}/bin/bareos-sd.conf.sed
# enable autoxflate plugin
sed 's@Pid Directory.*@\
Plugin Directory =\"'"${cwd}"'/bin/plugins\"\
@g' < ${cwd}/bin/bareos-sd.conf.sed > ${cwd}/bin/bareos-sd.conf

start_test

cat >${cwd}/tmp/bconcmds <<END_OF_DATA
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
label storage=File volume=TestVolume001
run job=$JobName yes
wait
messages
@#
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bareos-restores select storage=File
unmark *
mark *
done
yes
wait
messages
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=File
stop_bareos

check_two_logs
check_restore_diff
end_test
