#!/bin/sh
#
# Run a simple backup of the Bareos build directory using the Sparse option
#   then restore it.
#
TestName="sparse-lzo-test"
JobName=Sparse-lzo
. scripts/functions

#
# See if library is linked against liblzo2
#
cnt=`ldd ${bin}/libbareos.so 2>/dev/null | grep -c liblzo2`
if test ${cnt} -lt 1; then
   echo "$TestName skipped: not linked for lzo2 compression"
   exit 0
fi

cwd=`pwd`
scripts/cleanup
scripts/copy-test-confs
echo "${cwd}/build" >${cwd}/tmp/file-list

start_test

cat >${cwd}/tmp/bconcmds <<END_OF_DATA
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
label storage=File volume=TestVolume001
run job=SparseLZOTest yes
wait
messages
@#
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bareos-restores select all storage=File done
yes
wait
messages
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=File
stop_bareos

check_two_logs
check_restore_diff
end_test
