#!/bin/sh
#
# Run a simple backup of the Bareos build directory with TLS
#   communications code enabled then restore it.
#
TestName="tls-test"
JobName=tls
. scripts/functions

scripts/cleanup
scripts/copy-tls-confs
echo "${cwd}/build" >${cwd}/tmp/file-list

change_jobname CompressedTest $JobName
start_test

cat <<END_OF_DATA >tmp/bconcmds
messages
@$out tmp/log1.out
status all
status all
messages
label storage=File volume=TestVolume001 pool=Default
run job=$JobName storage=File yes
wait
messages
@#
@# now do a restore
@#
@$out tmp/log2.out
restore where=${cwd}/tmp/bareos-restores select storage=File
unmark *
mark *
done
yes
wait
messages
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=File
stop_bareos

check_two_logs
check_restore_diff
end_test
