#!/bin/sh
#
# Run a simple backup . Create three
#   tapes, each in a different pool, then run two jobs both of which
#   want the disk that is not loaded.  Note, they both have
#   prefers non-mounted tapes.  This should expose bug #801
#
#  This test the SD Virtual autochanger feature.  It is a disk based
#    "autochanger", but does not use any changer script.
#
#  Note, because we limit each drive to a maximum of 3 jobs,
#  the first three start on Drive-0, and the second three start
#  on drive-1 (Prefer Mounted Volumes = no).  Thus since there
#  is only one Volume (TestVolume001) that is valid, three jobs
#  block and ask the user to create a new volume.  However, at some
#  point, the first three jobs finish and free up TestVolum001, and
#  Since we set a poll interval of 15 seconds, after a short wait
#  TestVolume001 will be mounted on drive-1 and the job will
#  complete.  This tests a good number of things.
#
TestName="virtual-changer-test"
JobName="virtualchangertest"
. scripts/functions

scripts/cleanup
scripts/copy-2disk-drive-confs
scripts/prepare-disk-changer

CLIENT=2drive2disk


# Directory to backup.
# This directory will be created by setup_data().
BackupDirectory="${tmp}/data"

# Use a tgz to setup data to be backuped.
# Data will be placed at "${tmp}/data/".
setup_data data/small.tgz

# the default fileset FS_TESTJOB backups all file and directories defined in "${tmp}/file-list".
echo "${BackupDirectory}" >${tmp}/file-list


#change_jobname Virtual $JobName
start_test

# Turn off Prefer Mounted Volumes so we use 2 drives
outf="${cwd}/tmp/sed_tmp"
echo "s%# Prefer Mounted Volumes%  Prefer Mounted Volumes%g" >${outf}
cp ${cwd}/bin/bareos-dir.conf ${cwd}/tmp/1
# Comment the next line out to write everything to one drive
#  otherwise, it writes the two jobs to different drives
sed -f ${outf} ${cwd}/tmp/1 >${cwd}/bin/bareos-dir.conf

# Write out bconsole commands
cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
setdebug level=200 storage=Virtual
@#setdebug level=200 client=$CLIENT
label storage=Virtual volume=TestVolume001 slot=1 Pool=Default drive=0
label storage=Virtual volume=TestVolume002 slot=2 Pool=Full    drive=0
label storage=Virtual volume=TestVolume003 slot=3 Pool=Inc     drive=1
status storage=Virtual
run job=Virtual level=Full Pool=Default yes
run job=Virtual level=Full Pool=Default yes
run job=Virtual level=Full Pool=Default yes
run job=Virtual level=Full Pool=Default yes
run job=Virtual level=Full Pool=Default yes
@sleep 10
status storage=Virtual
list volumes
wait
list volumes
list jobs
status storage=Virtual
messages
quit
END_OF_DATA

# exit

run_bareos
cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@#
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bareos-restores select all storage=Virtual done
yes
wait
messages
quit
END_OF_DATA

run_bconsole

check_for_zombie_jobs storage=Virtual
stop_bareos

check_two_logs
check_restore_diff

end_test
