<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2015 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = _('Client details');
$this->headTitle($title);

?>

<div class="row">

<div class="col-md-12">
<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title"><?php echo $this->translate("Client"); ?></h3>
</div>

<div class="panel-body">

<table class="table table-hover" id="tab-client">
<thead class="bg-primary">
   <th><?php echo $this->translate("Name"); ?></th>
   <th><?php echo $this->translate("Version"); ?></th>
   <th><?php echo $this->translate("Autoprune"); ?></th>
   <th><?php echo $this->translate("Fileretention"); ?></th>
   <th><?php echo $this->translate("Jobretention"); ?></th>
   <th><?php echo $this->translate("Actions"); ?></th>
</thead>
</table>

</div>
</div>
</div>
</div>

<div class="row">
<div class="col-md-12">

<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title"><?php echo $this->translate("Last successful backups"); ?></h3>
</div>

<div class="panel-body">

<table class="table table-hover" id="tab-backups">
<thead class="bg-primary">
   <th><?php echo $this->translate("Job ID"); ?></th>
   <th><?php echo $this->translate("Timestamp"); ?></th>
   <th><?php echo $this->translate("Fileset"); ?></th>
   <th><?php echo $this->translate("Level"); ?></th>
   <th><?php echo $this->translate("Files"); ?></th>
   <th><?php echo $this->translate("Bytes"); ?></th>
   <th><?php echo $this->translate("Actions"); ?></th>
</thead>
</table>

</div>
</div>
</div>
</div>

<?php
   echo $this->headScript()->prependFile($this->basePath() . '/js/datatables.plugins.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/datatables.functions.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/datatables.min.js');
   echo $this->headLink()->prependStylesheet($this->basePath() . '/css/datatables.min.css');
?>

<script>

$(document).ready(function() {

   $('#tab-client').DataTable( {
      "ajax": {
         "url": "<?php echo $this->url('client', array('action' => 'getData'), null) . '?data=details&client='.$this->client; ?>",
         "dataSrc": ""
      },
      "language": {
         "url": "<?php echo $this->basePath() . '/js/dataTables/language/'; ?>" + getLocale('<?php echo $_SESSION['bareos']['locale']; ?>')
      },
      "columns" : [
         { "data": "name" },
         { "data": "uname"},
         { "data": "autoprune" },
         { "data": "fileretention" },
         { "data": "jobretention" },
         { "data": "name" }
      ],
      "paging": false,
      "ordering": false,
      "info": false,
      "pagingType": "full_numbers",
      "stateSave": true,
      "bFilter": false,
      "columnDefs": [
         {
            "targets": 2,
            "render": function(data, type, full, meta) {
               return formatAutoprune(data);
            }
         },
         {
            "targets": 3,
            "render": function(data, type, full, meta) {
               return formatRetention(data);
            }
         },
         {
            "targets": 4,
            "render": function(data, type, full, meta) {
               return formatRetention(data);
            }
         },
         {
            "targets": -1,
            "render": function(data, type, full, meta) {
               return '<a href="<?php echo $this->basePath() . '/restore/index?type=client&client='; ?>'+data+'"><button type="button" class="btn btn-default btn-xs" id="btn-1" data-toggle="tooltip" data-placement="top" title="Restore"><span class="glyphicon glyphicon-import"></span></button></a>';
            }
         }
      ]
   } );

   $('#tab-backups').DataTable( {
      "ajax": {
         "url": "<?php echo $this->url('client', array('action' => 'getData'), null) . '?data=backups&client='.$this->client; ?>",
         "dataSrc": ""
      },
      "language": {
         "url": "<?php echo $this->basePath() . '/js/dataTables/language/'; ?>" + getLocale('<?php echo $_SESSION['bareos']['locale']; ?>')
      },
      "columns" : [
         { "data": "jobid" },
         { "data": "starttime" },
         { "data": null },
         { "data": "level" },
         { "data": "jobfiles" },
         { "data": "jobbytes", "type": "file-size" },
         { "data": null }
      ],
      "paging": true,
      "ordering": true,
      "info": true,
      "pagingType": "full_numbers",
      "stateSave": true,
      "order": [[0, 'desc']],
      "columnDefs": [
         {
            "targets": 0,
            "render": function(data, type, full, meta) {
               return '<a href="<?php echo $this->basePath() . '/job/details/'; ?>'+data+'">'+data+'</a>';
            }
         },
         {
            "targets": 2,
            "render": function(data, type, full, meta) {
               return '<a href="<?php echo $this->basePath(). '/fileset/details/'; ?>'+data.filesetid+'">'+data.fileset+'</a>';
            }
         },
         {
            "targets": 3,
            "render": function(data, type, full, meta) {
               return formatJobLevel(data);
            }
         },
         {
            "targets": 5,
            "render": function(data, type, full, meta) {
               return formatBytes(data);
            }
         },
         {
            "targets": 6,
            "render": function(data, type, full, meta) {
               return '<a class="btn btn-default btn-xs" data-toggle="tooltip" data-placement="top" href="<?php echo $this->basePath(); ?>/restore/?type=client&mergefilesets=1&mergejobs=1&client='+data.client+'&jobid='+data.jobid+'" title="Show Files" id="btn-1"><span class="glyphicon glyphicon-folder-open"></span></a>';
            }
         }
      ]
   } );

   $('#tab-client tbody').on('mouseover', '#btn-1', function () {
      $('[data-toggle="tooltip"]').tooltip();
   } );

   $('#tab-backups tbody').on('mouseover', '#btn-1', function () {
      $('[data-toggle="tooltip"]').tooltip();
   } );

} );

</script>
