<?php

$title = 'Client details';
$this->headTitle($title);

?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<div class="row">

<div class="col-md-9">
<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title">General Information</h3>
</div>

<div class="panel-body">

<table class="table table-striped table-bordered" style="font-size: 9pt;">

<tr><td><b>Client</b></td><td><?php echo $this->escapeHtml($client->clientid); ?></td></tr>
<tr><td><b>Name</b></td><td><?php echo $this->escapeHtml($client->name); ?></td></tr>
<tr><td><b>Version</b></td><td><?php echo $this->escapeHtml($client->uname); ?></td></tr>
<tr><td><b>Autoprune</b></td><td><?php echo $this->escapeHtml($client->autoprune); ?></td></tr>
<tr><td><b>Fileretention</b></td><td><?php echo $this->printRetention($client->fileretention) . " days"; ?></td></tr>
<tr><td><b>Jobretention</b></td><td><?php echo $this->printRetention($client->jobretention) . " days"; ?></td></tr>

<tr>
<td><b>Last successful backup</b></td>
<td>
<?php if($job==null) : ?> never
<?php elseif($job!=null) : ?>
<a href="<?php echo $this->url('job', array('action'=>'details', 'id' => $job->jobid)); ?>" title="<?php echo $job->endtime; ?>"><?php echo $this->printHumanReadableTimeperiod($job->endtime, "fuzzy")?> (Level: <?php echo $this->printJobLevel($job->level); ?>)</a>
<?php endif; ?>
</td>
</tr>

<!-- <tr><td><b>Online status</b></td><td></td></tr> -->

</table>

</div>

</div>
</div>


<div class="col-md-3">

<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">Actions</h3>
</div>

<div class="panel-body">
<a class="btn btn-primary btn-block" href="<?php echo $this->url(
						'restore',
						array('action' => 'index'),
						array('query' => array(
							'type' => 'client',
							'client' => $client->name,
							'restoreclient' => $client->name
							)
						)); ?>" role="button">Restore</a>
</div>
</div>

</div>
</div>

<div class="row">
<div class="col-md-9">

<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">Last backups</h3>
</div>

<div class="panel-body">

<table class="table table-bordered table-condensed">

<tr>
<th class="bg-primary"><?php echo $this->translate("Job"); ?></th>
<th class="bg-primary"><?php echo $this->translate("Timestamp"); ?></th>
<th class="bg-primary"><?php echo $this->translate("Fileset"); ?></th>
<th class="bg-primary"><?php echo $this->translate("Level"); ?></th>
<th class="bg-primary"><?php echo $this->translate("Files"); ?></th>
<th class="bg-primary"><?php echo $this->translate("Bytes"); ?></th>
</tr>

<?php if($this->backups != null) : ?>

<?php foreach ($this->backups as $backup) : ?>

<tr>
<td><?php echo $this->escapeHtml($backup['jobid']); ?></td>
<td><?php echo $this->escapeHtml($backup['starttime']); ?></td>
<td><?php echo $this->escapeHtml($backup['fileset']); ?></td>
<td><?php echo $this->escapeHtml($this->printJobLevel($backup['level'])); ?></td>
<td><?php echo $this->escapeHtml($backup['jobfiles']); ?></td>
<td><?php echo $this->escapeHtml($this->printBytes($backup['jobbytes'])); ?></td>
</tr>

<?php endforeach; ?>

<?php endif; ?>

</table>

</div>

</div>
</div>

</div>
