<?php

$title = 'Client details';
$this->headTitle($title);

?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<div class="row">

<div class="col-md-7">
<div class="panel panel-default">
	  
<div class="panel-heading">
<h3 class="panel-title"><?php echo "Client " . $this->escapeHtml($client->clientid); ?> - <?php echo $this->escapeHtml($client->name); ?></h3>
</div>
    
<div class="panel-body">

<table class="table table-striped table-hover" style="font-size: 9pt;">

<tr><td>Client</td><td><?php echo $this->escapeHtml($client->clientid); ?></td></tr>
<tr><td>Name</td><td><?php echo $this->escapeHtml($client->name); ?></td></tr>
<tr><td>Version</td><td><?php echo $this->escapeHtml($client->uname); ?></td></tr>
<tr><td>Autoprune</td><td><?php echo $this->escapeHtml($client->autoprune); ?></td></tr>
<tr><td>Fileretention</td><td><?php echo $this->printRetention($client->fileretention) . " days"; ?></td></tr>
<tr><td>Jobretention</td><td><?php echo $this->printRetention($client->jobretention) . " days"; ?></td></tr>
<tr><td>Last successful backup</td><td><a href="<?php echo $this->url('job', array('action'=>'details', 'id' => $job->jobid)); ?>" title="<?php echo $job->endtime; ?>"><?php echo $this->printHumanReadableTimeperiod($job->endtime, "fuzzy")?> (Level: <?php echo $this->printJobLevel($job->level); ?>)</a></td></tr>

</table>

</div>

</div>
</div>

<div class="col-md-5">

<div class="panel panel-default">
	  
<div class="panel-heading">
<h3 class="panel-title">todo placeholder (client stats)</h3>
</div>
    
<div class="panel-body">
</div>
</div>

</div>

</div>
