<?php

$title = 'Client';
$this->headTitle($title);

?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<?php foreach($clients as $client) : ?>

<div class="row">

<div class="col-md-12">
<div class="panel panel-default">
    
<div class="panel-body">

<table class="table table-striped table-hover" style="font-size: 9pt;">

<tr>
	<th>Client</th>
	<th>Name</th>
	<th>Version</th>
	<th>Autoprune</th>
	<th>Fileretention</th>
	<th>Jobretention</th>
</tr>
<tr>

	<td><a href="<?php echo $this->url('client', array('action'=>'details', 'id' => $client->clientid)); ?>"><?php echo $this->escapeHtml($client->clientid); ?></a></td>
	<td><?php echo $this->escapeHtml($client->name); ?></td>
	<td><?php echo $this->escapeHtml($client->uname); ?></td>
	<td><?php echo $this->escapeHtml($client->autoprune); ?></td>
	<td><?php echo $this->printRetention($client->fileretention) . " days"; ?></td>
	<td><?php echo $this->printRetention($client->jobretention) . " days"; ?></td>

</tr>

</table>

</div>
</div>
</div>

</div>

<?php endforeach; ?>

