<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2015 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Clients';
$this->headTitle($title);

?>

<div class="row">

<div class="col-md-12">
<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title">Clients</h3>
</div>

<div class="panel-body">

<p>
Clients per page:
<a href="<?php echo $this->url('client', array('order_by' => $this->order_by, 'order' => $this->order, 'limit' => '10', null, null, true)); ?>">10</a> |
<a href="<?php echo $this->url('client', array('order_by' => $this->order_by, 'order' => $this->order, 'limit' => '25', null, null, true)); ?>">25</a> |
<a href="<?php echo $this->url('client', array('order_by' => $this->order_by, 'order' => $this->order, 'limit' => '50', null, null, true)); ?>">50</a> |
<a href="<?php echo $this->url('client', array('order_by' => $this->order_by, 'order' => $this->order, 'limit' => '100', null, null, true)); ?>">100</a>
</p>

<table class="table table-bordered table-condensed">

<tr>
	<th class="bg-primary">Client</th>
	<th class="bg-primary">Name</th>
	<th class="bg-primary">Version</th>
	<th class="bg-primary">Autoprune</th>
	<th class="bg-primary">Fileretention</th>
	<th class="bg-primary">Jobretention</th>
	<th class="bg-primary"></th>
</tr>

<?php foreach($this->paginator as $client) : ?>

<tr>
	<td><a href="<?php echo $this->url('client', array('action'=>'details', 'id' => $client['clientid'])); ?>"><?php echo $this->escapeHtml($client['clientid']); ?></a></td>
	<td><a href="<?php echo $this->url('client', array('action'=>'details', 'id' => $client['clientid'])); ?>"><?php echo $this->escapeHtml($client['name']); ?></a></td>
	<td><?php echo $this->escapeHtml($client['uname']); ?></td>
	<td><?php echo $this->escapeHtml($client['autoprune']); ?></td>
	<td><?php echo $this->printRetention($client['fileretention']) . " days"; ?></td>
	<td><?php echo $this->printRetention($client['jobretention']) . " days"; ?></td>
	<td><a href="<?php echo $this->url(
                                        'restore',
                                        array('action' => 'index'),
                                        array('query' => array(
                                                'type' => 'client',
                                                'client' => $client['name'],
                                                'restoreclient' => $client['name']
                                        )
                                )); ?>" class="btn btn-primary" role="button"><span class="glyphicon glyphicon-import"></span> Restore</a>
	</td>

</tr>

<?php endforeach; ?>

</table>

<?php

echo $this->paginationControl(
			$this->paginator,
			'Elastic',
			array('partial/paginator.phtml', 'Client'),
			array('route' => 'client')
		);

?>

</div>
</div>
</div>
</div>
