#!/bin/bash
set -e
set -o pipefail
set -u
#
# Run a simple backup
#
TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions
#shellcheck source=functions
. functions

start_test

cat <<END_OF_DATA >"$tmp/bconcmds"
@$out /dev/null
messages
@$out $log_home/create-backup.out
setdebug level=100 storage=File
label volume=TestVolume001 storage=File pool=Full
run job=$JobName yes
status director
status client
status storage=File
wait
messages
quit
END_OF_DATA

run_bconsole
check_for_zombie_jobs storage=File

expect_grep "No prior Full backup Job record found." \
	    "$log_home/create-backup.out" \
	    "Bad initial state. No backup should exist yet."

expect_grep "Start Backup JobId 1" \
	    "$log_home/create-backup.out" \
	    "Did not create backup job with id 1."

expect_grep "Backup OK" \
	    "$log_home/create-backup.out" \
	    "Backup was not created correctly."

expect_not_grep "warning" \
		"$log_home/create-backup.out" \
		"Backup was not created correctly."

end_test
