The Storage directive defines the name of the storage services where you want to backup the FileSet data. For additional details, see the :ref:`DirectorResourceStorage` of this manual. The Storage resource may also be specified in the Job’s Pool resource, in which case the value in the Pool resource overrides any value in the Job. This Storage resource definition is not required by either the Job resource or in the Pool, but it must be specified in one or the other, if not an
error will result.

