Send the message to the email addresses that are given as a comma separated list in the address field if the Job terminates normally (no error condition). :strong:`Mail On Success`\  messages are grouped together during a job and then sent as a single email message when the job terminates. This destination differs from the mail destination in that if the Job terminates abnormally, the message is totally discarded (for this destination). If the Job terminates normally, it is
emailed.

