This resource specification is similar to the :config:option:`dir/messages/MailCommand`\  except that it is used for Operator messages. The substitutions performed for the :config:option:`dir/messages/MailCommand`\  are also done for this command. Normally, you will set this command to the same value as specified for the :config:option:`dir/messages/MailCommand`\ . The :strong:`Operator Command`\  directive must
appear in the Messages resource before the :config:option:`dir/messages/Operator`\  directive.

