#!/bin/bash
set -e
set -o pipefail
set -u

#
# This systemtest validates that devices, multiplied using the 'Count' directive,
# work and can be used as any other device.
# To validate the devices behaviour, we perform the following actions:
#  - backups
#  - restores
#  - purges
#  - truncates
#

TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-to-pool1
#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions
"${rscripts}"/cleanup
"${rscripts}"/setup

# Fill ${BackupDirectory} with data.
setup_data

start_test

cat <<END_OF_DATA >$tmp/bconcmds
@$out ${NULL_DEV}
messages
@$out $tmp/backup-log.out
run job=$JobName level=Full storage=ImplicitAutochangerFile yes
run job=$JobName level=Full storage=ImplicitAutochangerFile yes
run job=$JobName level=Full storage=ImplicitAutochangerFile yes
run job=$JobName level=Full storage=ImplicitAutochangerFile yes
run job=$JobName level=Full storage=ImplicitAutochangerFile yes
@$out $tmp/status-storage.out
status storage=ImplicitAutochangerFile
@$out $tmp/backup-log.out
wait
messages
END_OF_DATA

run_bareos "$@"

for i in {0..3}; do
  expect_grep "Device \\\"ImplicitAutchangerDevice000$i\\\""\
    $tmp/status-storage.out\
    "Device \\\"ImplicitAutchangerDevice000$i\\\" was not created."
done

for i in {1..3}; do
  expect_grep "Using Device \\\"ImplicitAutchangerDevice000$i\\\" (storage) to write."\
    $tmp/backup-log.out\
    "Device \\\"ImplicitAutchangerDevice000$i\\\" was not used."
done

expect_not_grep "Using Device \\\"ImplicitAutchangerDevice\\\" (storage) to write."\
  $tmp/backup-log.out\
  "Used device \\\"ImplicitAutchangerDevice\\\". This device has count > 1 so only copies with serial numbers of this device should be used."

end_test