#!/bin/sh
#
# Run a simple backup
#   then restore it.
#
TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

console_messages_file="${working}"/.conmsg
syslog_file="${working}"/syslog.txt
dblog_file="${working}"/dblog.txt
stdout_file="${working}"/stdout.txt
stderr_file="${working}"/stderr.txt
extra_append_file="${logdir}"/bareos.log

rm -f "$console_messages_file"
rm -f "$syslog_file"
rm -f "$dblog_file"
rm -f "$stdout_file"
rm -f "$stderr_file"
rm -f "$extra_append_file"

function exit_error() {
  [ "$1" == "" ] || echo "$1"
  estat=1
  end_test
  exit 1
}

function check_output_file {
  [ -f "$1" ] || exit_error "$1 does not exist"

  if ! grep --quiet "This is an error message" "$1"; then
    exit_error "\"$1\" does not contain the expected text"
  fi
}

start_test

${BAREOS_UNITTESTS_BINARY_DIR}/messages > "$stdout_file" 2> "$stderr_file" || exit_error

check_output_file "$console_messages_file"
check_output_file "$syslog_file"
check_output_file "$dblog_file"
check_output_file "$stdout_file"
check_output_file "$stderr_file"
check_output_file "$extra_append_file"

end_test
