<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos for the canonical source repository
 * @copyright Copyright (c) 2013-2022 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = _('Analytics');
$this->headTitle($title);

?>

<?php if($this->acl_alert) : echo $this->ACLAlert($this->invalid_commands); elseif(!$this->acl_alert) : ?>

<ul class="nav nav-tabs">
   <li><a href="<?php echo $this->url('analytics', array('action'=>'index')); ?>"><?php echo $this->translate('Stored Data'); ?></a></li>
   <li class="active"><a href="<?php echo $this->url('analytics', array('action'=>'checkpoints')); ?>"><?php echo $this->translate('Checkpoints'); ?></a></li>
</ul>

<br />

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Checkpoint Transfer Rates'); ?></h3>
      </div>
      <div class="panel-body">
        <div class="col-md-2">
          <span><strong>Chart:</strong></span>
          <label><input type="radio" id="ct0" name="charttype" checked="checked" value="0" onclick="setChartType(0)"/> Stacked Area</label>
          <label><input type="radio" id="ct1" name="charttype" value="1" onclick="setChartType(1)"/> Line</label>
        </div>
        <div class="col-md-4">
          <span><strong>Checkpoint collection: </strong></span>
          <label><input type="radio" id="p0" name="period" checked="checked" value="0" onclick="setCheckpointNumber(60)"/> 1</label>
          <label><input type="radio" id="p1" name="period" value="1" onclick="setCheckpointNumber(300)"/> 5</label>
          <label><input type="radio" id="p2" name="period" value="2" onclick="setCheckpointNumber(600)"/> 10</label>
          <label><input type="radio" id="p3" name="period" value="3" onclick="setCheckpointNumber(900)"/> 15</label>
          <label><input type="radio" id="p4" name="period" value="4" onclick="setCheckpointNumber(1800)"/> 30</label>
          <label><input type="radio" id="p5" name="period" value="5" onclick="setCheckpointNumber(3600)"/> 60</label>
          <span> minute(s)</span>
          <br />
          <span><strong>Checkpoint interval: </strong></span><span><span id="checkpointinterval"><?php echo $_SESSION['bareos']['analytics_checkpoint_interval'] / 1000; ?></span> seconds</span>
          <br />
          <span><strong>Maximum checkpoints: </strong></span><span><span id="checkpointnumber">20</span> for each running job</span>
        </div>
        <div class="col-md-4">
        <span><strong>Checkpoint data:</strong></span>
          <label><input type="radio" id="cd0" name="chartdata" checked="checked" value="0" onclick="setCheckpointTransferrate(0)"/> Last transfer rate</label>
          <label><input type="radio" id="cd1" name="chartdata" value="1" onclick="setCheckpointTransferrate(1)"/> Average transfer rate</label>
        </div>
      </div>
      <div class="panel-body">
        <div id="runningjobs-chart"></div>
      </div>
      <div class="panel-body">
      <div id="runningjobs-chart-average"></div>
      </div>
    </div>
  </div>
</div>

<?php
  echo $this->headScript()->prependFile($this->basePath() . '/js/apexcharts.min.js');
?>

<style>
</style>

<script>

var checkpointnumber = 20 // checkpoints stored in map for each running jobid
var displayrange = checkpointnumber * <?php echo $_SESSION['bareos']['analytics_checkpoint_interval']; ?>;
var checkpointinterval = <?php echo $_SESSION['bareos']['analytics_checkpoint_interval']; ?>;
var checkpointtransferrate = "last"

var charttype = "area"
var chartstacked = true
var charttitle = "Last Transfer Rate"

function setCheckpointNumber(value) {
  checkpointnumber = value / (checkpointinterval / 1000)
  displayrange = checkpointnumber * <?php echo $_SESSION['bareos']['analytics_checkpoint_interval']; ?>;
  $("#checkpointnumber").html(checkpointnumber)
}

function setCheckpointTransferrate(value) {
  switch(value) {
    case 0:
      checkpointtransferrate = "last"
      charttitle = "Last Transfer Rate"
      break;
    case 1:
      checkpointtransferrate = "average"
      charttitle = "Average Transfer Rate"
      break;
    default:
      break;
  }
}

function setChartType(value) {
  switch(value) {
    // stacked area chart
    case 0:
      charttype = "area"
      chartstacked = true
      break;
    // line chart
    case 1:
      charttype = "line"
      chartstacked = false
      break;
    default:
      charttype = "area"
      chartstacked = true

  }

  chart.updateOptions({
    chart: {
      type: charttype,
      stacked: chartstacked
    }
  })
}

function getCurrentTime() {
  let timezoneoffset = new Date().getTimezoneOffset() * 60 * 1000;
  var currenttime = new Date().getTime();

  return (currenttime -= timezoneoffset);
}

function formatBytes(value) {
  let factor = 1000 // change to 1024 if required
  let decimal = 2 // change if required
  let megabyte = factor * factor

  return (value / megabyte).toFixed(decimal)
}

var options = {
  series: [],
  title: {
    text: 'Last Transfer Rate',
    align: 'left'
  },
  noData: {
    text: 'No data available.'
  },
  chart: {
    id: 'runningjobs-chart1',
    height: 500,
    type: charttype,
    stacked: chartstacked,
    animations: {
      enabled: false
    },
    toolbar: {
      show: false,
      tools: {
        download: false,
        selection: true,
        zoom: true,
        zoomin: true,
        zoomout: true,
        pan: true,
        reset: true
      }
    },
    autoselected: 'zoom'
  },
  dataLabels: {
    enabled: false
  },
  stroke: {
    curve: 'smooth'
  },
  markers: {
    size: 2
  },
  xaxis: {
    type: 'datetime',
    range: displayrange,
    min: getCurrentTime() - displayrange,
    max: getCurrentTime()
  },
  yaxis: {
    labels: {
      formatter: function (value) {
        return value + " MB/s";
      }
    }
  },
  legend: {
    show: true,
    showForSingleSeries: true,
    onItemClick: {
      toggleDataSeries: true
    },
    onItemHover: {
      highlightDataSeries: true
    },
    position: 'bottom',
    horizontalAlign: 'left'
  },
  grid: {
    borderColor: '#aaa',
    strokeDashArray: 4,
  },
  tooltip: {
    x: {
      format: "HH:mm:ss"
    }
  },
  theme: {
    mode: 'light',
    palette: 'palette1'
  }
};

var chart = new ApexCharts(document.querySelector("#runningjobs-chart"), options);
chart.render();

var runtimedata = new Map()
var series = []

function updateRunningJobsData() {
  $.ajax({
    url: "<?php echo $this->url('analytics', array('action' => 'getData'), null) . '?data=checkpoints'; ?>",
    dataType: 'json',
    timeout: 10000,
    success: function(response) {
      if(response.length > 0) {
        response.forEach((element) => {
          if(runtimedata.has(element.jobid) === false) {
            runtimedata.set(element.jobid, [[],[],[],[]])
            runtimedata.get(element.jobid)[0].push(element.name)
          }
          if(runtimedata.get(element.jobid)[1].length > checkpointnumber - 1) {
            runtimedata.get(element.jobid)[1].shift()
            runtimedata.get(element.jobid)[3].shift()
          }
          runtimedata.get(element.jobid)[1].push({x: element.lastcheckpointtime, y: formatBytes(element.lasttransferrate)})
          runtimedata.get(element.jobid)[2] = element.lastcheckpointtime
          runtimedata.get(element.jobid)[3].push({x: element.lastcheckpointtime, y: formatBytes(element.averagetransferrate)})
        })
      }
      runtimedata.forEach((value, key) => {
        if(getCurrentTime() - value[2] > displayrange) {
          runtimedata.delete(key)
        }
      })
    },
    error: function() {},
    parsererror: function() {},
    timeout: function() {}
  })
}

function updateChart() {

  series1 = []
  series2 = []

  runtimedata.forEach((value, key) => {
    series1.push({name: key + " " + value[0][0], data: value[1]})
    series2.push({name: key + " " + value[0][0], data: value[3]})
  })
  
  chart1.updateOptions({
    series: series1,
    xaxis: {
      type: 'datetime',
      range: displayrange,
      min: getCurrentTime() - displayrange,
      max: getCurrentTime(),
    }
  })

  chart2.updateOptions({
    series: series2,
    xaxis: {
      type: 'datetime',
      range: displayrange,
      min: getCurrentTime() - displayrange,
      max: getCurrentTime(),
    }
  })

}

const updateViewInterval = setInterval(updateView, <?php echo $_SESSION['bareos']['analytics_checkpoint_interval']; ?>)

function updateView() {
  updateRunningJobsData()
  updateChart()
  // debug
  // console.log(runtimedata)
}

</script>

<?php endif; ?>
