#!/bin/bash
set -e
set -o pipefail
set -u
#
#set -x
#trap read debug

#shellcheck source=../../environment.in
. ./environment
#shellcheck source=../../scripts/functions
. "${rscripts}"/functions
. ./reload_test_functions

TestName="$(get_test_name "$0")"
export TestName
export estat

export temporary_director_config_file="$config_directory_dir_additional_test_config/another_director.conf"
export bconsole_command_file="$tmp/bconsole_reload_command"
console_logfile="$tmp/console.log"

############################################
start_test
############################################

#cleanup possible leftover from last run
remove_console_logfile

setup_config
#reload modified config
add_duplicate_dir_to_config
test_reload_will_not_crash_director
find_error_string_in_console_log 'Fatal error: Only one Director resource permitted'

############################################
end_test
############################################
