#!/bin/bash
set -e
set -o pipefail
set -u

#shellcheck source=../../environment.in
. ./environment
#shellcheck source=../../scripts/functions
. "${BAREOS_SCRIPTS_DIR}"/functions
. ./reload_test_functions

export director_debug_level=""
#director_debug_level="-d 200"

#be sure no director is started
stop_director

#cleanup possible leftover from last run
${BAREOS_SCRIPTS_DIR}/cleanup
${BAREOS_SCRIPTS_DIR}/setup

start_director
