#!/bin/bash
set -e
set -o pipefail
set -u
#trap read debug

#shellcheck source=../../environment.in
. ./environment
#shellcheck source=../../scripts/functions
. "${rscripts}"/functions
. ./reload_test_functions

TestName="$(get_test_name "$0")"
export TestName
export estat

bconsole_command_file="$tmp/bconsole_reload_command"
console_logfile="$tmp/console.log"

############################################
start_test
############################################

setup_config
#reload unmodified config
test_reload_will_not_crash_director

############################################
end_test
############################################
