#!/usr/bin/env bash
set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../environment.in
. ./environment

OS=$(uname)
if [[ $OS =~ MINGW64_.* ]];
then
  echo "Test $TestName does not work on windows: stored_conf.cc:570 Backend autochanger_test for device File1 not available."
  exit 77
fi


#shellcheck source=../scripts/functions
. "${rscripts}"/functions

start_test

cat <<END_OF_DATA >"$tmp/bconcmds"
label barcodes slots=1 drive=0 pool=Incremental yes
release alldrives
mount drive=1 slot=1
run job=backup-bareos-fd yes
wait
END_OF_DATA

run_bconsole

end_test
