#!/bin/sh
#
TestName="$(basename "$(pwd)")"
export TestName
. ./environment
. "${rscripts}"/functions
"${rscripts}"/cleanup
"${rscripts}"/setup


exit_failure()
{
  estat=1
  end_test
}

start_test

${BAREOS_UNITTESTS_BINARY_DIR}/catalog || exit_failure

end_test
