#!/bin/sh
#
# Run a simple backup
#   then restore it.
#
TestName="$(basename "$(pwd)")"
export TestName

. ./environment
. ${scripts}/functions

${scripts}/cleanup
${scripts}/setup

start_test
./../../../../b/core/src/tests/catalog
end_test
