#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2025-2025 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

set -e
set -o pipefail
set -u

#
# run multiple jobs and verify that pruning of jobs works
#

TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../../environment.in
. ./environment

#shellcheck source=../../scripts/functions
. "${rscripts}"/functions

start_test

cat <<END_OF_DATA >"$tmp/bconcmds"
@$out ${log_home}/backup.out
run job=$regularjob_name Level=Full yes
run job=$regularjob_name Level=Full yes
wait
@sleep 2
messages
@$out ${log_home}/prune.out
prune jobs pool=Full yes
wait
quit
END_OF_DATA

run_bconsole

check_log "${log_home}/backup.out"

expect_grep "Purging the following 2 JobIds: 8,10" \
  "${log_home}/prune.out" \
  "Expected pruned jobids not found" \
  "Purging the"

expect_grep "Pruned 2 Jobs for client bareos-fd from catalog." \
  "${log_home}/prune.out" \
  "Expected number of jobs pruned not found"

end_test
