If set to :strong:`yes` this directive will use the optimizations for memory size over speed. So it will try to use less memory which may lead to a somewhat lower speed. Its currently mostly used for keeping all hardlinks in memory.

If none of :config:option:`dir/director/OptimizeForSize`\  and :config:option:`dir/director/OptimizeForSpeed`\  is enabled, :config:option:`dir/director/OptimizeForSize`\  is enabled by default.

