The time specifies the maximum allowed time that a job may block waiting for a resource (such as waiting for a tape to be mounted, or waiting for the storage or file daemons to perform their duties), counted from the when the job starts, (not necessarily the same as when the job was scheduled).



.. figure:: /include/images/different_time.*
   :alt: Job time control directives
   :name: fig:differenttime
   :width: 13cm

   Job time control directives

