#!/bin/bash
set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

bstat=0
dstat=0
estat=0
rstat=0
zstat=0

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions
setup_data

selftest_log=$tmp/selftest_log.out
wildcard_log=$tmp/wildcard_log.out

job_log=$logdir/bareos.log

rm -f $selftest_log
rm -f $job_log

./sbin/testfind-testfind -c etc/bareos -f SelfTest | tee  "$selftest_log"
./sbin/testfind-testfind -c etc/bareos -f Wildtest | tee  "$wildcard_log"

expect_grep "Total files.*50" \
            "$selftest_log" \
            "Number of files is incorrect."

expect_grep "Hard links.*2" \
            "$selftest_log" \
            "Number of files is incorrect."

expect_grep "Total files.*18" \
            "$wildcard_log" \
            "Number of files is incorrect."

end_test
