#!/bin/sh
#
# This systemtest tests the oVirt plugin functionality
# of the Bareos FD by using the supplied module
#   BareosFdPluginPercona.py
#
TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd
. ./environment
. ${scripts}/functions

${scripts}/cleanup
${scripts}/setup

# Directory to backup.
# This directory will be created by setup_data().
# BackupDirectory="${tmp}/data"

# Use a tgz to setup data to be backed up.
# Data will be placed at "${tmp}/data/".
# setup_data

start_test

cat <<END_OF_DATA >$tmp/bconcmds
@$out /dev/null
messages
@$out $tmp/log1.out
setdebug level=100 storage=File
label volume=TestVolume001 storage=File pool=Full
run job=$JobName level=Full yes
status director
status client
status storage=File
wait
messages
@#
@# now do a restore
@#
@$out $tmp/log2.out
wait
restore client=bareos-fd fileset=PerconaTest where=$tmp/bareos-restores pluginoptions=python:local=yes select all done
yes
wait
messages
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=File
stop_bareos

check_two_logs

# Check restored disk image content
restored_disk_image=$(find $tmp/bareos-restores -type f | grep -v "\.ovf" | tail -1)
if [ $(strings $restored_disk_image | tail -1) == "BareosTest" ]; then
    echo "Restored disk image content OK"
else
    echo "Restored disk image ERROR: Does not contain expected string"
    dstat=1
fi

end_test
