#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2024-2024 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

set -e
set -o pipefail
set -u
#
# Run a simple backup
#

TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd

#shellcheck source=../environment.in
. ./environment
runner_name="$(basename "$0")"
log_home="${tmp}/${runner_name}"
mkdir -p "${log_home}"

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

start_test

cat <<END_OF_DATA >"$tmp/bconcmds"
@$out /dev/null
messages
@$out $log_home/create-backup.out
setdebug level=100 storage=File trace=1
label volume=BackupVol storage=File pool=Full
run job=$JobName yes
status director
status client
status storage=File
wait
messages
update volstatus=Used volume=BackupVol
@$out $log_home/jobs.out
list jobs
quit
END_OF_DATA

run_bconsole
check_for_zombie_jobs storage=File

expect_grep "No prior Full backup Job record found." \
	    "$log_home/create-backup.out" \
	    "Bad initial state. No backup should exist yet."

expect_grep "Start Backup JobId 1" \
	    "$log_home/create-backup.out" \
	    "Did not create backup job with id 1."

expect_grep "Backup OK" \
	    "$log_home/create-backup.out" \
	    "Backup was not created correctly."

expect_grep "Using just in time reservation for job" \
            "$log_home/create-backup.out" \
            "Backup job did not use just in time reservation."

end_test
