#!/bin/bash
set -e
set -o pipefail
set -u
#
# Run a simple backup
#   then restore it.
#
TestName="$(basename "$(pwd)")"
export TestName

backup1=backup-bareos-fd
backup2=backup-bareos-fd
backup3=backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions


echo "/home/alaa/Documents/smallfiles/" >"$tmp/file-list"

start_test

cat <<END_OF_DATA >"$tmp/bconcmds"
@$out /dev/null
messages
@$out $tmp/paralell-backup.out
run job=${backup1} level=Full yes
run job=${backup1} level=Full yes
run job=${backup1} level=Full yes
wait
messages

@$out $tmp/paralell-restore.out
restore jobid=1 all done
1
yes
restore jobid=2 all done
2
yes
restore jobid=3 all done
3
yes
wait
messages
quit
END_OF_DATA

#run job=restore1 jobid=1 yes
#run job=restore2 jobid=2 yes
#run job=restore3 jobid=3 yes

run_bconsole

for i in 1 2 3; do
    diffr=$(diff -qr ~/Documents/smallfiles tmp/restore$i/home/alaa/Documents/smallfiles)
    echo $diffr
    if [ "${diffr}" != "" ]; then
        echo "bad diff backup $i"
    fi
done

end_test
