#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2026 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

JobNames=(
  backup-bareos-fd
  backup-bareos-fd-pluginoptions
  backup-bareos-fd-plugin-vmware
  backup-bareos-fd-plugin-postgresql
  backup-bareos-fd-plugin-proxmox
  backup-bareos-fd-plugin-mariabackup
  backup-bareos-fd-plugin-percona-xtrabackup
  backup-bareos-fd-plugin-ldap
  backup-bareos-fd-plugin-libcloud
  backup-bareos-fd-plugin-hyperv
  backup-bareos-fd-plugin-grpc
)

. ./environment
. "${BAREOS_SCRIPTS_DIR}/functions"

start_test

cat <<END_OF_DATA >"${tmp}/bconcmds"
@$out ${NULL_DEV}
messages
@$out ${tmp}/webui-vue-create-backup.out
$(for job in "${JobNames[@]}"; do
  echo "run job=${job} yes"
  echo "wait"
done)
messages
quit
END_OF_DATA

run_bconsole

expect_grep 'Termination:.*Backup OK' \
  "${tmp}/webui-vue-create-backup.out" \
  "Backup did not succeed."
for job in "${JobNames[@]}"; do
  expect_grep "${job}" \
    "${tmp}/webui-vue-create-backup.out" \
    "Plugin backup job ${job} did not run."
done

end_test
