-- read-only access for third-party applications
-- for tables
GRANT SELECT ON TABLE Path TO @DB_USER@;
GRANT SELECT ON TABLE File TO @DB_USER@;
GRANT SELECT ON TABLE RestoreObject TO @DB_USER@;
GRANT SELECT ON TABLE Job TO @DB_USER@;
GRANT SELECT ON TABLE JobHisto TO @DB_USER@;
GRANT SELECT ON TABLE Location TO @DB_USER@;
GRANT SELECT ON TABLE Fileset TO @DB_USER@;
GRANT SELECT ON TABLE JobMedia TO @DB_USER@;
GRANT SELECT ON TABLE Media TO @DB_USER@;
GRANT SELECT ON TABLE MediaType TO @DB_USER@;
GRANT SELECT ON TABLE Storage TO @DB_USER@;
GRANT SELECT ON TABLE Device TO @DB_USER@;
GRANT SELECT ON TABLE Pool TO @DB_USER@;
GRANT SELECT ON TABLE Client TO @DB_USER@;
GRANT SELECT ON TABLE Log TO @DB_USER@;
GRANT SELECT ON TABLE LocationLog TO @DB_USER@;
GRANT SELECT ON TABLE Counters TO @DB_USER@;
GRANT SELECT ON TABLE BaseFiles TO @DB_USER@;
GRANT SELECT ON TABLE PathHierarchy TO @DB_USER@;
GRANT SELECT ON TABLE PathVisibility TO @DB_USER@;
GRANT SELECT ON TABLE Version TO @DB_USER@;
GRANT SELECT ON TABLE Status TO @DB_USER@;
GRANT SELECT ON TABLE NDMPLevelMap TO @DB_USER@;
GRANT SELECT ON TABLE NDMPJobEnvironment TO @DB_USER@;
GRANT SELECT ON TABLE DeviceStats TO @DB_USER@;
GRANT SELECT ON TABLE JobStats TO @DB_USER@;
GRANT SELECT ON TABLE TapeAlerts TO @DB_USER@;
\g
