USE mysql

CREATE USER '@DB_USER@'@'localhost' IDENTIFIED BY '@DB_PASS@';
CREATE USER '@DB_USER@'@'127.0.0.1' IDENTIFIED BY '@DB_PASS@';
CREATE USER '@DB_USER@'@'::1' IDENTIFIED BY '@DB_PASS@';

GRANT ALL PRIVILEGES ON TABLE @DB_NAME@.* TO @DB_USER@@localhost @DB_PASS@;
GRANT ALL PRIVILEGES ON TABLE @DB_NAME@.* TO @DB_USER@@'127.0.0.1' @DB_PASS@;
GRANT ALL PRIVILEGES ON TABLE @DB_NAME@.* TO @DB_USER@@'::1' @DB_PASS@;
FLUSH PRIVILEGES;
