#!/bin/bash
set -e
set -o pipefail
set -u
#trap read debug

TestName="$(basename "$(pwd)")"

export TestName
export estat

#shellcheck source=../environment.in
. ./environment
#shellcheck source=../scripts/functions
. "${rscripts}"/functions
#shellcheck source=../scripts/reload_test_functions
. "${rscripts}"/reload_test_functions

temporary_config_file="$config_directory_dir_additional_test_config/another_client.conf"
bconsole_command_file="$tmp/bconsole_reload_command"
console_logfile="$tmp/console.log"
console_show_client_output_file="$tmp/list_of_clients.out"

director_debug_level=""
#director_debug_level="-d 200"




############################################
start_test
############################################

#be sure no director is started
stop_director

#cleanup possible leftover from last run
${rscripts}/cleanup
remove_console_logfiles

${rscripts}/setup
start_director

#reload modified config
add_another_client
test_reload_will_not_crash_director
find_added_client_in_config

stop_director

############################################
end_test
############################################
