#!/bin/bash

set -e
set -u

BASEDIR=`dirname $0`
TARGETDIR="${BASEDIR}/../en/new_main_reference"
# relative from TARGETDIR
SCRIPTDIR="../../scripts"
DATADIR="../main/autogenerated"

cd ${TARGETDIR}

for i in ${DATADIR}/*-config-schema.json; do
    printf "%s:\n" "`basename $i`"
    ${SCRIPTDIR}/generate-resoure-descriptions.py -d $i
done
