#!/bin/bash
set -e
set -o pipefail
set -u

#shellcheck source=../environment.in
. ./environment
#shellcheck source=../scripts/functions
. "${rscripts}"/functions

export TestName="$(get_test_name "$0")"

"${rscripts}"/cleanup
"${rscripts}"/setup

# Fill ${BackupDirectory} with data.
setup_data

# Create a list of paths to backup,
# containing only simple file types.
echo "${BackupDirectory}/build" >"$tmp/file-list-simple"

bin/bareos start
bin/bareos status

print_debug "$(bin/bconsole <<< "status dir")"
