#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2024-2025 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

#CTEST requires=create-backup

set -e
set -o pipefail
set -u
#
# Run a simple backup
#
TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd
Volume=TestVolume001
Storage=FileStorage

#shellcheck source=../../environment.in
. ./environment

#shellcheck source=../../scripts/functions
. "${BAREOS_SCRIPTS_DIR}"/functions
#shellcheck source=functions
. functions

start_test

for blocksize in 1 4 16 32 128; do
  run_bdedupestimate -b ${blocksize}k -v -V "${Volume}" "${Storage}"

  mv "${tmp}/bdedupestimate.out" "${runner_tmp}/dedup-${blocksize}.out"
  expect_grep "Using block size ${blocksize} k" \
    "${runner_tmp}/dedup-${blocksize}.out" \
    "Bad block size was used"

  expect_grep "Using device: \"${Storage}\" for reading" \
    "${runner_tmp}/dedup-${blocksize}.out" \
    "Wrong device was used for reading."

  expect_not_grep "Dedup factor: x1.00" \
    "${runner_tmp}/dedup-${blocksize}.out" \
    "Found bad dedup estimation"
done

end_test
