#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2017-2017 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.


for db in sqlite postgresql mysql; do
   DB=`echo $db | tr "a-z" "A-Z"`
   >&2 echo -n "creating ${db}_queries.c for $querycount queries..."
   # everything goes to ${db}_queries.c
   exec > ../${db}_queries.c
   d=`date '+%F %T'`
   echo "/* autogenerated file by $0 on $d */"
   echo "#define SQL(...) #__VA_ARGS__"
   echo "const char *B_DB_${DB}::queries [] = {"

   for query in `ls ????_* | sed 's#\..*##g'  | sort | uniq`; do
      queryname=`echo $query | cut -b 6-`
      echo "SQL("
      if  [ -e "$query.$db" ]; then
         cat $query.$db
      else
         cat $query
      fi
      echo "),"
   done
   echo "NULL };"

d=`date '+%F %T'`
echo



echo "const char *B_DB_${DB}::query_names [] = {"
for query in `ls ????_* | sed 's#\..*##g'  | sort | uniq`; do
   queryname=`echo $query | cut -b 6-`
   echo "\"$queryname\","
done
echo "NULL };"

>&2 echo "done"

done
