<?php

$title = 'Administration';
$this->headTitle($title);

?>

<h2><?php echo $title; ?></h2>
<hr />

<div class="row">

  <div class="col-md-2">

	  <div class="panel panel-default">
	  
	      <div class="panel-heading">
		  <h3 class="panel-title"><?php echo $this->translate('Administration'); ?></h3>
	      </div>
    
	      <div class="panel-body">
	      
	      <table class="table table-striped table-hover">
		<tr><td><a href="<?php echo $this->url('admin', array('action'=>'roles')); ?>"><?php echo $this->translate('Roles'); ?></a></td></tr>
		<tr><td><a href="<?php echo $this->url('admin', array('action'=>'users')); ?>"><?php echo $this->translate('Users'); ?></a></td></tr>
	      </table>
	      
	      </div>
	      
	  </div>
	  
  </div>

  <div class="col-md-10">
  
  </div>

</div>

