<?php

$title = 'User Administration';
$this->headTitle($title);

?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<ul class="nav nav-tabs">
	<li><a href="<?php echo $this->url('admin', array('action'=>'index')); ?>"><?php echo $this->translate('Overview'); ?></a></li>
	<li><a href="<?php echo $this->url('admin', array('action'=>'roles')); ?>"><?php echo $this->translate('Roles'); ?></a></li>
	<li class="active"><a href="<?php echo $this->url('admin', array('action'=>'users')); ?>"><?php echo $this->translate('Users'); ?></a></li>
</ul>

<br />