 Bareosdir_API[Bareosdir_PyParsePluginDefinition_NUM] = (void*)PyParsePluginDefinition;
 Bareosdir_API[Bareosdir_PyGetPluginValue_NUM] = (void*)PyGetPluginValue;
 Bareosdir_API[Bareosdir_PySetPluginValue_NUM] = (void*)PySetPluginValue;
 Bareosdir_API[Bareosdir_PyHandlePluginEvent_NUM] = (void*)PyHandlePluginEvent;
 Bareosdir_API[Bareosdir_set_bareos_core_functions_NUM] = (void*)set_bareos_core_functions;
 Bareosdir_API[Bareosdir_set_plugin_context_NUM] = (void*)set_plugin_context;
