
#   Dumb little AWK program to convert random decimal
#   values generated by rand.bc into passwords from the
#   character set defined below as "charset".

BEGIN {
    charset = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
    for (i = 0; i < length(charset); i++) {
    	set[i] = substr(charset, i, 1)
    }
}
    { printf "%s", set[$1 % length(charset)] }
    
END { printf "\n" }
