#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2026-2026 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

set -e
set -o pipefail
set -u

#
# make sure we can restore an incremental backup
#

TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../../environment.in
. ./environment

#shellcheck source=../../scripts/functions
. "${BAREOS_SCRIPTS_DIR}"/functions
start_test

# remove files
rm -rf "${NDMP_FILESYSTEM}"

cat <<END_OF_DATA >"${tmp}/bconcmds"
@$out ${log_home}/restore.out
restore select jobid=2 client=${NDMPCLIENT} fileset=ndmp-fileset restorejob=NDMPRestoreDump
mark ${NDMP_FILESYSTEM}/incremental
done
yes
wait
messages
END_OF_DATA

run_bconsole "${tmp}/bconcmds"

check_log "${log_home}/restore.out"
expect_grep "Termination:.*Restore OK" "${log_home}/restore.out" \
  "restore did not succeed"

[ "$(cat "${NDMP_FILESYSTEM}/incremental")" = "incremental-1" ] \
  || set_error "wrong content of the restored incremental file"
expect_grep "Recovering the NDMP image of JobId 2" "${log_home}/restore.out" \
  "the image of the incremental job was not recovered"
expect_not_grep "Recovering the NDMP image of JobId 1" \
  "${log_home}/restore.out" "the image of the full job was recovered"

check_no_running_jobs

end_test
