#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2024-2025 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

# TODO: this is independent and should work with CTEST: nolock, but the SD 
#       seems to crash when setting it.

set -e
set -o pipefail
set -u
#
# restore some a directory from archives
#
TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../../environment.in
. ./environment

#shellcheck source=../../scripts/functions
. "${BAREOS_SCRIPTS_DIR}"/functions
#shellcheck source=functions
. functions

# cleanup log
: >"${runner_tmp}/log1.out"

start_test

run_bconsole - <<END_OF_DATA
@$out ${runner_tmp}/log1.out
status storage=Dedup
label volume=PurgeTruncateVol pool=Incremental
purge volume=PurgeTruncateVol
truncate volstatus=Purged volume=PurgeTruncateVol
update volstatus=Full volume=PurgeTruncateVol
status storage=Dedup
quit
END_OF_DATA

expect_grep "3000 OK label" \
  "${runner_tmp}/log1.out" \
  "Volume labeling failed."

expect_not_grep "Error" \
  "${runner_tmp}/log1.out" \
  "Something went wrong."

end_test
