.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BAREOS\-DIR 8 "6 December 2009" "Kern Sibbald" "Backup Archiving REcovery Open Sourced"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
.B bareos\-dir
\- Bareos Director
.SH SYNOPSIS
.B bareos\-dir
.RI [ options ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B bareos\-dir
command.
.br
Bareos's Director Daemon acts as the controller of the
network backup system: it is responsible for scheduling and
coordinating backups across the network.
.SH OPTIONS
.TP
.BI \-c,--config\  path
Specify the configuration file or directory to use.
.TP
.BI \-d,--debug-level\  nn
Set debug level to \fInn\fP.
.TP
.BI \--dt,--debug-timestamps
Print timestamp in debug output.
.TP
.BI \-f,--foreground
Run in foreground (for debugging).
.TP
.BI \-g,--group\  group
Set the group/gid to run as.
.TP
.BI \-m,--print-kaboom
Print kaboom output (for debugging).
.TP
.BI \-p,--pid-file\  file
Specify the full path to the pidfile.
.TP
.BI \-r,--run-job\  job
Run <job>.
.TP
.BI \-s,--no-signals
No signals (for debugging).
.TP
.BI \-t,--test-config
Test the configuration and report errors.
.TP
.BI \-u,--user\  user
Set the username/uid to run as.
.TP
.BI \-v,--verbose
Set verbose mode.
.TP
.BI \--xc,--export-config\ [<resource_type> [<name>]]
Print all or specific configuration resources and exit.
.TP
.BI \--xs,--export-schema
Print configuration schema in JSON format and exit.
.TP
.BI \-h,--help,-?
Show version and usage of program.
.SH SEE ALSO
.BR bareos-fd (8),
.BR bareos-sd (8).

.SH AUTHOR
This manual page was written by Jose Luis Tallon
.nh
<jltallon@adv\-solutions.net>.
