.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BAREOS\-SD 8 "6 December 2009" "Kern Sibbald" "Backup Archiving REcovery Open Sourced"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
.B bareos\-sd
\- Bareos's Storage Daemon
.SH SYNOPSIS
.B bareos\-sd
.RI [ options ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B bareos\-sd
command.
.br
Bareos's Storage Daemon acts as the interface between the Bareos
network backup system and a tape drive/autochanger or filesystem where
the backups will be stored.
.SH OPTIONS
.TP
.BI \-c\   path
Specify the configuration file or directory to use.
.TP
.BI \-d\  nn
Set debug level to \fInn\fP.
.TP
.BI \-dt
Print timestamp in debug output.
.TP
.BI \-f
Run in foreground (for debugging).
.TP
.BI \-g\  group
Set the group/gid to run as.
.TP
.BI \-p
Proceed in spite of I/O errors
.TP
.BI \-m
Print kaboom output (for debugging)
.TP
.BI \-s
No signals (for debugging).
.TP
.B \-t
Test the configuration file and report errors.
.TP
.BI \-u\  user
Set the username/uid to run as.
.TP
.BI \-v
Set verbose mode.
.TP
.B \-?
Show version and usage of program.
.SH SEE ALSO
.BR bareos\-dir (8),
.BR bareos\-fd (8).
.br
.SH AUTHOR
This manual page was written by Jose Luis Tallon
.nh
<jltallon@adv\-solutions.net>.
