#!/bin/sh

. ./environment


rm -rf ${tmp}/*
rm -rf ${logdir}/*.log
rm -rf ${working}/*.bsr ${working}/log*.sd
rm -rf ${working}/*.trace ${working}/*.traceback ${working}/*.bactrace
rm -rf ${working}/*.state
rm -rf ${working}/*.conmsg
rm -rf ${working}/*.pid
rm -rf ${working}/*.mail
rm -rf ${working}/CLEANUPMARKER
rm -rf ${working}/plugins/*
rm -rf ${archivedir}/*
find . -name "gigaslam.gif" -exec rm -f {} \;
# cleanup old config files
# don't delete mtx-changer.conf (and other files?)
#rm -f  ${conf}/*.cert
#rm -f  ${conf}/bareos*.conf
#rm -f  ${conf}/bconsole*.conf
#rm -rf ${conf}/*.d/
#rm -f  ${conf}/*.pem
#rm -rf ${conf}/bareos-dir-export/
#rm -rf ${conf}/tls/

# cleanup chrome user data (selenium tests)
rm -rf /tmp/chrome-user-data-*

#if [ -f ${scripts}/bareos ]; then
#  ${scripts}/bareos stop 2>&1 >/dev/null
#fi
${cats}/drop_bareos_tables ${DBTYPE} >/dev/null 2>&1
echo "creating database (${DBTYPE})"
${cats}/create_bareos_tables ${DBTYPE} >/dev/null 2>&1
${cats}/make_bareos_tables ${DBTYPE} >/dev/null 2>&1
${cats}/grant_bareos_privileges ${DBTYPE} >/dev/null 2>&1
