#!/bin/sh
#shellcheck source=../environment.in
. ./environment

# reset dbdriver in case we're rerunning the test with another driver
sed \
  -i \
  -e 's/dbdriver =.*/dbdriver = XXX_REPLACE_WITH_DATABASE_DRIVER_XXX/' \
  etc/bareos/bareos-dir.d/catalog/*.conf 2>/dev/null

${scripts}/bareos-config initialize_database_driver
. ${rscripts}/functions

print_debug "drop database \"${db_name}\" (${DBTYPE})"
${scripts}/drop_bareos_database ${DBTYPE} >/dev/null 2>&1

print_debug "creating database \"${db_name}\" (${DBTYPE})"
${scripts}/create_bareos_database ${DBTYPE} >/dev/null 2>&1
${scripts}/make_bareos_tables ${DBTYPE} >/dev/null 2>&1
${scripts}/grant_bareos_privileges ${DBTYPE} >/dev/null 2>&1

exit 0
