#!/bin/bash
set -e
set -o pipefail
set -u
#
# check that "maximum concurrent jobs" on the Storage resource works correctly.
# for details, see test-concurrency-common
#
TestName="$(basename "$(pwd)")"
export TestName

JobName=test-storage-concurrency
want_w_storage=2

. test-concurrency-common
