#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2023-2025 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

#
# Provoke a fatal error during a restore and check that the right
# termination text is displayed.
# The error is provoked by temporarily renaming the volume.
#

#CTEST requires=create-backup

set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../../environment.in
. ./environment

#shellcheck source=../../scripts/functions
. "${BAREOS_SCRIPTS_DIR}"/functions
#shellcheck source=functions
. functions

start_test

# we must ensure that the restore directory exists before we try to make it
# read only.

mv storage/TestVolume001{,.c}

cat <<END_OF_DATA >"$tmp/bconcmds"
@$out ${NULL_DEV}
messages
@$out ${runner_tmp}/setup.out
setdebug level=100 storage=File
status director
status client
status storage=File
wait
messages
@$out ${runner_tmp}/jobs.out
list jobs
@$out ${runner_tmp}/should-hang.out
restore client=bareos-fd fileset=SelfTest where=$tmp/bareos-restores select all done yes
@sleep 6
messages
quit
END_OF_DATA

run_bconsole

bin/bareos restart

cat <<END_OF_DATA >"$tmp/bconcmds"
@$out ${runner_tmp}/should-show-error.out
wait
messages
quit
END_OF_DATA

run_bconsole
check_for_zombie_jobs storage=File

check_preconditions

expect_grep "Termination:.*Restore Error" \
  "${runner_tmp}/should-show-error.out" \
  "Restore of job in removed volume was not set as failed!"

mv storage/TestVolume001{.c,}

end_test
