#!/bin/sh
#
# Configure the dart files
#
. scripts/functions

out="${tmp}/sed_tmp"

scripts/create_sed

sed -f ${out} ${cwd}/DartConfiguration.tcl.in >${cwd}/DartConfiguration.tcl
sed -f ${out} ${cwd}/DartTestfile.txt.in >${cwd}/DartTestfile.txt

sed -f ${out} ${rscripts}/update-ctest.in >${rscripts}/update-ctest
chmod +x ${rscripts}/update-ctest

