#!/bin/sh

set -e
set -u

/bin/cp -f scripts/bareos-dir-2client.conf ${conf}/bareos-dir.conf
/bin/cp -f scripts/bareos-sd-2disk-drive.conf ${conf}/bareos-sd.conf
/bin/cp -f scripts/test-bareos-fd.conf ${conf}/bareos-fd.conf
/bin/cp -f scripts/test-console.conf ${conf}/bconsole.conf

outf="tmp/sed_tmp"
echo "s%# Autochanger = yes%  Autochanger = yes%g" >${outf}
cp bin/bareos-dir.conf tmp/1
sed -f ${outf} tmp/1 >${conf}/bareos-dir.conf
