#!/bin/sh
/bin/cp -f scripts/bareos-dir-fifo.conf bin/bareos-dir.conf
/bin/cp -f scripts/bareos-sd-fifo.conf bin/bareos-sd.conf
/bin/cp -f scripts/test-bareos-fd.conf bin/bareos-fd.conf
/bin/cp -f scripts/test-console.conf bin/bconsole.conf

scripts/set_tape_options
