#!/bin/sh
/bin/cp -f ${rscripts}/bareos-dir-tape.conf ${conf}/bareos-dir.conf
/bin/cp -f ${rscripts}/bareos-sd-btape.conf ${conf}/bareos-sd.conf
/bin/cp -f ${rscripts}/test-bareos-fd.conf ${conf}/bareos-fd.conf
/bin/cp -f ${rscripts}/test-console.conf ${conf}/bconsole.conf

${rscripts}/set_tape_options
