#!/bin/sh
/bin/cp -f ${rscripts}/new-test-bareos-dir.conf ${conf}/bareos-dir.conf
/bin/cp -f ${rscripts}/test-bareos-sd.conf ${conf}/bareos-sd.conf
/bin/cp -f ${rscripts}/test-bareos-fd.conf ${conf}/bareos-fd.conf
/bin/cp -f ${rscripts}/test-console.conf ${conf}/bconsole.conf

${rscripts}/set_tape_options
