#!/bin/sh

set -e
set -u

/bin/cp -f scripts/new-test-bareos-dir.conf bin/bareos-dir.conf
/bin/cp -f scripts/test-bareos-sd.conf bin/bareos-sd.conf
/bin/cp -f scripts/crypto-bareos-fd.conf bin/bareos-fd.conf
/bin/cp -f scripts/test-console.conf bin/bconsole.conf
/bin/cp -f scripts/cryptokeypair.pem bin/cryptokeypair.pem
/bin/cp -f scripts/master2048.cert bin/master2048.cert
