#!/bin/sh
#
cwd=`pwd`
. scripts/functions
mkdir -p ${bin}
out="${tmp}/sed_tmp"

${rscripts}/create_sed

# Process .in files with sed script
for file in ${cwd}/*.in \
            ${rscripts}/*.in \
            ${rconfigs}/*/*.in \
            ${rconfigs}/*/*/*/*.in
do
  sed -f ${out} ${file} > `echo "${file}" | sed -e 's/.in$//'`
done

chmod 755 ${rscripts}/regress-config
chmod 755 ${rscripts}/cleanup-*tape ${rscripts}/cleanup-*drive ${rscripts}/prepare-two-tapes
chmod 755 ${rscripts}/diff.pl
${rscripts}/set_tape_options
${rscripts}/config_dart

