#!/bin/bash
set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions
"${rscripts}"/cleanup
"${rscripts}"/setup

setup_data

start_test

# 1) Create a full backup with LZ4 compression (as per SelfTest fileset config)
# 2) Copy full backup to other pool and decompress (as per FileStorage2 device config)
# 3) Restore copied job
cat <<END_OF_DATA >"$tmp/bconcmds"
@$out /dev/null
messages
label volume=TestVolume001 storage=File pool=Full
run job=backup-bareos-fd level=Full yes
wait
update volume=TestVolume001 volstatus=Used
messages
label volume=TestCopyVolume001 storage=File2 pool=FullCopy
run copy yes
wait
messages
restore jobid=4 client=bareos-fd where=$tmp/bareos-restores all done yes
wait
messages
quit
END_OF_DATA

run_bareos "$@"

# There should be no difference, but with autoxflate decompression
# the restore reports success ("Restore OK") but seems to fail silently
# and doesn't actually restore anything
check_restore_diff "${BackupDirectory}"

end_test
