#!/bin/bash
#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2023-2023 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

debug_level=500
File="bbatch.c"

start_test

# 1) Create a full backup with LZ4 compression (as per SelfTest fileset config)
# 2) Copy full backup to other pool and decompress (as per FileStorage2 device config)
# 3) Restore copied job
cat <<END_OF_DATA >"$tmp/bconcmds"
@$out ${tmp}/backup.out
messages
label volume=TestVolume001 storage=L1 pool=Full
run job=backup-bareos-fd level=Full yes
wait
update volume=TestVolume001 volstatus=Used
messages
@$out ${tmp}/copy.out
label volume=TestCopyVolume001 storage=L2 pool=FullCopy
setdebug level=$debug_level storage=L1
setdebug level=$debug_level storage=L2
run copy-local yes
wait
update volume=TestCopyVolume001 volstatus=Used
setdebug level=0 storage=L1
setdebug level=0 storage=L2
messages
@$out ${tmp}/restore.out
restore jobid=4 client=bareos-fd where=$tmp/bareos-restores all done yes
wait
messages
quit
END_OF_DATA

run_bconsole "$@"

# There should be no difference
check_restore_diff "${BackupDirectory}"

if ! is_file_compressed "LD1" "TestVolume001" "${File}"; then
    echo "TestVolume001 is not compressed"
    estat=3
fi
if is_file_compressed "LD2" "TestCopyVolume001" "${File}"; then
    echo "TestCopyVolume001 is not uncompressed"
    estat=4
fi

end_test
