<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos for the canonical source repository
 * @copyright Copyright (C) 2013-2023 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = _('Client details');
$this->headTitle($title);

?>

<ul class="nav nav-tabs">
   <li class="active"><a href="<?php echo $this->url('client', array('action'=>'index')); ?>"><?php echo $this->translate('Show'); ?></a></li>
   <li><a href="<?php echo $this->url('client', array('action'=>'timeline')); ?>"><?php echo $this->translate('Timeline'); ?></a></li>
</ul>

<br />

<?php if($this->acl_alert) : echo $this->ACLAlert($this->invalid_commands); elseif(!$this->acl_alert) : ?>

<div class="row">

<div class="col-md-12">
<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title"><?php echo $this->translate("Client"); ?></h3>
</div>

<div class="panel-body">

<table class="table table-no-bordered table-hover" id="clientdetails">
<thead class="bg-primary">
   <th><?php echo $this->translate("Name"); ?></th>
   <th><?php echo $this->translate("Version"); ?></th>
   <th><?php echo $this->translate("Autoprune"); ?></th>
   <th><?php echo $this->translate("Fileretention"); ?></th>
   <th><?php echo $this->translate("Jobretention"); ?></th>
   <th><?php echo $this->translate("Actions"); ?></th>
</thead>
</table>

</div>
</div>
</div>
</div>

<div class="row">
<div class="col-md-12">

<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title"><?php echo $this->translate("Job list"); ?></h3>
</div>

<div class="panel-body">

<table
   class="table table-no-bordered table-hover"
   id="clientbackups"
   data-filter-control="true">

<thead class="bg-primary">
   <th
      data-filed="jobid"
      data-width="200"
      data-filter-control="input"
      data-filter-control-placeholder="<?php echo $this->translate("Job ID"); ?>">
      <?php echo $this->translate("Job ID"); ?>
   </th>
   <th
      data-field="name"
      data-filter-control="input"
      data-filter-control-placeholder="<?php echo $this->translate("Job name"); ?>">
      <?php echo $this->translate("Job name"); ?>
   </th>
   <th
      data-field="starttime"
      data-width="200"
      data-filter-control="input"
      data-filter-control-placeholder="<?php echo $this->translate("Start"); ?>">
      <?php echo $this->translate("Start"); ?>
   </th>
   <th
      data-field="endtime"
      data-width="200"
      data-filter-control="input"
      data-filter-control-placeholder="<?php echo $this->translate("End"); ?>">
      <?php echo $this->translate("End"); ?>
   </th>
   <th
      data-field="duration"
      data-width="100"
      data-filter-control="input"
      data-filter-control-placeholder="<?php echo $this->translate("Duration"); ?>">
      <?php echo $this->translate("Duration"); ?>
   </th>
   <th
      data-field="rate"
      data-width="100"
      data-filter-control="input"
      data-filter-control-placeholder="<?php echo $this->translate("Rate"); ?>">
      <?php echo $this->translate("Rate"); ?>
   </th>
   <th
      data-field="fileset"
      data-filter-control="input"
      data-filter-control-placeholder="<?php echo $this->translate("Fileset"); ?>">
      <?php echo $this->translate("Fileset"); ?>
   </th>
   <th
      data-field="level"
      data-width="50"
      data-filter-control="input"
      data-filter-control-placeholder="<?php echo $this->translate("Level"); ?>">
      <?php echo $this->translate("Level"); ?>
   </th>
   <th
      data-field="jobfiles"
      data-width="100"
      data-filter-control="input"
      data-filter-control-placeholder="<?php echo $this->translate("Files"); ?>">
      <?php echo $this->translate("Files"); ?>
   </th>
   <th
      data-field="jobbytes"
      data-width="100"
      data-filter-control="input"
      data-filter-control-placeholder="<?php echo $this->translate("Bytes"); ?>">
      <?php echo $this->translate("Bytes"); ?>
   </th>
   <th
      data-field="jobstatus"
      data-width="200"
      data-filter-control="input"
      data-filter-control-placeholder="<?php echo $this->translate("Status"); ?>">
      <?php echo $this->translate("Status"); ?>
   </th>
   <th
      data-width="100">
      <?php echo $this->translate("Actions"); ?>
   </th>
</thead>
</table>

</div>
</div>
</div>
</div>

<?php
   echo $this->headScript()->prependFile($this->basePath() . '/js/custom-functions.js');
   echo $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-table-filter-control.min.css');
   echo $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-table.min.css');
   echo $this->headScript()->prependFile($this->basePath() . '/js/bootstrap-table-formatter.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/bootstrap-table-filter-control.min.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/bootstrap-table-locale-all.min.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/bootstrap-table-cookie.min.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/bootstrap-table.min.js');
?>

<script>

   var basePath = "<?php echo $this->basePath(); ?>";

   function attachClientDetails() {
      $('#clientdetails').bootstrapTable({
         locale: '<?php echo str_replace('_','-', $_SESSION['bareos']['locale']); ?>',
         cookie: <?php echo $_SESSION['bareos']['dt_statesave']; ?>,
         cookieIdTable: 'dashboard_table_jobs_last_status',
         url: '<?php echo $this->url('api/client', array(), array("query" => array("client" => $this->client))); ?>',
         method: 'get',
         dataType: 'json',
         columns: [
            {
               field: 'name',
            },
            {
               field: 'uname',
            },
            {
               field: 'autoprune',
               formatter: function(value) {
                  return formatAutoprune(value);
               }
            },
            {
               field: 'fileretention',
               formatter: function(value) {
                  return formatRetention(value);
               }
            },
            {
               field: 'jobretention',
               formatter: function(value) {
                  return formatRetention(value);
               }
            },
            {
               field: 'action',
               formatter: function(value, row, index) {
                  return clientActionButtonsFormatter(value, row, index, basePath);
               }
            }
         ]
      });
   }

   function attachClientBackups() {
      $('#clientbackups').bootstrapTable({
         locale: '<?php echo str_replace('_','-', $_SESSION['bareos']['locale']); ?>',
         cookie: <?php echo $_SESSION['bareos']['dt_statesave']; ?>,
         cookieIdTable: 'client_clientbackups',
         url: '<?php echo $this->url('api/job', array(), array("query" => array("client" => $this->client))); ?>',
         method: 'get',
         dataType: 'json',
         pagination : true,
         sidePagination: 'client',
         pageList: [ <?php echo $_SESSION['bareos']['dt_lengthmenu']; ?> ],
         pageSize: <?php echo $_SESSION['bareos']['dt_pagelength']; ?>,
         search: false,
         showPaginationSwitch: true,
         showColumns: true,
         showRefresh: true,
         sortName: 'jobid',
         sortOrder: 'desc',
         columns: [
            {
               field: 'jobid',
               sortable: true,
               formatter: function(value) {
                  return formatJobId(value, basePath);
               }
            },
            {
               field: 'name',
               sortable: true,
               formatter: function(value) {
                  return formatJobName(value, basePath);
               }
            },
            {
               field: 'starttime',
               sortable: true,
            },
            {
               field: 'endtime',
               sortable: true,
            },
            {
               field: 'duration',
               sortable: true,
            },
            {
               field: 'rate',
               sortable: true,
            },
            {
               field: 'fileset',
               sortable: true,
               formatter: function(value, row, index) {
                  return formatFilesetName(value, row, index, basePath);
               }
            },
            {
               field: 'level',
               sortable: true,
               formatter: function(value) {
                  return formatJobLevel(value);
               }
            },
            {
               field: 'jobfiles',
               sortable: true,
            },
            {
               field: 'jobbytes',
               sortable: true,
               formatter: function(value) {
                  return formatBytes(value);
               }
            },
            {
               field: 'jobstatus',
               sortable: false,
               formatter: function(value) {
                  return formatJobStatus(value);
               }
            },
            {
               field: 'action',
               formatter: function(value, row, index) {
                  return jobActionButtonsFormatter(value, row, index, basePath);
               }
            }
         ]
      });
   }

   $(document).ready(function() {
      setDtTextDomain('<?php echo $this->basePath() . '/js/locale'; ?>');
      setDtLocale('<?php echo $_SESSION['bareos']['locale']; ?>');
      attachClientDetails();
      attachClientBackups();
   });

</script>

<?php endif; ?>
