<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos for the canonical source repository
 * @copyright Copyright (c) 2013-2023 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = _('Clients');
$this->headTitle($title);

?>

<ul class="nav nav-tabs">
   <li class="active"><a href="<?php echo $this->url('client', array('action'=>'index')); ?>"><?php echo $this->translate('Show'); ?></a></li>
   <li><a href="<?php echo $this->url('client', array('action'=>'timeline')); ?>"><?php echo $this->translate('Timeline'); ?></a></li>
</ul>

<br />

<?php if($this->acl_alert) : echo $this->ACLAlert($this->invalid_commands); elseif(!$this->acl_alert) : ?>

<div class="row">

<div class="col-md-8">
<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title"><?php echo $this->translate('Clients'); ?></h3>
</div>

<div class="panel-body">

<table
   class="table table-no-bordered table-hover"
   id="clients"
   data-filter-control="true">

<thead class="bg-primary">
   <th
      data-field="name"
      data-filter-control="input"
      data-filter-control-placeholder="<?php echo $this->translate("Name"); ?>">
      <?php echo $this->translate("Name"); ?>
   </th>
   <th
      data-field="uname"
      data-filter-control="input"
      data-filter-control-placeholder="<?php echo $this->translate("OS"); ?>">
      <?php echo $this->translate("OS"); ?>
   </th>
   <th
      data-field="version"
      data-filter-control="input"
      data-filter-control-placeholder="<?php echo $this->translate("Version"); ?>">
      <?php echo $this->translate("Version"); ?>
   </th>
   <th
      data-field="enabled"
      data-filter-control="input"
      data-filter-control-placeholder="<?php echo $this->translate("Status"); ?>">
      <?php echo $this->translate("Status"); ?>
   </th>
   <th>
      <?php echo $this->translate("Actions"); ?>
   </th>
</thead>

</table>

</div>
</div>
</div>
</div>

<?php
   echo $this->headScript()->prependFile($this->basePath() . '/js/custom-functions.js');
   echo $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-table-filter-control.min.css');
   echo $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-table.min.css');
   echo $this->headScript()->prependFile($this->basePath() . '/js/bootstrap-table-sort.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/bootstrap-table-formatter.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/bootstrap-table-filter-control.min.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/bootstrap-table-locale-all.min.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/bootstrap-table-cookie.min.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/bootstrap-table.min.js');
?>

<!-- modal-001 start -->
<div id="modal-001" class="modal fade modal-001" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
         </button>
         <h4 class="modal-title" id="myModalLabel">Client status</h4>
      </div>
      <div class="modal-body">
         <p><?php echo str_replace(array("\n","\r"), "<br />", $this->result); ?></p>
      </div>
      <div class="modal-footer">
         <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate("Close"); ?></button>
      </div>
    </div>
  </div>
</div>
<!-- modal-001 end -->

<script>

   var basePath = "<?php echo $this->basePath(); ?>";
   var result = '<?php echo str_replace(array("\n","\r"), "", $this->result); ?>';

   function attachClientsTable() {
      $('#clients').bootstrapTable({
         locale: '<?php echo str_replace('_','-', $_SESSION['bareos']['locale']); ?>',
         cookie: <?php echo $_SESSION['bareos']['dt_statesave']; ?>,
         cookieIdTable: 'client_clients',
         url: '<?php echo $this->url('client', array('action' => 'getData'), null) . '?data=all'; ?>',
         method: 'get',
         dataType: 'json',
         pagination : true,
         sidePagination: 'client',
         pageList: [ <?php echo $_SESSION['bareos']['dt_lengthmenu']; ?> ],
         pageSize: <?php echo $_SESSION['bareos']['dt_pagelength']; ?>,
         search: false,
         showPaginationSwitch: true,
         showRefresh: true,
         sortName: 'name',
         sortOrder: 'asc',
         columns: [
            {
               field: 'name',
               sortable: true,
               formatter: function(value) {
                  return formatClientName(value, basePath);
               }
            },
            {
               field: 'uname',
               sortable: true,
               formatter: function(value) {
                  return formatUname(value, basePath);
               }
            },
            {
               field: 'version',
               sortable: true,
               sorter: sortSemanticVersion,
            },
            {
               field: 'enabled',
               sortable: true,
               formatter: function(value) {
                  return formatEnabledDisabledStatus(value);
               }
            },
            {
               field: 'actions',
               formatter: function(value, row, index) {
                  return clientsActionButtonsFormatter(value, row, index, basePath);
               }
            }
         ]
      });
   }

   $(document).ready(function() {

      setDtTextDomain('<?php echo $this->basePath() . '/js/locale'; ?>');
      setDtLocale('<?php echo $_SESSION['bareos']['locale']; ?>');

      if(result.length > 0) {
         $("#modal-001").modal();
      }

      attachClientsTable();

   });

</script>

<?php endif; ?>
