<?php

$title = 'Client Status';
$this->headTitle($title);

?>

<ul class="nav nav-tabs">
   <li class="active"><a href="<?php echo $this->url('client', array('action'=>'index')); ?>"><?php echo $this->translate('Show'); ?></a></li>
</ul>

<br />

<div class="row">
<div class="col-md-8">

<div class="panel panel-default">

<div class="panel-heading">
   <h3 class="panel-title"><?php echo $this->translate("Client Status"); ?></h3>
</div>

<div class="panel-body">
<pre class="dird-messages" style="height: 500px; font-size: 8pt;">
<code>
<?php echo $this->result; ?>
</code>
</pre>
</div>

</div>
</div>
