 Bareossd_API[Bareossd_PyParsePluginDefinition_NUM] = (void*)PyParsePluginDefinition;
 Bareossd_API[Bareossd_PyGetPluginValue_NUM] = (void*)PyGetPluginValue;
 Bareossd_API[Bareossd_PySetPluginValue_NUM] = (void*)PySetPluginValue;
 Bareossd_API[Bareossd_PyHandlePluginEvent_NUM] = (void*)PyHandlePluginEvent;
 Bareossd_API[Bareossd_set_bareos_core_functions_NUM] = (void*)set_bareos_core_functions;
 Bareossd_API[Bareossd_set_plugin_context_NUM] = (void*)set_plugin_context;
