#!/bin/sh
#
# Test the fill command in btape
#
TestName="btape-fill-tape"
JobName=filltape
. scripts/functions
set_debug 0

copy_tape_confs

echo "${cwd}/build" >${cwd}/tmp/file-list

cp ${cwd}/bin/bareos-sd.conf ${cwd}/tmp/1
sed "s%# MaximumVolumeSize%  MaximumVolumeSize%" ${cwd}/tmp/1 >${cwd}/bin/bareos-sd.conf

start_test

cat <<END_OF_DATA >tmp/bconcmds
fill
s
quit
END_OF_DATA

run_btape DDS-4

grep "^The last block on the tape matches\. Test succeeded\." tmp/log1.out 2>&1 >/dev/null
if [ $? != 0 ] ; then
   echo " "
   echo " "
   echo "  !!!!! btape fill test failed!!! !!!!! "
   echo "  !!!!! btape fill test failed!!! !!!!! " >>test.out
   echo " "
else
   echo "  ===== btape fill test OK ===== "
   echo "  ===== btape fill test OK ===== " >>test.out
#  scripts/cleanup
fi
