#!/bin/sh
#
# Test the fill command in btape
#
TestName="btape-fill-full-tape"
JobName=AutoLabel
. scripts/functions
set_debug 0

scripts/copy-tape-confs
scripts/cleanup-tape

change_jobname $JobName
start_test

bin/btape -c bin/bareos-sd.conf DDS-4 <<END_OF_DATA 2>&1 >tmp/log1.out
fill
s

quit
END_OF_DATA


grep "^The last block on the tape matches\. Test succeeded\." tmp/log1.out 2>&1 >/dev/null
if [ $? != 0 ] ; then
   echo " "
   echo " "
   echo "  !!!!! btape fill test failed!!! !!!!! "
   echo "  !!!!! btape fill test failed!!! !!!!! " >>test.out
   echo " "
else
   echo "  ===== btape fill test OK ===== "
   echo "  ===== btape fill test OK ===== " >>test.out
#  scripts/cleanup
fi
