#!/bin/sh
#
# Run four jobs at the same time
#
TestName="four-concurrent-jobs-tape"
JobName=FourConcurrentJobs
. scripts/functions
set_debug 0

scripts/cleanup-tape
scripts/copy-tape-confs

echo "${cwd}/build" >${cwd}/tmp/file-list

change_jobname $JobName
start_test

cat <<END_OF_DATA >tmp/bconcmds
@output /dev/null
messages
@$out tmp/log1.out
label storage=DDS-4 volume=TestVolume001 slot=0 pool=Default
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
@sleep 2
status dir
@sleep 5
status dir
status storage=DDS-4
messages
wait
messages
@#
@# now do a restore
@#
@$out tmp/log2.out
restore where=${cwd}/tmp/bareos-restores select storage=DDS-4
unmark *
mark *
done
yes
wait
messages
@$out
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=DDS-4
stop_bareos

check_two_logs
check_restore_diff
end_test
