#!/bin/sh
#
# Run a simple backup of the Bareos build directory using the compressed option
#   then backup four times, each with incremental then finally restore.
#   It should require at least 4 different bsrs.
#
TestName="four-jobs-tape"
JobName=fourjobstape
. scripts/functions
set_debug 0

scripts/cleanup-tape
scripts/copy-tape-confs
echo "${cwd}/build" >${cwd}/tmp/file-list

change_jobname $JobName
start_test

cat <<END_OF_DATA >tmp/bconcmds
@$out /dev/null
estimate job=$JobName listing
estimate job=$JobName listing
estimate job=$JobName listing
messages
@$out tmp/log1.out
label storage=DDS-4 volume=TestVolume001 slot=0 pool=Default
run job=$JobName yes
wait
messages
quit
END_OF_DATA
if test "$debug" -eq 1 ; then
  bin/bareos start
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf
else
  bin/bareos start 2>&1 >/dev/null
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf  2>&1 >/dev/null
fi

scripts/check_for_zombie_jobs storage=DDS-4
echo "Backup 1 done"
# make some files for the incremental to pick up
touch ${cwd}/build/src/dird/*.c ${cwd}/build/src/dird/*.o
touch ${cwd}/build/src/lib/*.c ${cwd}/build/src/lib/*.o

#
# run a second job
#
cat <<END_OF_DATA >tmp/bconcmds
@$out /dev/null
messages
@$out tmp/log1.out
run job=$JobName level=Incremental yes
wait
messages
quit
END_OF_DATA
if test "$debug" -eq 1 ; then
  bin/bareos start
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf
else
  bin/bareos start 2>&1 >/dev/null
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf  2>&1 >/dev/null
fi

scripts/check_for_zombie_jobs storage=DDS-4
echo "Backup 2 done"
touch ${cwd}/build/src/dird/*.c
touch ${cwd}/build/src/lib/*.c ${cwd}/build/src/lib/*.o
#
# run a third job
#
cat <<END_OF_DATA >tmp/bconcmds
@$out /dev/null
messages
@$out tmp/log1.out
run job=$JobName level=Incremental yes
wait
messages
quit
END_OF_DATA
if test "$debug" -eq 1 ; then
  bin/bareos start
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf
else
  bin/bareos start 2>&1 >/dev/null
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf  2>&1 >/dev/null
fi

scripts/check_for_zombie_jobs storage=DDS-4
echo "Backup 3 done"
# make some files for the incremental to pick up
touch ${cwd}/build/src/lib/*.c ${cwd}/build/src/lib/*.o
#
# run a fourth job
#
cat <<END_OF_DATA >tmp/bconcmds
@$out /dev/null
messages
@$out tmp/log1.out
run job=$JobName level=Incremental yes
wait
messages
quit
END_OF_DATA
if test "$debug" -eq 1 ; then
  bin/bareos start
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf
else
  bin/bareos start 2>&1 >/dev/null
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf  2>&1 >/dev/null
fi

scripts/check_for_zombie_jobs storage=DDS-4
echo "Backup 4 done"
#
# now do several restores to ensure we cleanup between jobs
#
cat <<END_OF_DATA >tmp/bconcmds
@$out /dev/null
restore where=${cwd}/tmp/bareos-restores select all done
yes
wait
restore where=${cwd}/tmp/bareos-restores select all done
yes
wait
@$out tmp/log2.out
@#
@# now unmount the tape and start two restores
@#  at the same time
@#
unmount storage=DDS-4
restore where=${cwd}/tmp/bareos-restores select all done
yes
restore where=${cwd}/tmp/bareos-restores select
unmark *
mark *
done
yes
mount storage=DDS-4
wait
messages
@$out
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=DDS-4
stop_bareos

check_two_logs
check_restore_diff
end_test
