#!/bin/sh
#
# Run a simple backup of the /lib directory
#   then restore it.
#
cwd=`pwd`
bin/bareos stop 2>&1 >/dev/null
cd bin
./drop_bareos_tables >/dev/null 2>&1
./make_bareos_tables >/dev/null 2>&1
./grant_bareos_privileges 2>&1 >/dev/null
cd ..

scripts/cleanup-tape
scripts/copy-tape-confs
echo "/lib" >${cwd}/tmp/file-list
echo " "
echo " "
echo " === Starting lib-tape-root test ==="
echo " "
echo " "
bin/bareos start 2>&1 >/dev/null
bin/bconsole -c bin/bconsole.conf <<END_OF_DATA
@output /dev/null
messages
@output tmp/log1.out
label storage=DDS-4 Volume=TestVolume001 slot=0
run job=NightlySave yes
wait
messages
@#
@# now do a restore
@#
@output tmp/log2.out
restore where=${cwd}/tmp/bareos-restores select all done
yes
wait
messages
@output
quit
END_OF_DATA
bin/bareos stop 2>&1 >/dev/null
cd /
${cwd}/bin/testls -e ${cwd}/scripts/exclude-usr-test lib >${cwd}/tmp/original
cd ${cwd}/tmp/bareos-restores
${cwd}/bin/testls -e ${cwd}/scripts/exclude-usr-test lib >${cwd}/tmp/restored
cd ${cwd}/tmp
sed s%.*lib/kbd/consolefonts$%lib/kbd/consolefonts% original >1
sort <1 >original
#
sed s%.*lib/kbd/consolefonts$%lib/kbd/consolefonts% restored >1
sort <1 >restored
rm -f 1
#
cd ${cwd}
diff tmp/original tmp/restored 2>&1 1>/dev/nul
if [ $? != 0 ] ; then
   echo " "
   echo " "
   echo "  ===== lib-tape-root failed!!! ===== "
   echo "  ===== lib-tape-root failed!!! ===== " >>test.out
   echo " "
else
   echo "  ===== lib-tape-root OK ===== "
   echo "  ===== lib-tape-root OK ===== " >>test.out
   scripts/cleanup
fi
