#!/bin/sh
#
# Run a simple backup of the Bareos build directory using the compressed option
#   then backup four times, each with incremental then finally restore.
#   It should require at least 4 different bsrs.
#
TestName="relabel-tape"
JobName=Relabeltape
. scripts/functions
set_debug 0

scripts/cleanup-tape
scripts/copy-tape-confs
echo "${cwd}/build" >${cwd}/tmp/file-list

change_jobname $JobName
start_test

cat <<END_OF_DATA >tmp/bconcmds
@output /dev/null
messages
@$out tmp/log1.out
label storage=DDS-4 volume=TestVolume001 slot=0 pool=Default
run job=$JobName level=Full yes
wait
messages
add pool=Default
0
TestVolume002
@# set status to append
update volume=TestVolume001
1
.
run job=NightlySave level=Full yes
@sleep 20
unmount
unmount
purge volume=TestVolume001
relabel oldvolume=TestVolume001 volume=TestVolume003 slot=0 pool=Default
list volumes
mount
messages
wait
run job=$JobName level=Full yes
wait
messages
@$out
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=DDS-4


echo "Backup done"
#
# now do several restores to ensure we cleanup between jobs
#
cat <<END_OF_DATA >tmp/bconcmds
@$out /dev/null
restore where=${cwd}/tmp/bareos-restores select all done
yes
wait
restore where=${cwd}/tmp/bareos-restores select all done
yes
wait
@$out tmp/log2.out
@#
@# now unmount the tape and start two restores
@#  at the same time
@#
unmount storage=DDS-4
restore where=${cwd}/tmp/bareos-restores select all done
yes
restore where=${cwd}/tmp/bareos-restores select
unmark *
mark *
done
yes
mount storage=DDS-4
wait
messages
@$out
quit
END_OF_DATA

run_bconsole

check_for_zombie_jobs storage=DDS-4
stop_bareos

check_two_logs
check_restore_diff
end_test
