#!/bin/sh
#
# Run a simple backup of the Bareos build directory
#   then verify the catalog.
#
TestName="verify-vol-tape"
JobName=VerifyVol
. scripts/functions
set_debug 0

copy_tape_confs

echo "${cwd}/build" >${cwd}/tmp/file-list

change_jobname NightlySave $JobName
start_test

cat <<END_OF_DATA >tmp/bconcmds
@$out /dev/null
messages
@$out tmp/log1.out
setdebug level=1 storage=DDS-4 sd
label storage=DDS-4 volume=TestVolume001 pool=Default
run job=$JobName yes
wait
messages
@#
@# now do a verify volume
@#
@$out ${cwd}/tmp/original
run job=VerifyTape pool=Default
yes
wait
messages
@$out
quit
END_OF_DATA

run_bareos

sleep 2
check_for_zombie_jobs storage=DDS-4
stop_bareos

grep "^  Termination: *Backup OK" tmp/log1.out 2>&1 >/dev/null
bstat=$?
grep "^  Termination: *Verify OK" ${cwd}/tmp/original 2>&1 >/dev/null
rstat=$?
dstat=0
end_test
