#!/bin/sh
#
# Run a simple backup of the Bareos build directory
#   to a tape then restore it, we do that twice to ensure that
#   we can correctly append to a tape.
#
TestName="win32-backup-tape"
JobName=win32tape
. scripts/functions
set_debug 0

scripts/copy-win32-confs
scripts/cleanup-tape

echo "${cwd}/build" >${cwd}/tmp/file-list

change_jobname $JobName
start_test

cat <<END_OF_DATA >tmp/bconcmds
@output /dev/null
messages
@$out tmp/log1.out
label storage=DDS-4 volume=TestVolume001 slot=0 pool=Default drive=0
run job=$JobName yes
@sleep 10
status storage=DDS-4
@sleep 30
messages
wait
messages
@#
@# now do a restore
@#
@$out tmp/log2.out
restore where=${cwd}/tmp/bareos-restores select all storage=DDS-4 done
yes
wait
messages
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=DDS-4
stop_bareos

check_two_logs
# no diff for now
dstat=0
end_test
