<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2017 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

?>

<div class="panel panel-default">

   <div class="panel-heading">
      <h3 class="panel-title"><?php echo $this->translate('Jobs started during the past 24 hours') ?>
         <a href="#" onClick="refreshPartials();return false;" title="Refresh"><span class="glyphicon glyphicon-refresh pull-right" aria-hidden="true"></span></a>
      </h3>
   </div>

   <div class="panel-body">

   <div class="container-fluid block">

      <div class="row">

         <div class="col-md-3 text-center">
            <h4>
               <span class="label label-info"><?php echo $this->translate('Running'); ?></span>
            </h4>
            <h3>
               <a href="<?php echo $this->url('job', array('action' => 'index'), array('query' => array('period' => '1', 'status' => 'running'))); ?>">
                  <span class="running-jobs-field"></span>
               </a>
            </h3>
         </div>

         <div class="col-md-3 text-center">
            <h4>
               <span class="label label-default"><?php echo $this->translate('Waiting'); ?></span>
            </h4>
            <h3>
               <a href="<?php echo $this->url('job', array('action' => 'index'), array('query' => array('period' => '1', 'status' => 'waiting'))); ?>">
                  <span class="waiting-jobs-field"></span>
               </a>
            </h3>
         </div>

         <div class="col-md-3 text-center">
            <h4>
               <span class="label label-success"><?php echo $this->translate('Successful'); ?></span>
            </h4>
            <h3>
               <a href="<?php echo $this->url('job', array('action' => 'index'), array('query' => array('period' => '1', 'status' => 'successful'))); ?>">
                  <span class="successful-jobs-field"></span>
               </a>
            </h3>
         </div>

         <div class="col-md-3 text-center">
            <h4>
               <span class="label label-danger"><?php echo $this->translate('Failed'); ?></span>
            </h4>
            <h3>
               <a href="<?php echo $this->url('job', array('action' => 'index'), array('query' => array('period' => '1', 'status' => 'unsuccessful'))); ?>">
                  <span class="failed-jobs-field"></span>
               </a>
            </h3>
         </div>

      </div>

   </div>

   </div>

</div>
