#!/bin/sh
#
# Run a simple backup on a mysql database
#   then convert to postgresql and restore it.
#

TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd
. ./environment
. ${scripts}/functions

. ./environment-postgresql
${scripts}/cleanup
${scripts}/setup

. ./environment-mysql
${scripts}/cleanup
${scripts}/setup

# Directory to backup.
# This directory will be created by setup_data().
BackupDirectory="${tmp}/data"

# Use a tgz to setup data to be backed up.
# Data will be placed at "${tmp}/data/".
setup_data

start_test

cat <<END_OF_DATA >$tmp/bconcmds
@$out /dev/null
messages
@$out $tmp/log1.out
setdebug level=100 storage=File
label volume=TestVolume001 storage=File pool=Full catalog=mysql
run job=$JobName yes
status director
status client=bareos-fd
status storage=File
wait
messages
@$out $tmp/files.mysql
messages
list files jobid=1
END_OF_DATA

cp "${conf}"/bareos-dir.d/client/bareos-mysql-fd.conf.test "${conf}"/bareos-dir.d/client/bareos-fd.conf

run_bareos
stop_bareos

"${sbin}"/bareos-dbcopy -d -c ${current_test_directory}/etc/bareos mysql postgresql

cat <<END_OF_DATA >$tmp/bconcmds
@#
@# now do a restore on the postgresql database
@#
@$out $tmp/log2.out
wait
restore client=bareos-fd fileset=SelfTest where=$tmp/bareos-restores select all done
yes
wait
messages
@$out $tmp/files.postgresql
messages
list files jobid=1
END_OF_DATA

cp "${conf}"/bareos-dir.d/client/bareos-postgresql-fd.conf.test "${conf}"/bareos-dir.d/client/bareos-fd.conf

run_bareos
check_for_zombie_jobs storage=File client=bareos-fd
stop_bareos

check_two_logs
check_restore_diff ${BackupDirectory}

sed -i '/Using Catalog.*/d' "${tmp}"/files.postgresql
sed -i '/Using Catalog.*/d' "${tmp}"/files.mysql

sort "${tmp}"/files.mysql -o "${tmp}"/files.mysql
sort "${tmp}"/files.postgresql -o "${tmp}"/files.postgresql

if ! diff "${tmp}"/files.mysql "${tmp}"/files.postgresql;
then
  estat=1
  echo "differences in \"list files jobid=1\" output!"
fi

end_test
