<?php

$title = 'Fileset details';
$this->headTitle($title);

?>

<h2><?php echo $title; ?></h2>
<hr />

<div class="row">

<div class="col-md-6">
<div class="panel panel-default">
	  
<div class="panel-heading">
<h3 class="panel-title"><?php echo $this->escapeHtml($fileset->fileset); ?></h3>
</div>
    
<div class="panel-body">

<table class="table table-striped table-hover" style="font-size: 9pt;">

<tr><td>Fileset ID</td><td><?php echo $this->escapeHtml($fileset->filesetid); ?></td></tr>
<tr><td>Fileset Name</td><td><?php echo $this->escapeHtml($fileset->fileset); ?></td></tr>
<tr><td>MD5</td><td><?php echo $this->escapeHtml($fileset->md5); ?></td></tr>
<tr><td>Createtime</td><td><?php echo $this->escapeHtml($fileset->createtime); ?></td></tr>

</table>

</div>
</div>
</div>

</div>