<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2015 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Fileset details';
$this->headTitle($title);

?>

<div class="row">

<div class="col-md-12">
<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title">Fileset</h3>
</div>

<div class="panel-body">

<table class="table table-condensed">

<tr>
   <th class="bg-primary">Id</th>
   <th class="bg-primary">Name</th>
   <th class="bg-primary">MD5</th>
   <th class="bg-primary">Createtime</th>
</tr>

<tr>
   <td><?php echo $this->escapeHtml($fileset['filesetid']); ?></td>
   <td><?php echo $this->escapeHtml($fileset['fileset']); ?></td>
   <td><?php echo $this->escapeHtml($fileset['md5']); ?></td>
   <td><?php echo $this->escapeHtml($fileset['createtime']); ?></td>
</tr>

</table>

<pre>
<code>
<?php echo $fileset['filesettext']; ?>
</code>
</pre>

</div>
</div>
</div>
</div>
