<?php

$title = 'Fileset';
$this->headTitle($title);

?>

<h2><?php echo $title; ?></h2>
<hr />

<div class="row">

<div class="col-md-12">
<div class="panel panel-default">
	    
<div class="panel-body">

<table class="table table-striped table-hover" style="font-size: 9pt;">

<tr>
	<th>Fileset ID</th>
	<th>Fileset Name</th>
	<th>MD5</th>
	<th>Modified</th>
</tr>

<?php foreach($filesets as $fileset) : ?>

<tr>

	<td><a href="<?php echo $this->url('fileset', array('action'=>'details', 'id' => $fileset->filesetid)); ?>"><?php echo $this->escapeHtml($fileset->filesetid); ?></a></td>
	<td><?php echo $this->escapeHtml($fileset->fileset); ?></td>
	<td><?php echo $this->escapeHtml($fileset->md5); ?></td>
	<td><?php echo $this->escapeHtml($fileset->createtime); ?></td>

</tr>

<?php endforeach; ?>

</table>

</div>
</div>
</div>

</div>
