<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2015 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Filesets';
$this->headTitle($title);

?>

<p>
Filesets per page:
<a href="<?php echo $this->url('fileset', array('limit' => '10', null, null, true)); ?>">10</a> |
<a href="<?php echo $this->url('fileset', array('limit' => '25', null, null, true)); ?>">25</a> |
<a href="<?php echo $this->url('fileset', array('limit' => '50', null, null, true)); ?>">50</a> |
<a href="<?php echo $this->url('fileset', array('limit' => '100', null, null, true)); ?>">100</a>
</p>

<table class="table">

<tr>
	<th><?php echo $this->translate("Fileset"); ?></th>
	<th><?php echo $this->translate("Modified"); ?></th>
</tr>

<?php foreach($this->paginator as $fileset) : ?>

<tr>

	<td><a href="<?php echo $this->url('fileset', array('action'=>'details', 'id' => $fileset['fileset'])); ?>"><?php echo $this->escapeHtml($fileset['fileset']); ?></a></td>
	<td><?php echo $this->escapeHtml($fileset['createtime']); ?></td>

</tr>

<?php endforeach; ?>

</table>

<?php

echo $this->paginationControl(
			$this->paginator,
			'Elastic',
			array('partial/paginator.phtml', 'Fileset'),
			array('route' => 'fileset')
		);

?>

