#!/bin/sh
#
# Setup for using the Virtual Disk Changer (simulates tape changer)
#
/bin/cp -f scripts/bareos-dir-tape.conf bin/bareos-dir.conf
/bin/cp -f scripts/bareos-sd-2disk.conf bin/bareos-sd.conf
/bin/cp -f scripts/test-bareos-fd.conf bin/bareos-fd.conf
/bin/cp -f scripts/test-console.conf bin/bconsole.conf

outf="tmp/sed_tmp"
echo "s%# Autochanger = yes%  Autochanger = yes%g" >${outf}
cp bin/bareos-dir.conf tmp/1
sed -f ${outf} tmp/1 >bin/bareos-dir.conf
