#!/bin/sh
. scripts/functions
/bin/cp -f ${rscripts}/bareos-dir.conf ${scripts}/bareos-dir.conf
/bin/cp -f ${rscripts}/bareos-sd.conf ${scripts}/bareos-sd.conf
/bin/cp -f ${rscripts}/bareos-fd.conf ${scripts}/bareos-fd.conf
/bin/cp -f ${rscripts}/bconsole.conf ${scripts}/bconsole.conf
/bin/cp -f ${rscripts}/bconsole.conf ${scripts}/bat.conf

${rscripts}/set_tape_options
