#!/bin/sh
#
# This is a default configuration file for Bareos that
# sets reasonable defaults, and assumes that you do not
# have MySQL running.  It will "install" Bareos into
# bin and etc in the current directory.
#

CFLAGS="-g -Wall" \
  ./configure \
    --sbindir=$HOME/bareos/bin \
    --sysconfdir=$HOME/bareos/bin \
    --with-confdir=$HOME/bareos/bin \
    --with-pid-dir=$HOME/bareos/bin \
    --with-subsys-dir=$HOME/bareos/bin \
    --enable-smartalloc \
    --enable-gnome \
    --with-mysql=$HOME/mysql \
    --with-working-dir=$HOME/bareos/bin/working \
    --with-dump-email=root@localhost \
    --with-job-email=root@localhost \
    --with-smtp-host=localhost \
    --with-baseport=9101

exit 0
