<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2015 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Restore';
$this->headTitle($title);

?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<?php
	$form->prepare();
	$form->setAttribute('class','form-horizontal form-group-sm');
	echo $this->form()->openTag($form);
?>


<div class="row">

	<div class="col-md-4">

       <?php
		switch($this->restore_params['type']) {
			// Restore most recent client (full)
			case 1:
				echo $this->formRow($form->get('client')->setAttribute('class','form-control'));
				echo $this->formRow($form->get('fileset')->setAttribute('class','form-control'));
				echo $this->formRow($form->get('restoreclient')->setAttribute('class','form-control'));
				echo $this->formRow($form->get('where')->setAttribute('class','form-control'));
				break;
			// Restore specific job (jobid)
			case 2:
				echo $this->formRow($form->get('job')->setAttribute('class', 'form-control'));
				echo $this->formRow($form->get('client')->setAttribute('class','form-control'));
                                echo $this->formRow($form->get('restoreclient')->setAttribute('class','form-control'));
                                echo $this->formRow($form->get('where')->setAttribute('class','form-control'));
				break;
			default:
				echo $this->formRow($form->get('job')->setAttribute('class', 'form-control'));
				echo $this->formRow($form->get('client')->setAttribute('class','form-control'));
                                echo $this->formRow($form->get('fileset')->setAttribute('class','form-control'));
				echo $this->formRow($form->get('before')->setAttribute('class','form-control'));
                                echo $this->formRow($form->get('restoreclient')->setAttribute('class','form-control'));
				echo $this->formRow($form->get('where')->setAttribute('class','form-control'));
				break;
               }
       ?>

	</div>

	<div class="col-md-8">
		<!-- filebrowser -->
	</div>
</div>

<br />

<div class="row">
	<div class="col-md-4">
		<?php echo $this->formSubmit($form->get('submit')->setAttribute('class','btn btn-primary')); ?>
	</div>
</div>

<?php
   echo $this->form()->closeTag($form);
?>

