#!/bin/sh
#
# Run a simple backup
#   then restore it.
#
TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd
. ./environment
. ${scripts}/functions

. ./environment-postgresql
${scripts}/cleanup
${scripts}/setup

. ./environment-mysql
${scripts}/cleanup
${scripts}/setup

# Directory to backup.
# This directory will be created by setup_data().
BackupDirectory="${tmp}/data"

# Use a tgz to setup data to be backed up.
# Data will be placed at "${tmp}/data/".
setup_data

start_test

cat <<END_OF_DATA >$tmp/bconcmds
@$out /dev/null
messages
@$out $tmp/log1.out
setdebug level=100 storage=File
label volume=TestVolume001 storage=File pool=Full catalog=mysql
run job=$JobName yes
status director
status client=bareos-mysql-fd
status storage=File
wait
messages
@#
@# now do a restore
@#
@$out $tmp/log2.out
wait
restore client=bareos-mysql-fd fileset=SelfTest where=$tmp/bareos-restores select all done
#restore client=bareos-postgresql-fd fileset=SelfTest where=$tmp/bareos-restores select all done
yes
wait
messages
quit
END_OF_DATA

run_bareos
check_for_zombie_jobs storage=File client=bareos-mysql-fd
stop_bareos

check_two_logs
check_restore_diff ${BackupDirectory}
end_test
