<?php

$title = 'Job details';
$this->headTitle($title);

?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<div class="row">

  <div class="col-md-6">
      
      <div class="panel panel-default">
      
	<div class="panel-heading">
	  <h3 class="panel-title">General</h3>
	</div>

	<div class="panel-body">

	<table class="table table-striped table-hover" style="font-size: 9pt;">
	<tr><td>Job</td><td><?php echo $this->escapeHtml($job->jobid); ?></td></tr>
	<tr><td>Name</td><td><?php echo $this->escapeHtml($job->jobname); ?></td></tr>
	<tr><td>Client</td><td><a href="<?php echo $this->url('client', array('action' => 'details', 'id' => $job->clientid)); ?>"><?php echo $this->escapeHtml($job->clientname); ?></a></td></tr>
	<tr><td>Type</td><td><?php echo $this->printJobType($job->type); ?></td></tr>
	<tr><td>Level</td><td><?php echo $this->printJobLevel($job->level); ?></td></tr>
	<tr><td>Scheduled start</td><td><?php echo $this->printDate($job->schedtime, 'long'); ?></td></tr>
	<tr><td>Real start</td><td><?php echo $this->printDate($job->starttime, 'long'); ?></td></tr>
	<tr><td>End</td><td><?php echo $this->printDate($job->endtime, 'long'); ?></td></tr>
	<tr><td>Files</td><td><a href="<?php echo $this->url('file', array('action' => 'jobid', 'id' => $job->jobid)); ?>"><?php echo $this->escapeHtml($job->jobfiles); ?></a></td></tr>
	<tr><td>Bytes</td><td><?php echo $this->printBytes($job->jobbytes); ?></td></tr>
	<tr><td>Pool</td><td><a href="<?php echo $this->url('pool', array('action' => 'details', 'id' => $job->poolid)); ?>"><?php echo $this->escapeHtml($job->poolid); ?></a></td></tr>
	<tr><td>Fileset</td><td><a href="<?php echo $this->url('fileset', array('action' => 'details', 'id' => $job->filesetid)); ?>"><?php echo $this->escapeHtml($job->filesetid); ?></a></td></tr>
	<tr><td>Errors</td><td><?php echo $this->escapeHtml($job->joberrors); ?></td></tr>
	<tr><td>Status</td><td><?php echo $this->printJobStatus($job->jobstatus); ?></td></tr>
	</table>

	</div>

      </div>
      
  </div>
  
  <div class="col-md-6">
      
      <div class="panel panel-default">
      
	<div class="panel-heading">
	  <h3 class="panel-title">Log</h3>
	</div>

	<div class="panel-body">

	

	</div>

      </div>
      
  </div>
  
  
  
</div>
