<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2015 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 * @author	  Frank Bergkemper
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Job details';
$this->headTitle($title);

?>

<!-- Job -->
<div class="row">

<div class="col-md-12">

<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title">Job</h3>
</div>

<div class="panel-body">

<table class="table table-condensed">

<tr>
	<td><b>Job</b></td><td><?php echo $this->escapeHtml($job['jobid']); ?></td>
	<td><b>Scheduled start</b></td><td><?php echo $this->printDate($job['schedtime'], 'iso'); ?></td>
	<td><b>Status</b></td><td><?php echo $this->printJobStatus($job['jobstatus']); ?></td>
</tr>

<tr>
	<td><b>Name</b></td><td><?php echo $this->escapeHtml($job['job']); ?></td>
	<td><b>Real start</b></td><td><?php echo $this->printDate($job['starttime'], 'iso'); ?></td>
	<td><b>Errors</b></td><td><?php echo $this->escapeHtml($job['joberrors']); ?></td>
</tr>

<tr>
	<td><b>Client</b></td><td><a href="<?php echo $this->url('client', array('action' => 'details', 'id' => $job['clientname'])); ?>"><?php echo $this->escapeHtml($job['clientname']); ?></a></td>
	<td><b>End</b></td><td><?php echo $this->printDate($job['endtime'], 'iso'); ?></td>
	<td><b>Files</b></td><td><?php echo $this->escapeHtml($job['jobfiles']); ?></td>
</tr>

<tr>
	<td><b>Type</b></td><td><?php echo $this->printJobType($job['type']); ?></td>
	<td><b>Fileset</b></td><td><?php echo $this->escapeHtml($job['filesetid']); ?></td>
	<td><b>Bytes</b></td><td><?php echo $this->printBytes($job['jobbytes']); ?></td>
</tr>

<tr>
	<td><b>Level</b></td><td><?php echo $this->printJobLevel($job['level']); ?></td>
	<td><b>Pool</b></td><td><a href="<?php echo $this->url('pool', array('action' => 'details', 'id' => $job['poolname'])); ?>"><?php echo $this->escapeHtml($job['poolname']); ?></a></td>
	<td></td><td></td>
</tr>

</table>

</div>
</div>
</div>
</div>

<!-- Log -->
<div class="row">

<div class="col-md-12">

<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title">Messages</h3>
</div>

<div class="panel-body">

<table class="table table-condensed">

	<tr>
	<th class="bg-primary">Timestamp</th>
	<th class="bg-primary">Message</th>
	</tr>

	<?php foreach($this->joblog as $log) : ?>

	<tr>
	<td><?php echo $this->escapeHtml($log['time']); ?></td>
	<td><?php echo nl2br($this->escapeHtml($log['logtext'])); ?></td>
	</tr>

	<?php endforeach; ?>

</table>

</div>
</div>
</div>
</div>
