<?php

$title = 'Job history';
$this->headTitle($title);

?>

<h2><?php echo $title; ?></h2>
<hr />

<div class="row">

<div class="col-md-2">

	  <div class="panel panel-default">
	  
	      <div class="panel-heading">
		  <h3 class="panel-title"><?php echo $this->translate('Job'); ?></h3>
	      </div>
    
	      <div class="panel-body">
	      
	      <table class="table" style="font-size: 9pt;">
		<tr><td><a href="<?php echo $this->url('job', array('action'=>'index')); ?>"><?php echo $this->translate('Job history'); ?></a></td></tr>
		<tr><td><a href="<?php echo $this->url('job', array('action'=>'todo')); ?>"><?php echo $this->translate('Running jobs'); ?></a></td></tr>
		<tr><td><a href="<?php echo $this->url('job', array('action'=>'todo')); ?>"><?php echo $this->translate('todo'); ?></a></td></tr>
		<tr><td><a href="<?php echo $this->url('job', array('action'=>'todo')); ?>"><?php echo $this->translate('Job timeline'); ?></a></td></tr>
	      </table>
	      
	      </div>
	      
	  </div>

</div>

<div class="col-md-10">

<div class="panel panel-default">
<div class="panel-body">

<table class="table table-striped table-hover" style="font-size: 9pt;">

<tr>
	<th>Job</th>
	<th>Name</th>
	<th>Client</th>
	<th>Type</th>
	<th>Level</th>
	<th>Start</th>
	<th>End</th>
	<th>Duration</th>
	<th>Status</th>
	<th>Log</th>
	
</tr>

<?php foreach ($this->paginator as $job) : ?>

<tr>

	<td><a href="<?php echo $this->url('job', array('action' => 'details', 'id' => $job->jobid)); ?>"><?php echo $this->escapeHtml($job->jobid); ?></a></td>
	<td><?php echo $this->escapeHtml($job->jobname); ?></td>
	<td><a href="<?php echo $this->url('client', array('action' => 'details', 'id' => $job->clientid)); ?>"><?php echo $this->escapeHtml($job->clientname); ?></a></td>
	<td><?php echo $this->printJobType($job->type); ?></td>
	<td><?php echo $this->printJobLevel($job->level); ?></td>
	<td><?php echo $this->escapeHtml($job->starttime); ?></td>
	<td><?php echo $this->escapeHtml($job->endtime); ?></td>
	<td><?php echo $this->printJobDuration($job->starttime, $job->endtime); ?></td>
	<td><?php echo $this->printJobStatus($job->jobstatus); ?></td>
	<td><a href="<?php echo $this->url('log', array('action' => 'job', 'id' => $job->jobid)); ?>">View</a></td>
	
</tr>

<?php endforeach; ?>

</table>

</div>
</div>

<?php

echo $this->paginationControl(
			$this->paginator, 
			'Elastic',
			array('partial/paginator.phtml', 'Job'),
			array('route' => 'job')
		);

?>

</div>

</div>
