<?php

$title = 'Job history';
$this->headTitle($title);

?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<ul class="nav nav-tabs">
	<li class="active"><a href="<?php echo $this->url('job', array('action'=>'index')); ?>"><?php echo $this->translate('Job history'); ?></a></li>
	<li><a href="<?php echo $this->url('job', array('action'=>'running')); ?>"><?php echo $this->translate('Running jobs'); ?></a></li>
	<li><a href="<?php echo $this->url('job', array('action'=>'waiting')); ?>"><?php echo $this->translate('Waiting jobs'); ?></a></li>
	<li><a href="<?php echo $this->url('job', array('action'=>'problem')); ?>"><?php echo $this->translate('Unsuccessful jobs'); ?></a></li>
	<li><a href="<?php echo $this->url('job', array('action'=>'timeline')); ?>"><?php echo $this->translate('Job timeline'); ?></a></li>
</ul>

<br />

<div class="row">

<div class="col-md-12">

<div class="panel panel-default">
<div class="panel-body">

<table class="table table-striped table-hover" style="font-size: 9pt;">

<tr>
	<th><?php echo $this->translate("Job"); ?></th>
	<th><?php echo $this->translate("Name"); ?></th>
	<th><?php echo $this->translate("Client"); ?></th>
	<th><?php echo $this->translate("Type"); ?></th>
	<th><?php echo $this->translate("Level"); ?></th>
	<th><?php echo $this->translate("Start"); ?></th>
	<th><?php echo $this->translate("End"); ?></th>
	<th><?php echo $this->translate("Duration"); ?></th>
	<th><?php echo $this->translate("Status"); ?></th>
	<th><?php echo $this->translate("Log"); ?></th>
	<th></th>
	<th></th>
	
</tr>

<?php foreach ($this->paginator as $job) : ?>

<tr>

	<td><a href="<?php echo $this->url('job', array('action' => 'details', 'id' => $job->jobid)); ?>"><?php echo $this->escapeHtml($job->jobid); ?></a></td>
	<td><?php echo $this->escapeHtml($job->jobname); ?></td>
	<td><a href="<?php echo $this->url('client', array('action' => 'details', 'id' => $job->clientid)); ?>"><?php echo $this->escapeHtml($job->clientname); ?></a></td>
	<td><?php echo $this->printJobType($job->type); ?></td>
	<td><?php echo $this->printJobLevel($job->level); ?></td>
	<td><?php echo $this->printDate($job->starttime); ?></td>
	<td><?php echo $this->printDate($job->endtime); ?></td>
	<?php if(!empty($job->endtime)) : ?>
	<td><?php echo $this->printJobDuration($job->starttime, $job->endtime); ?></td>
	<?php endif; ?>
	<?php if(empty($job->endtime)) : ?>
	<td><?php echo $this->escapeHtml("-"); ?></td>
	<?php endif; ?>
	<td><?php echo $this->printJobStatus($job->jobstatus); ?></td>
	<td><a href="<?php echo $this->url('log', array('action' => 'job', 'id' => $job->jobid)); ?>" title="<?php echo $this->translate("View logs"); ?>"><span class="glyphicon glyphicon-file"></span></a></td>
	<td>
	<?php if($job->type == "B") : ?>
	<a href="<?php ?>" title="<?php echo $this->translate("Rerun"); ?>"><span class="glyphicon glyphicon-repeat"></span></a>
	<?php endif; ?>
	</td>
	<td>
	<?php if($job->type == "B") : ?>
	<a href="<?php ?>" title="<?php echo $this->translate("Restore"); ?>"><span class="glyphicon glyphicon-import"></span></a>
	<?php endif; ?>
	</td>
	
</tr>

<?php endforeach; ?>

</table>

</div>
</div>

<?php

echo $this->paginationControl(
			$this->paginator, 
			'Elastic',
			array('partial/paginator.phtml', 'Job'),
			array('route' => 'job')
		);

?>

</div>

</div>
