<?php

/**
 *
 * Barbossa - A Web-Frontend to manage Bareos
 * 
 * @link      http://github.com/fbergkemper/barbossa for the canonical source repository
 * @copyright Copyright (c) 2013-2014 dass-IT GmbH (http://www.dass-it.de/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Unsuccessful jobs (last 24 hours)';
$this->headTitle($title);

?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<?php

$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('
                <div%s>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                &times;
                </button>
                <ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

        echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
        echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
        echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
        echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));

?>

<ul class="nav nav-tabs">
	<li><a href="<?php echo $this->url('job', array('action'=>'index')); ?>"><?php echo $this->translate('Job history'); ?></a></li>
	<li><a href="<?php echo $this->url('job', array('action'=>'running')); ?>"><?php echo $this->translate('Running jobs'); ?></a></li>
	<li><a href="<?php echo $this->url('job', array('action'=>'waiting')); ?>"><?php echo $this->translate('Waiting jobs'); ?></a></li>
	<li class="active"><a href="<?php echo $this->url('job', array('action'=>'problem')); ?>"><?php echo $this->translate('Unsuccessful jobs'); ?></a></li>
	<li><a href="<?php echo $this->url('job', array('action'=>'timeline')); ?>"><?php echo $this->translate('Job timeline'); ?></a></li>
</ul>

<br />

<?php if(count($this->lastUnsuccessfulJobs) > 0) : ?>

<div class="row">

<div class="col-md-12">

<div class="panel panel-default">
<div class="panel-body">

<table class="table table-striped table-hover" style="font-size: 9pt;">

<tr>
	<th><?php echo $this->translate("Job"); ?></th>
	<th><?php echo $this->translate("Name"); ?></th>
	<th><?php echo $this->translate("Client"); ?></th>
	<th><?php echo $this->translate("Type"); ?></th>
	<th><?php echo $this->translate("Level"); ?></th>
	<th><?php echo $this->translate("Start"); ?></th>
	<th><?php echo $this->translate("End"); ?></th>
	<th><?php echo $this->translate("Status"); ?></th>
	<th><?php echo $this->translate("Log"); ?></th>
	
</tr>

<?php foreach ($this->paginator as $job) : ?>

<tr>

	<td><a href="<?php echo $this->url('job', array('action' => 'details', 'id' => $job->jobid)); ?>"><?php echo $this->escapeHtml($job->jobid); ?></a></td>
	<td><?php echo $this->escapeHtml($job->jobname); ?></td>
	<td><a href="<?php echo $this->url('client', array('action' => 'details', 'id' => $job->clientid)); ?>"><?php echo $this->escapeHtml($job->clientname); ?></a></td>
	<td><?php echo $this->printJobType($job->type); ?></td>
	<td><?php echo $this->printJobLevel($job->level); ?></td>
	<td><?php echo $this->printDate($job->starttime); ?></td>
	<td><?php echo $this->printDate($job->endtime); ?></td>
	<td><?php echo $this->printJobStatus($job->jobstatus); ?></td>
	<td><a href="<?php echo $this->url('log', array('action' => 'job', 'id' => $job->jobid)); ?>" title="<?php echo $this->translate("View logs"); ?>"><span class="glyphicon glyphicon-file"></span></a></td>
	
	
</tr>

<?php endforeach; ?>

</table>

</div>
</div>

<?php

echo $this->paginationControl(
			$this->paginator, 
			'Elastic',
			array('partial/paginator.phtml', 'Job'),
			array('route' => 'job')
		);

?>

</div>

</div>

<?php elseif(count($this->lastUnsuccessfulJobs) == 0) : ?>

<div class="alert alert-dismissable alert-info">
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
<ul>
<li><?php echo $this->translate("Congratulation, no unsuccessful jobs during the last 24 hours!"); ?></li>
</ul>
</div>

<?php endif; ?>
