<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2015 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 * @author    Frank Bergkemper
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Jobs';
$this->headTitle($title);

?>

<ul class="nav nav-tabs">
   <li><a href="<?php echo $this->url('job', array('action'=>'index')); ?>"><?php echo $this->translate('Overview'); ?></a></li>
   <li class="active"><a href="<?php echo $this->url('job', array('action'=>'run')); ?>"><?php echo $this->translate('Run'); ?></a></li>
</ul>

<br />

<div class="row">

<div class="col-md-6">

<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title">Run jobs</h3>
</div>

<div class="panel-body">

<table class="table table-hover" id="backupjobs">
   <thead class="bg-primary">
      <th><?php echo $this->translate("Name"); ?></th>
      <th><?php echo $this->translate("Actions"); ?></th>
   </thead>
</table>

</div>
</div>
</div>
</div>

<?php
   echo $this->headScript()->prependFile($this->basePath() . '/js/datatables.functions.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/datatables.min.js');
   echo $this->headLink()->prependStylesheet($this->basePath() . '/css/datatables.min.css');
?>

<script>

   $('#backupjobs').DataTable( {
      "ajax": {
         "url": "<?php echo $this->url('job', array('action' => 'getData'), null) . '?data=backupjobs'; ?>",
         "dataSrc": ""
      },
      "language": {
         "url": "<?php echo $this->basePath() . '/js/dataTables/language/'; ?>" + getLocale('<?php echo $_SESSION['bareos']['locale']; ?>')
      },
      "columns" : [
         {
            "data": null
         },
         {
            "orderable": false,
            "data": null
         }
      ],
      "paging": true,
      "ordering": true,
      "info": true,
      "pagingType": "full_numbers",
      "stateSave": true,
      "order": [[0, 'asc']],
      "columnDefs": [
         {
            "targets": 0,
            "data": null,
            "render": function(data, type, full, meta) {
               return data.name;
            }
         },
         {
            "targets": 1,
            "data": null,
            "render": function(data, type, full, meta) {
               return '<a href="<?php echo $this->basePath() . '/job/queue?job='; ?>'+data.name+'"><button type="button" class="btn btn-default btn-xs" id="btn-1" data-toggle="tooltip" data-placement="top" title="Run"><span class="glyphicon glyphicon-play-circle"></span></button></a>';
            }
         }
      ]
   } );

   $('#backupjobs tbody').on('mouseover', '#btn-1', function () {
      $('[data-toggle="tooltip"]').tooltip();
   } );

</script>
