<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2015 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 * @author    Frank Bergkemper
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Jobs';
$this->headTitle($title);

?>

<ul class="nav nav-tabs">
	<li><a href="<?php echo $this->url('job', array('action'=>'index')); ?>"><?php echo $this->translate('History'); ?></a></li>
	<li><a href="<?php echo $this->url('job', array('action'=>'running')); ?>"><?php echo $this->translate('Running'); ?></a></li>
	<li><a href="<?php echo $this->url('job', array('action'=>'waiting')); ?>"><?php echo $this->translate('Waiting'); ?></a></li>
	<li><a href="<?php echo $this->url('job', array('action'=>'unsuccessful')); ?>"><?php echo $this->translate('Unsuccessful (past 24 hours)'); ?></a></li>
	<li><a href="<?php echo $this->url('job', array('action'=>'successful')); ?>"><?php echo $this->translate('Successful (past 24 hours)'); ?></a></li>
	<!-- <li><a href="<?php echo $this->url('job', array('action'=>'timeline')); ?>"><?php echo $this->translate('Timeline'); ?></a></li> -->
	<li class="active"><a href="<?php echo $this->url('job', array('action'=>'run')); ?>"><?php echo $this->translate('Run'); ?></a></li>
</ul>

<br />

<div class="row">

<div class="col-md-8">

<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title">Run jobs</h3>
</div>

<div class="panel-body">

<p>
Jobs per page:
<a href="<?php echo $this->url('job', array('action' => 'run', 'limit' => '10', null, null, true)); ?>">10</a> |
<a href="<?php echo $this->url('job', array('action' => 'run', 'limit' => '25', null, null, true)); ?>">25</a> |
<a href="<?php echo $this->url('job', array('action' => 'run', 'limit' => '50', null, null, true)); ?>">50</a> |
<a href="<?php echo $this->url('job', array('action' => 'run', 'limit' => '100', null, null, true)); ?>">100</a>
</p>

<table class="table table-bordered table-condensed">

<tr>
<th class="bg-primary"><?php echo $this->translate("Name"); ?></th>
<th class="bg-primary"></th>
</tr>

<?php foreach ($this->paginator as $job) : ?>
<tr>
<td><?php echo $this->escapeHtml($job['name']); ?></td>
<td class="text-center">
<a href="<?php echo $this->url(
		'job',
		array('action'=>'queue'),
		array('query' => array('job' => $job['name']))
	); ?>" class="btn btn-default btn-xs" title="run now" role="button" data-toggle="tooltip" data-placement="top">
	<span class="glyphicon glyphicon-play-circle" aria-hidden="true"></span>
</a>
</td>
</tr>
<?php endforeach; ?>

</table>

<?php echo $this->paginationControl(
                        $this->paginator,
                        'Elastic',
                        array('partial/paginator.phtml', 'Job'),
                        array('route' => 'job')
                );

?>

</div>
</div>
</div>
</div>

<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>
