<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2015 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 * @author    Frank Bergkemper
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Jobs';
$this->headTitle($title);

?>

<?php

$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('
                <div%s>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                &times;
                </button>
                <ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

        echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
        echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
        echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
        echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));

?>

<ul class="nav nav-tabs">
	<li><a href="<?php echo $this->url('job', array('action'=>'index')); ?>"><?php echo $this->translate('History'); ?></a></li>
	<li><a href="<?php echo $this->url('job', array('action'=>'running')); ?>"><?php echo $this->translate('Running'); ?></a></li>
	<li><a href="<?php echo $this->url('job', array('action'=>'waiting')); ?>"><?php echo $this->translate('Waiting'); ?></a></li>
	<li><a href="<?php echo $this->url('job', array('action'=>'unsuccessful')); ?>"><?php echo $this->translate('Unsuccessful (past 24 hours)'); ?></a></li>
	<li class="active"><a href="<?php echo $this->url('job', array('action'=>'successful')); ?>"><?php echo $this->translate('Successful (past 24 hours)'); ?></a></li>
	<!-- <li><a href="<?php echo $this->url('job', array('action'=>'timeline')); ?>"><?php echo $this->translate('Timeline'); ?></a></li> -->
	<li><a href="<?php echo $this->url('job', array('action'=>'run')); ?>"><?php echo $this->translate('Run'); ?></a></li>
</ul>

<br />

<?php if(count($this->jobs) > 0) : ?>

<div class="row">

<div class="col-md-12">

<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title">Successful jobs (past 24 hours)</h3>
</div>

<div class="panel-body">

<p>
Jobs per page:
<a href="<?php echo $this->url('job', array('action' => 'successful', 'limit' => '10', null, null, true)); ?>">10</a> |
<a href="<?php echo $this->url('job', array('action' => 'successful', 'limit' => '25', null, null, true)); ?>">25</a> |
<a href="<?php echo $this->url('job', array('action' => 'successful', 'limit' => '50', null, null, true)); ?>">50</a> |
<a href="<?php echo $this->url('job', array('action' => 'successful', 'limit' => '100', null, null, true)); ?>">100</a>
</p>

<table class="table table-condensed">

<tr>
	<th class="bg-primary"><?php echo $this->translate("Job"); ?></th>
	<th class="bg-primary"><?php echo $this->translate("Name"); ?></th>
	<th class="bg-primary"><?php echo $this->translate("Client"); ?></th>
	<th class="bg-primary"><?php echo $this->translate("Type"); ?></th>
	<th class="bg-primary"><?php echo $this->translate("Level"); ?></th>
	<th class="bg-primary"><?php echo $this->translate("Start"); ?></th>
	<th class="bg-primary"><?php echo $this->translate("End"); ?></th>
	<th class="bg-primary"><?php echo $this->translate("Bytes"); ?></th>
	<th class="bg-primary"><?php echo $this->translate("Status"); ?></th>
	<th class="bg-primary"></th>
</tr>

<?php foreach ($this->paginator as $job) : ?>

<tr>

	<td><a href="<?php echo $this->url('job', array('action' => 'details', 'id' => $job['jobid'])); ?>"><?php echo $this->escapeHtml($job['jobid']); ?></a></td>
	<td><?php echo $this->escapeHtml($job['name']); ?></td>
	<td><a href="<?php echo $this->url('client', array('action' => 'details', 'id' => $job['clientname'])); ?>"><?php echo $this->escapeHtml($job['clientname']); ?></a></td>
	<td><?php echo $this->printJobType($job['type']); ?></td>
	<td><?php echo $this->printJobLevel($job['level']); ?></td>
	<td><?php echo $this->printDate($job['starttime']); ?></td>
	<td><?php echo $this->printDate($job['endtime']); ?></td>
	<td><?php echo $this->printBytes($job['jobbytes']); ?></td>
	<td><?php echo $this->printJobStatus($job['jobstatus']); ?></td>
	<td>
	<?php if($job['type'] == "B") : ?>
                <?php if($job['jobstatus'] == "T" || $job['jobstatus'] == "E" || $job['jobstatus'] == "e" || $job['jobstatus'] == "f" || $job['jobstatus'] == "A") : ?>
                <a class="btn btn-default btn-xs" 
                        href="<?php echo $this->url('job', array('action' => 'rerun', 'id' => $job['jobid'])); ?>" 
                        title="<?php echo $this->translate("Rerun"); ?>" data-toggle="tooltip" data-placement="top">
                <span class="glyphicon glyphicon-repeat"></span></a>
                <?php endif; ?>
        <?php endif; ?>
	</td>
</tr>

<?php endforeach; ?>

</table>

<?php

echo $this->paginationControl(
			$this->paginator, 
			'Elastic',
			array('partial/paginator.phtml', 'Job'),
			array('route' => 'job')
		);

?>

</div>
</div>
</div>
</div>

<?php elseif(count($this->lastSuccessfulJobs) == 0) : ?>

<div class="alert alert-dismissable alert-info">
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
<ul>
<li><?php echo $this->translate("No successful jobs found."); ?></li>
</ul>
</div>

<?php endif; ?>

<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>
