<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2014 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 * @author    Frank Bergkemper
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Jobs';
$this->headTitle($title);

?>

<ul class="nav nav-tabs">
   <li><a href="<?php echo $this->url('job', array('action'=>'index')); ?>"><?php echo $this->translate('History'); ?></a></li>
   <li><a href="<?php echo $this->url('job', array('action'=>'running')); ?>"><?php echo $this->translate('Running'); ?></a></li>
   <li class="active"><a href="<?php echo $this->url('job', array('action'=>'waiting')); ?>"><?php echo $this->translate('Waiting'); ?></a></li>
   <li><a href="<?php echo $this->url('job', array('action'=>'unsuccessful')); ?>"><?php echo $this->translate('Unsuccessful (past 24 hours)'); ?></a></li>
   <li><a href="<?php echo $this->url('job', array('action'=>'successful')); ?>"><?php echo $this->translate('Successful (past 24 hours)'); ?></a></li>
   <!-- <li><a href="<?php echo $this->url('job', array('action'=>'timeline')); ?>"><?php echo $this->translate('Timeline'); ?></a></li> -->
   <li><a href="<?php echo $this->url('job', array('action'=>'run')); ?>"><?php echo $this->translate('Run'); ?></a></li>
</ul>

<br />

<div class="row">

<div class="col-md-12">

<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title">Unsuccessful jobs (past 24 hours)</h3>
</div>

<div class="panel-body">

<table class="table table-hover" id="jobtable">

<thead class="bg-primary">
   <th><?php echo $this->translate("Job"); ?></th>
   <th><?php echo $this->translate("Name"); ?></th>
   <th><?php echo $this->translate("Client"); ?></th>
   <th><?php echo $this->translate("Type"); ?></th>
   <th><?php echo $this->translate("Level"); ?></th>
   <th><?php echo $this->translate("Status"); ?></th>
   <th><?php echo $this->translate("Actions"); ?></th>
</thead>

</table>

</div>
</div>
</div>
</div>

<?php
   echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.dataTables.min.js');
   echo $this->headScript()->prependFile($this->basePath() . '/js/dataTables.bootstrap.min.js');
   echo $this->headLink()->prependStylesheet($this->basePath() . '/css/dataTables.bootstrap.min.css');
?>

<script>

$(document).ready(function() {

   var table = $('#jobtable').DataTable( {
      "ajax": {
         "url": "<?php echo $this->url('job', array('action' => 'getData'), null) . '?data=waiting'; ?>",
         "dataSrc": ""
      },
      "columns": [
         { "data": null },
         { "data": null },
         { "data": null },
         { "data": null },
         { "data": null },
         { "data": null },
         {
            "orderable": false,
            "data": null
         }
      ],
      "paging": true,
      "ordering": true,
      "info": true,
      "pagingType": "full_numbers",
      "stateSave": true,
      "columnDefs": [
         {
            "targets": 0,
            "data": null,
            "render": function(data, type, full, meta) {
               return '<a href="<?php echo $this->basePath() . '/job/details/'; ?>'+data.jobid+'">'+data.jobid+'</a>';
            }
         },
         {
            "targets": 1,
            "data": null,
            "render": function(data, type, full, meta) {
               return data.name;
            }
         },
         {
            "targets": 2,
            "data": null,
            "render": function(data, type, full, meta) {
               return '<a href="<?php echo $this->basePath() . '/client/details/'; ?>'+data.client+'">'+data.client+'</a>';
            }
         },
         {
            "targets": 3,
            "data": null,
            "render": function(data, type, full, meta) {
               var output;
               switch(data.type) {
                  case 'B':
                     output = 'Backup';
                     break;
                  case 'M':
                     output = 'Migrated';
                     break;
                  case 'V':
                     output = 'Verify';
                     break;
                  case 'R':
                     output = 'Restore';
                     break;
                  case 'U':
                     output = 'Console program';
                     break;
                  case 'I':
                     output = 'Internal system job';
                     break;
                  case 'D':
                     output = 'Admin';
                     break;
                  case 'A':
                     output = 'Archive';
                     break;
                  case 'C':
                     output = 'Copy of a job';
                     break;
                  case 'c':
                     output = 'Copy job';
                     break;
                  case 'g':
                     output = 'Migration job';
                     break;
                  case 'S':
                     output = 'Scan';
                     break;
                  default:
                     output = data.type;
                     break;
               }
               return output;
            }
         },
         {
            "targets": 4,
            "data": null,
            "render": function(data, type, full, meta) {
               switch(data.level) {
                  case 'F':
                     return 'Full';
                  case 'D':
                     return 'Differential';
                  case 'I':
                     return 'Incremental';
                  default:
                     return data.level;
               }
            }
         },
         {
            "targets": 5,
            "data": null,
            "render": function(data, type, full, meta) {

               var output;

               switch(data.jobstatus) {

                  // Non-fatal error
                  case 'e':
                     output = '<span class="label label-danger">Failure</span>';
                     break;
                  // Terminated with errors
                  case 'E':
                     output = '<span class="label label-danger">Failure</span>';
                     break;
                  // Fatal error
                  case 'f':
                     output = '<span class="label label-danger">Failure</span>';
                     break;
                  // Terminated successful
                  case 'T':
                     output = '<span class="label label-success">Success</span>';
                     break;
                  // Running
                  case 'R':
                     output = '<span class="label label-info">Running</span>';
                     break;
                  // Created no yet running
                  case 'C':
                     output = '<span class="label label-default">Queued</span>';
                     break;
                  // Blocked
                  case 'B':
                     output = '<span class="label label-warning">Blocked</span>';
                     break;
                  // Verify found differences
                  case 'D':
                     output = '<span class="label label-warning">Verify found differences</span>';
                     break;
                  // Canceled by user
                  case 'A':
                     output = '<span class="label label-warning">Canceled</span>';
                     break;
                  // Waiting for client
                  case 'F':
                     output = '<span class="label label-default">Waiting</span>';
                     break;
                  // Waiting for storage daemon
                  case 'S':
                     output = '<span class="label label-default">Waiting</span>';
                     break;
                  // Waiting for new media
                  case 'm':
                     output = '<span class="label label-default">Waiting</span>';
                     break;
                  // Waiting for media mount
                  case 'M':
                     output = '<span class="label label-default">Waiting</span>';
                     break;
                  // Waiting for storage resource
                  case 's':
                     output = '<span class="label label-default">Waiting</span>';
                     break;
                  // Waiting for job resource
                  case 'j':
                     output = '<span class="label label-default">Waiting</span>';
                     break;
                  // Waiting for client resource
                  case 'c':
                     output = '<span class="label label-default">Waiting</span>';
                     break;
                  // Waiting on maximum jobs
                  case 'd':
                     output = '<span class="label label-default">Waiting</span>';
                     break;
                  // Waiting on starttime
                  case 't':
                     output = '<span class="label label-default">Waiting</span>';
                     break;
                  // Waiting on higher priority jobs
                  case 'p':
                     output = '<span class="label label-default">Waiting</span>';
                     break;
                  // SD despooling attributes
                  case 'a':
                     output = '<span class="label label-info">SD despooling attributes</span>';
                     break;
                  // Doing batch insert file records
                  case 'i':
                     output = '<span class="label label-info">Doing batch insert file records</span>';
                     break;
                  // Incomplete
                  case 'I':
                     output = '<span class="label label-primary">Incomplete</span>';
                     break;
                  // Committing data
                  case 'L':
                     output = '<span class="label label-info">Committing data</span>';
                     break;
                  // Terminated with warnings
                  case 'W':
                     output = '<span class="label label-warning">Warning</span>';
                     break;
                  // Doing data despooling
                  case 'l':
                     output = '<span class="label label-info">Doing data despooling</span>';
                     break;
                  // Queued waiting for device
                  case 'q':
                     output = '<span class="label label-default">Queued waiting for device</span>';
                     break;
                  // Default
                  default:
                     output = '<span class="label label-primary">' + data.jobStatus + '</span>';
                     break;
               }

               return output;
            }

         },
         {
            "targets": 6,
            "data": null,
            "render": function(data, type, full, meta) {
               if(data.type == 'B') {
                  return '<a class="btn btn-default btn-xs" data-toggle="tooltip" data-placement="top" href="<?php echo $this->basePath() . '/job/cancel/'; ?>'+data.jobid+'" title="Cancel" id="btn-1"><span class="glyphicon glyphicon-trash"></span></a>';
               }
               return '';
            }
         }
      ]
   } );

   $('#jobtable tbody').on('mouseover', '#btn-1', function () {
      $('[data-toggle="tooltip"]').tooltip();
   } );

} );

</script>
