#!/bin/bash
set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

#
# Run test to check correct output of #`status scheduler job=...`
# of a copy job whose client is disabled
#

start_test

disablelog="$tmp"/disablelog.out
statuslog="$tmp"/statuslog.out

cat <<END_OF_DATA >$tmp/bconcmds
messages
@$out $disablelog
enable client=bareos-fd
status scheduler job=copy

@$out $statuslog
disable client=bareos-fd
status scheduler job=copy
wait
messages
quit
END_OF_DATA

run_bconsole

#check that `status scheduler job=...` returns scheduled copy jobs
if ! grep "TestCycle               Level=Full" "$disablelog"; then
  echo "No scheduled jobs were found in $disablelog, which should contain all scheduled jobs" >&2
  estat=1
fi

#check that `status scheduler job=...` returns nothing when we disable the client
if  grep "TestCycle               Level=Full" "$statuslog"; then
  echo "a scheduled job was listed in $statuslog, which shouldn't happen" >&2
  estat=1
fi

end_test
