#!/bin/bash
set -e
set -o pipefail
set -u
#
# This systemtest tests the vmware plugin functionality
# of the Bareos FD by using the supplied module
#   BareosFdPluginProxmox.py
#
TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-proxmox-vm
#shellcheck source=../environment.in
. ./environment

export PATH="${current_test_directory}/sbin:${current_test_directory}/bin:$PATH"

JobName=backup-proxmox-vm
#shellcheck source=../scripts/functions
. "${rscripts}"/functions
"${rscripts}"/cleanup
"${rscripts}"/setup

BACKGUESTID=999010
RESTGUESTID=999011

qm stop "${BACKGUESTID}" || :
qm destroy "${BACKGUESTID}" || :
qm create "${BACKGUESTID}" --ostype l26 --memory 512 --name plugtestvm --scsi0 ZFS:2
qm start "${BACKGUESTID}"

start_test

cat <<END_OF_DATA >$tmp/bconcmds
@$out ${NULL_DEV}
messages
@$out $tmp/log1.out
setdebug level=100 storage=File
label volume=TestVolume001 storage=File pool=Full
run job=$JobName level=Full yes
status director
status client
status storage=File
wait
messages

END_OF_DATA

run_bareos "$@"

qm stop "${BACKGUESTID}"
qm destroy "${BACKGUESTID}"

# make sure BACKGUESTID was destroyed
qm list | grep -v "${BACKGUESTID}"

cat <<END_OF_DATA2 >$tmp/bconcmds
@#
@# now do a restore
@#
@$out $tmp/log2.out
wait
setdebug client=bareos-fd level=1000 trace=1
restore client=bareos-fd fileset=ProxmoxTestVM where=/ select all done  pluginoptions=python:guestid=${RESTGUESTID}:restoretodisk=yes
yes
wait
messages
quit

END_OF_DATA2


run_bareos "$@"

qm start "${RESTGUESTID}"

# make sure RESTGUESTID was recovered
qm list | grep "${RESTGUESTID}"

# cleanup
qm stop "${RESTGUESTID}"
qm destroy "${RESTGUESTID}"


check_for_zombie_jobs storage=File

check_two_logs


end_test
