#!/bin/sh
#
# Run a simple backup
#   then restore it.
#
TestName="$(basename "$(pwd)")"
export TestName

JobName=ai-backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions
"${rscripts}"/cleanup
"${rscripts}"/setup


# Fill ${BackupDirectory} with data.
setup_data

start_test

cat <<END_OF_DATA >$tmp/bconcmds
@$out /dev/null
messages
@$out $tmp/log1.out
setdebug level=100 storage=File
label volume=TestVolume001 storage=File pool=Full
run job=$JobName level=Full yes
wait
@exec "sh -c 'touch ${tmp}/data/weird-files/file-1'"
run job=$JobName level=Incremental yes
wait
@exec "sh -c 'touch ${tmp}/data/weird-files/file-2'"
run job=$JobName level=Incremental yes
wait
@exec "sh -c 'touch ${tmp}/data/weird-files/file-3'"
run job=$JobName level=Incremental yes
wait
run job=Consolidate yes
wait
status director
status client
status storage=File
list jobs
wait
messages
wait
quit
END_OF_DATA

run_bareos "$@"

# Consolidating zero-file incremental backups

cat <<END_OF_DATA >$tmp/bconcmds
@$out /dev/null
messages
@$out $tmp/log2.out

run job=$JobName level=Incremental yes
wait
run job=$JobName level=Incremental yes
wait
run job=$JobName level=Incremental yes
wait
messages

run job=Consolidate yes
wait
messages
quit
END_OF_DATA

run_bconsole

stop_bareos

check_job_canceled

if ! grep "purged JobIds 6,4,7,8 as they were consolidated into Job 11" "$tmp"/log2.out; then
  echo "Zero file backups were not consolidated. Check $tmp/log2.out" >&2
  estat=1
fi

end_test
