#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2026-2026 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd

#shellcheck source=../../environment.in
. ./environment

#shellcheck source=../../scripts/functions
. ${BAREOS_SCRIPTS_DIR}/functions

start_test

cat <<END_OF_DATA >$tmp/bconcmds
@$out ${NULL_DEV}
messages
@$out ${runner_tmp}/create-backup.out
run job=$JobName yes
wait
messages
quit
END_OF_DATA

run_bconsole

check_for_zombie_jobs storage=File

expect_grep "No prior Full backup Job record found." \
  "${runner_tmp}/create-backup.out" \
  "Bad initial state. No backup should exist yet."

expect_grep "Start Backup JobId 1" \
  "${runner_tmp}/create-backup.out" \
  "Did not create backup job with id 1."

expect_grep "Backup OK" \
  "${runner_tmp}/create-backup.out" \
  "Backup was not created correctly."

end_test
