Cephfs Plugin
~~~~~~~~~~~~~

.. index::
   single: Plugin; ceph; cephfs
   single: Ceph; Cephfs Plugin

Opposite to the :ref:`Rados Backend <SdBackendRados>` that is used to store data on a CEPH Object Store, this plugin is intended to backup a CEPH Object Store via the Cephfs interface to other media. The package **bareos-filedaemon-ceph-plugin** (:sinceVersion:`15.2.0: Cephfs Plugin`) contains an example configuration file, that must be adapted to your environment.
