.. _oVirtPlugin:

oVirt Plugin
~~~~~~~~~~~~

.. index::
   pair: Plugin; oVirt

.. warning::

   The oVirt Plugin has been removed in :sinceVersion:`23: oVirt Plugin` because
   the plugin behaves unstable with Python 3.

   As Red Hat already has announced that Red Hat Virtualization will be
   discontinued and customers should merge away, the Bareos project will not
   work on solving the problems with Python 3 which are caused by third-party
   python modules.
   If you are using the oVirt plugin, stay with Baros 22 using the Python 2
   version of the plugin.
