Rados Plugin
~~~~~~~~~~~~

.. deprecated:: 20.0.0

.. index::
   single: Plugin; Ceph; Rados
   single: Ceph; Rados Plugin

Opposite to the :ref:`Rados Backend <SdBackendRados>` that is used to store data on a CEPH Object Store, this plugin is intended to backup a CEPH Object Store via the Rados interface to other media. The package **bareos-filedaemon-ceph-plugin** (:sinceVersion:`15.2.0: CEPH Rados Plugin`) contains an example configuration file, that must be adapted to your environment.
