BEGIN;

CREATE TABLE Quota (
   ClientId INTEGER REFERENCES Client DEFAULT 0,
   GraceTime INTEGER UNSIGNED DEFAULT 0,
   QuotaLimit BIGINT UNSIGNED DEFAULT 0,
   PRIMARY KEY (ClientId)
);

CREATE TABLE NDMPLevelMap (
   ClientId INTEGER REFERENCES Client DEFAULT 0,
   FileSetId INTEGER UNSIGNED REFERENCES FileSet DEFAULT 0,
   FileSystem TEXT DEFAULT '',
   DumpLevel INTEGER UNSIGNED DEFAULT 0,
   CONSTRAINT NDMPLevelMap_pkey PRIMARY KEY (ClientId, FilesetId, FileSystem)
);

ALTER TABLE Media ADD COLUMN EncryptionKey VARCHAR(128);

UPDATE Version SET VersionId = 2001;
COMMIT;
