.. csv-table::
   :header: "configuration directive name", "type of data", "default value", "remark"

   :config:option:`sd/autochanger/ChangerCommand`\             , "**= STRNAME** ", "", "**required** "
   :config:option:`sd/autochanger/ChangerDevice`\              , "**= STRNAME** ", "", "**required** "
   :config:option:`sd/autochanger/Description`\                , "= STRING", "", ""
   :config:option:`sd/autochanger/Device`\                     , "**= RESOURCE_LIST** ", "", "**required** "
   :config:option:`sd/autochanger/Name`\                       , "**= NAME** ", "", "**required** "

