.. csv-table::
   :header: "configuration directive name", "type of data", "default value", "remark"

   :config:option:`dir/counter/Catalog`\                       , "= RES", "", ""
   :config:option:`dir/counter/Description`\                   , "= STRING", "", ""
   :config:option:`dir/counter/Maximum`\                       , "= PINT32", "2147483647", ""
   :config:option:`dir/counter/Minimum`\                       , "= INT32", "0", ""
   :config:option:`dir/counter/Name`\                          , "**= NAME** ", "", "**required** "
   :config:option:`dir/counter/WrapCounter`\                   , "= RES", "", ""

