.. csv-table::
   :header: "configuration directive name", "type of data", "default value", "remark"

   :config:option:`sd/ndmp/AuthType`\                          , "= AUTH_TYPE", "None", ""
   :config:option:`sd/ndmp/Description`\                       , "= STRING", "", ""
   :config:option:`sd/ndmp/LogLevel`\                          , "= PINT32", "4", ""
   :config:option:`sd/ndmp/Name`\                              , "**= NAME** ", "", "**required** "
   :config:option:`sd/ndmp/Password`\                          , "**= AUTOPASSWORD** ", "", "**required** "
   :config:option:`sd/ndmp/Username`\                          , "**= STRING** ", "", "**required** "

