.. config:option:: dir/schedule/Description

   :type: STRING

   .. include:: /config-directive-description/dir-schedule-Description.rst.inc



.. config:option:: dir/schedule/Enabled

   :type: BOOLEAN
   :default: yes

   En- or disable this resource.

   .. include:: /config-directive-description/dir-schedule-Enabled.rst.inc



.. config:option:: dir/schedule/Name

   :required: True
   :type: NAME

   The name of the resource.

   .. include:: /config-directive-description/dir-schedule-Name.rst.inc



.. config:option:: dir/schedule/Run

   :type: SCHEDULE_RUN_COMMAND

   .. include:: /config-directive-description/dir-schedule-Run.rst.inc



