.. csv-table::
   :header: "configuration directive name", "type of data", "default value", "remark"

   :config:option:`dir/schedule/Description`\                  , "= STRING", "", ""
   :config:option:`dir/schedule/Enabled`\                      , "= BOOLEAN", "yes", ""
   :config:option:`dir/schedule/Name`\                         , "**= NAME** ", "", "**required** "
   :config:option:`dir/schedule/Run`\                          , "= SCHEDULE_RUN_COMMAND", "", ""

