.. csv-table::
   :header: "configuration directive name", "type of data", "default value", "remark"

   :config:option:`dir/fileset/Description`\                   , "= STRING", "", ""
   :config:option:`dir/fileset/EnableVSS`\                     , "= BOOLEAN", "yes", ""
   :config:option:`dir/fileset/Exclude`\                       , "\{ INCLUDE_EXCLUDE_ITEM \}", "", ""
   :config:option:`dir/fileset/IgnoreFileSetChanges`\          , "= BOOLEAN", "no", ""
   :config:option:`dir/fileset/Include`\                       , "\{ INCLUDE_EXCLUDE_ITEM \}", "", ""
   :config:option:`dir/fileset/Name`\                          , "**= NAME** ", "", "**required** "

