<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2014 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 * @author    Frank Bergkemper
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Login';
$this->headTitle($title);

?>

<div class="centered text-centered">
<div class="row">
<div class="col-md-4 col-centered text-centered">
<div class="form-group">

<?php

$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('director')->setAttribute('class','form-control'));
echo $this->formRow($form->get('consolename')->setAttribute('class','form-control'));
echo $this->formRow($form->get('password')->setAttribute('class','form-control'));
echo $this->formSubmit($form->get('submit')->setAttribute('class','btn btn-primary'));
echo $this->form()->closeTag();

if(isset($this->err_msg)) {
	echo "<br /><p class='text-danger bg-danger'>" . $this->err_msg ."</p>";
}

?>

</div>
</div>
</div>
</div>
