#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2025-2025 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

set -e
set -o pipefail
set -u

#shellcheck source=../../environment.in
. ./environment

#shellcheck source=../../scripts/functions
. "${BAREOS_SCRIPTS_DIR}"/functions

if [ -f "${tmp}/${vm_data_file}" ]; then
  #shellcheck source=vm.info.template
  source "${tmp}/${vm_data_file}"

  # delete the created vm
  cat <<EOF >"${tmp}/ps_commands"
Get-VM "${vm_name}" | Remove-VM -Force;
Remove-Item -Path "${vm_disk}";
EOF

  ps_exec "${tmp}/ps_commands"

fi

"${BAREOS_SCRIPTS_DIR}"/cleanup
