#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2021-2024 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

set -e
set -o pipefail
set -u

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions
"${rscripts}"/cleanup
"${rscripts}"/setup

# Fill ${BackupDirectory} with data.
setup_data

# Count number of directories to be stripped to fully
# strip away $BackupDirectory prefix
strip_count="${BackupDirectory//[!\/]}"
strip_count="${#strip_count}"

# Clear additional configs
rm -f  "${config_directory_dir_additional_test_config}"/*

# Create fileset strip path setting
cat <<END_OF_DATA > "$config_directory_dir_additional_test_config/strippath-fileset-job.conf"
FileSet {
  Name = "SelfTestStripPath"
  Description = "fileset just to backup some files for selftest"
  Include {
    Options {
      Signature = XXH128
	  HardLinks = Yes
	  Strip Path = $strip_count
    }
    File = "${BackupDirectory}"
  }
}
END_OF_DATA

bin/bareos start
bin/bareos status

# make sure, director is up and running.
print_debug "$(bin/bconsole <<< "status dir")"
