#!/bin/bash
set -e
set -o pipefail
set -u
#
# Run a simple backup, set it to archive and do a copy.
#
TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions
"${rscripts}"/cleanup
"${rscripts}"/setup



# Fill ${BackupDirectory} with data.
setup_data

# Count number of directories to be stripped to fully
# strip away $BackupDirectory prefix
strip_count="${BackupDirectory//[!\/]}"
strip_count="${#strip_count}"

# Clear additional configs
rm -f  "${config_directory_dir_additional_test_config}"/*

# Create fileset with strip path setting
cat <<END_OF_DATA > "$config_directory_dir_additional_test_config/strippath-backup-job.conf"
FileSet {
  Name = "SelfTest"
  Description = "fileset just to backup some files for selftest"
  Include {
    Options {
      Signature = XXH128
	  HardLinks = Yes
	  Strip Path = $strip_count
    }
    File = "${BackupDirectory}"
  }
}
END_OF_DATA

start_test

cat <<END_OF_DATA >"$tmp/bconcmds"
@$out /dev/null
messages
@$out $tmp/reload.out
reload
messages
@$out $tmp/backup.out
setdebug level=100 storage=File
setdebug level=10 client=bareos-fd
label volume=TestVolume001 storage=File pool=Full
run job=$JobName yes
status director
status client
status storage=File
wait
messages
@$out $tmp/file-list.out
list files jobid=1
@$out $tmp/restore.out
restore client=bareos-fd fileset=SelfTest where=$tmp/bareos-restores/${BackupDirectory} select all done yes
wait
messages
quit
END_OF_DATA

run_bareos "$@"

check_for_zombie_jobs storage=File

expect_grep "Start Restore Job" \
	    "$tmp/restore.out" \
	    "Required restore job was not started."

check_restore_diff "${BackupDirectory}"

end_test
