#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2024-2026 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

#CTEST requires=01-full+incr

TestName="$(basename "$(pwd)")"
export TestName

JobName=ai-backup-bareos-fd

#shellcheck source=../../environment.in
. ./environment

#shellcheck source=../../scripts/functions
. "${BAREOS_SCRIPTS_DIR}"/functions
start_test

# Consolidating zero-file incremental backups

# we need to sleep before the consolidate because the
# job retention is 1 second.  Otherwise we might not
# consider the last job eligable
cat <<END_OF_DATA >$tmp/bconcmds
@$out $tmp/extra.out
messages
.api 2
@$out $tmp/consolidate-empty-incrementals_incr.out
run job=$JobName level=Incremental yes
wait
run job=$JobName level=Incremental yes
wait
run job=$JobName level=Incremental yes
wait
@sleep 1
@$out $tmp/consolidate-empty-incrementals_consolidate.out
run job=Consolidate yes
wait
.api 1
@$out $tmp/consolidate-empty-incrementals_messages.out
messages
END_OF_DATA
run_bconsole

# take the last 3 jobs (needed in case of test restart)

jobids=$(grep "jobid" "$tmp/consolidate-empty-incrementals_incr.out" | tail -n 3 | sed 's/["jobid:]//g' | xargs | tr ' ' ',')
purged_jobids="$(
  sed -n "s/.*purging empty jobids //p" "$tmp/consolidate-empty-incrementals_messages.out" \
    | tail -n 1 | tr -d '\r'
)"

if [ -z "${purged_jobids}" ]; then
  set_error "Removal of expected empty jobs was not successful."
  exit 1
fi

IFS=',' read -r -a expected_jobids <<<"${jobids}"
IFS=',' read -r -a actual_jobids <<<"${purged_jobids// /}"

for purged_jobid in "${actual_jobids[@]}"; do
  found=0
  for expected_jobid in "${expected_jobids[@]}"; do
    if [ "${purged_jobid}" = "${expected_jobid}" ]; then
      found=1
      break
    fi
  done
  if [ "${found}" -ne 1 ]; then
    set_error "Unexpected empty jobs were purged: expected subset of ${jobids}, got ${purged_jobids}"
    exit 1
  fi
done

end_test
