#!/bin/bash
set -e
set -o pipefail
set -u
#
# Start and stop the daemons to make sure our configuration does not crash them.
# This checks
# - an invalid entry in an ACL
#
TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions
"${rscripts}"/cleanup
"${rscripts}"/setup

start_test

start_bareos
stop_bareos

end_test
