<?php

$title = 'Volume details';
$this->headTitle($title);

?>

<h2><?php echo $title; ?></h2>
<hr />

<script type="text/javascript">
    
    function chart1() {

      var data = [
	  ['Free bytes', <?php echo ($media->maxvolbytes - $media->volbytes); ?>],
	  ['Used bytes', <?php echo $media->volbytes; ?>]
      ];
      
      var plot1 = jQuery.jqplot('chart1',[data],
      {
	seriesDefaults: {
	  renderer: jQuery.jqplot.PieRenderer,
	  rendererOptions: { 
	    showDataLabels: true
	  }
      },
	legend:{ 
	  show: true,
	  location: 'w'
	},
	grid: {
	  drawGridLines: true
        }
      });
      
    }

    $(document).ready(
      function(){
	chart1();
      }
    );
    
</script>

<div class="row">

  <div class="col-md-7">

	  <div class="panel panel-default">
	  
	      <div class="panel-heading">
		  <h3 class="panel-title"><?php echo $this->translate('Volume details') ?></h3>
	      </div>
    
	      <div class="panel-body">

	      <table class="table table-striped table-hover" style="font-size: 9pt;">
	      <tr><td>Volume ID</td><td><a href="<?php echo $this->url('media', array('action'=>'details', 'id' => $media->mediaid)); ?>"><?php echo $this->escapeHtml($media->mediaid); ?></a></td></tr>
	      <tr><td>Volumename</td><td><?php echo $this->escapeHtml($media->volumename); ?></td></tr>
	      <tr><td>Mediatype</td><td><?php echo $this->escapeHtml($media->mediatype); ?></td></tr>
	      <tr><td>Mediatype ID</td><td><?php echo $this->escapeHtml($media->mediatypeid); ?></td></tr>
	      <tr><td>Labeltype</td><td><?php echo $this->escapeHtml($media->labeltype); ?></td></tr>
	      <tr><td>First written</td><td><?php echo $this->escapeHtml($media->firstwritten); ?></td></tr>
	      <tr><td>Last written</td><td><?php echo $this->escapeHtml($media->lastwritten); ?></td></tr>
	      <tr><td>Label date</td><td><?php echo $this->escapeHtml($media->labeldate); ?></td></tr>
	      <tr><td>Volume jobs</td><td><?php echo $this->escapeHtml($media->voljobs); ?></td></tr>
	      <tr><td>Volume files</td><td><?php echo $this->escapeHtml($media->volfiles); ?></td></tr>
	      <tr><td>Volume blocks</td><td><?php echo $this->escapeHtml($media->volblocks); ?></td></tr>
	      <tr><td>Volume mounts</td><td><?php echo $this->escapeHtml($media->volmounts); ?></td></tr>
	      <tr><td>Volume used bytes</td><td><?php echo $this->printBytes($media->volbytes); ?></td></tr>
	      <tr><td>Volume errors</td><td><?php echo $this->escapeHtml($media->volerrors); ?></td></tr>
	      <tr><td>Volume writes</td><td><?php echo $this->escapeHtml($media->volwrites); ?></td></tr>
	      <tr><td>Volume capacity bytes</td><td><?php echo $this->escapeHtml($media->volcapacitybytes); ?></td></tr>
	      <tr><td>Volume Status</td><td><?php echo $this->escapeHtml($media->volstatus); ?></td></tr>
	      <tr><td>Enabled</td><td><?php echo $this->escapeHtml($media->enabled); ?></td></tr>
	      <tr><td>Recycle</td><td><?php echo $this->escapeHtml($media->recycle); ?></td></tr>
	      <tr><td>Action on purge</td><td><?php echo $this->escapeHtml($media->actiononpurge); ?></td></tr>
	      <tr><td>Volume retention</td><td><?php echo $this->printRetention($media->volretention) . " days"; ?></td></tr>
	      <tr><td>Volume use duration</td><td><?php echo $this->escapeHtml($media->voluseduration); ?></td></tr>
	      <tr><td>Volume maximum jobs</td><td><?php echo $this->escapeHtml($media->maxvoljobs); ?></td></tr>
	      <tr><td>Volume maximum files</td><td><?php echo $this->escapeHtml($media->maxvolfiles); ?></td></tr>
	      <tr><td>Volume maximum bytes</td><td><?php echo $this->printBytes($media->maxvolbytes); ?></td></tr>
	      <tr><td>In changer</td><td><?php echo $this->escapeHtml($media->inchanger); ?></td></tr>
	      <tr><td>Storage ID</td><td><?php echo $this->escapeHtml($media->storageid); ?></td></tr>
	      <tr><td>Device ID</td><td><?php echo $this->escapeHtml($media->deviceid); ?></td></tr>
	      <tr><td>Media addressing</td><td><?php echo $this->escapeHtml($media->mediaaddressing); ?></td></tr>
	      <tr><td>Volume readtime</td><td><?php echo $this->escapeHtml($media->volreadtime); ?></td></tr>
	      <tr><td>Volume writetime</td><td><?php echo $this->escapeHtml($media->volwritetime); ?></td></tr>
	      <tr><td>Endfile</td><td><?php echo $this->escapeHtml($media->endfile); ?></td></tr>
	      <tr><td>Endblock</td><td><?php echo $this->escapeHtml($media->endblock); ?></td></tr>
	      <tr><td>Location ID</td><td><?php echo $this->escapeHtml($media->locationid); ?></td></tr>
	      <tr><td>Recycle count</td><td><?php echo $this->escapeHtml($media->recyclecount); ?></td></tr>
	      <tr><td>Initial write</td><td><?php echo $this->escapeHtml($media->initialwrite); ?></td></tr>
	      <tr><td>Scratchpool ID</td><td><?php echo $this->escapeHtml($media->scratchpoolid); ?></td></tr>
	      <tr><td>Recyclepool ID</td><td><?php echo $this->escapeHtml($media->recyclepoolid); ?></td></tr>
	      <tr><td>Encryptionkey</td><td><?php echo $this->escapeHtml($media->encryptionkey); ?></td></tr>
	      <tr><td>Comment</td><td><?php echo $this->escapeHtml($media->comment); ?></td></tr>
	      </table>
	      
	      </div>
	      
	  </div>
	  
  </div>

  <div class="col-md-5">
	  
	  <div class="panel panel-default">
	  
	      <div class="panel-heading">
		  <h3 class="panel-title"><?php echo $this->translate('Volume usage') ?></h3>
	      </div>
    
	      <div class="panel-body">
	  
	      <div id="chart1" style="width:400px; height:400px;"></div>
	      
	      </div>
	      
	  </div>
	      
  </div>

</div>