<?php

$title = 'Volume';
$this->headTitle($title);

?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<div class="row">

<div class="col-md-12">
<div class="panel panel-default">
    
<div class="panel-body">

<table class="table table-striped table-hover" style="font-size: 9pt;">

<tr>
	<th>Volume</th>
	<th>Name</th>
	<th>Storage</th>
	<th>Type</th>
	<th>Last written</th>
	<th>Status</th>
	<th>Retention</th>
	<th>Maximum bytes</th>
	<th>Current bytes</th>
	<th>Free bytes</th>
	
</tr>

<?php foreach($this->paginator as $volume) : ?>

<tr>

	<td><a href="<?php echo $this->url('media', array('action'=>'details', 'id' => $volume->mediaid)); ?>"><?php echo $this->escapeHtml($volume->mediaid); ?></a></td>
	<td><?php echo $this->escapeHtml($volume->volumename); ?></td>
	<td><a href="<?php echo $this->url('storage', array('action'=>'details')); ?>"><?php echo $this->escapeHtml($volume->storageid); ?></a></td>
	<td><?php echo $this->escapeHtml($volume->mediatype); ?></td>
	<td><?php echo $this->printDate($volume->lastwritten); ?></td>
	<td><?php echo $this->escapeHtml($volume->volstatus); ?></td>
	<td><?php echo $this->printRetention($volume->volretention) . " days"; ?></td>
	<td><?php echo $this->printBytes($volume->maxvolbytes); ?></td>
	<td><?php echo $this->printBytes($volume->volbytes); ?></td>
	<td><?php echo $this->printBytes($volume->maxvolbytes - $volume->volbytes); ?></td>
	
</tr>

<?php endforeach; ?>

</table>

</div>
</div>
</div>

</div>

<?php

echo $this->paginationControl(
			$this->paginator, 
			'Elastic',
			array('partial/paginator.phtml', 'Volume'),
			array('route' => 'media')
		);

?>
