<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos-webui for the canonical source repository
 * @copyright Copyright (c) 2013-2015 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 * @author    Frank Bergkemper
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$title = 'Volumes';
$this->headTitle($title);

?>

<div class="row">

<div class="col-md-12">
<div class="panel panel-default">

<div class="panel-heading">
<h3 class="panel-title">Volumes</h3>
</div>

<div class="panel-body">

<p>
Volumes per page:
<a href="<?php echo $this->url('media', array('limit' => '10', null, null, true)); ?>">10</a> |
<a href="<?php echo $this->url('media', array('limit' => '25', null, null, true)); ?>">25</a> |
<a href="<?php echo $this->url('media', array('limit' => '50', null, null, true)); ?>">50</a> |
<a href="<?php echo $this->url('media', array('limit' => '100', null, null, true)); ?>">100</a>
</p>

<table class="table table-condensed">

<tr>
	<th class="bg-primary"><?php echo $this->translate("Volume"); ?></th>
	<th class="bg-primary"><?php echo $this->translate("Name"); ?></th>
	<th class="bg-primary"><?php echo $this->translate("Storage"); ?></th>
	<th class="bg-primary"><?php echo $this->translate("Type"); ?></th>
	<th class="bg-primary"><?php echo $this->translate("Last written"); ?></th>
	<th class="bg-primary"><?php echo $this->translate("Status"); ?></th>
	<th class="bg-primary"><div align="right">Retention/Expiration</div></th>
	<th class="bg-primary"><div align="right"><?php echo $this->translate("Maximum bytes"); ?></div></th>
	<th class="bg-primary"><div align="right"><?php echo $this->translate("Current bytes"); ?></div></th>
	<th class="bg-primary"><div align="right">Free bytes</div></th>
</tr>

<?php foreach($this->paginator as $volume) : ?>

<tr>
	<td><a href="<?php echo $this->url('media', array('action'=>'details', 'id' => $volume['volumename'])); ?>"><?php echo $this->escapeHtml($volume['mediaid']); ?></a></td>
	<td><a href="<?php echo $this->url('media', array('action'=>'details', 'id' => $volume['volumename'])); ?>"><?php echo $this->escapeHtml($volume['volumename']); ?></a></td>
	<td><?php echo $this->escapeHtml($volume['storageid']); ?></td>
	<td><?php echo $this->escapeHtml($volume['mediatype']); ?></td>
	<td><div title="<?php echo $volume['lastwritten']; ?>"><?php echo $this->printHumanReadableTimeperiod($volume['lastwritten'], "fuzzy"); ?></div></td>
	<td><?php echo $this->escapeHtml($volume['volstatus']); ?></td>
	<td><div align="right"><?php echo $this->printExpiration($volume['volretention'], $volume['lastwritten'], $volume['volstatus']); ?></div></td>
	<td><div align="right"><?php echo $this->printBytes($volume['maxvolbytes']); ?></div></td>
	<td><div align="right"><?php echo $this->printBytes($volume['volbytes']); ?></div></td>
	<td><div align="right"><?php echo $this->printBytes($volume['maxvolbytes'] - $volume['volbytes']); ?></div></td>
</tr>

<?php endforeach; ?>

</table>

<?php

echo $this->paginationControl(
			$this->paginator,
			'Elastic',
			array('partial/paginator.phtml', 'Volume'),
			array('route' => 'media')
		);

?>

</div>
</div>
</div>
</div>

