/*
   BAREOS® - Backup Archiving REcovery Open Sourced

   Copyright (C) 2024-2026 Bareos GmbH & Co. KG

   This program is Free Software; you can redistribute it and/or
   modify it under the terms of version three of the GNU Affero General Public
   License as published by the Free Software Foundation and included
   in the file LICENSE.

   This program is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
   Affero General Public License for more details.

   You should have received a copy of the GNU Affero General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
   02110-1301, USA.
*/
/**
 * @file
 * Embedded static asset table.
 * Auto-generated by embed_assets.py — do not edit by hand.
 */
#ifndef BAREOS_BAREOS_SETUP_EMBEDDED_ASSETS_H_
#define BAREOS_BAREOS_SETUP_EMBEDDED_ASSETS_H_

#include <cstddef>
#include <cstdint>

struct EmbeddedFile {
  const char* path;     // URL path, e.g. "/index.html"
  const uint8_t* data;  // gzip-compressed content
  size_t size;          // byte length of data
  const char* mime;     // MIME type string
  bool gzipped;         // true if data is gzip-compressed
};

// Defined in the auto-generated embedded_assets.cc
extern const EmbeddedFile kEmbeddedFiles[];
extern const size_t kEmbeddedFilesCount;

#endif  // BAREOS_BAREOS_SETUP_EMBEDDED_ASSETS_H_
