os:
  - linux
# dist: using Ubuntu 20.04 (Focal Fossa)
#dist: focal
# dist: using Ubuntu 18.04 (Bionic)
dist: bionic
# sudo: required
language: cpp
compiler:
  - gcc
git:
  depth: false
services:
  - postgresql
addons:
  hosts:
    - bareos.example.com

# This project also uses Coverity Scan https://scan.coverity.com/
# However, the Travis coverity scan addon (as of 19.02.2014) does not fit our needs,
# because then all builds are done as coverity scans and results send to the server.
# Therefore we reused the old method
# (setting environment variables, download and execute a script).

env:
    global:
        - BAREOS_VERSION="unknown"
        - NOW=$(LANG=C date -R -u)
        - DB=postgresql
        # -- BEGIN Coverity Scan ENV
        # The build command with all of the arguments that you would apply to a manual `cov-build`
        # Usually this is the same as STANDARD_BUILD_COMMAND, excluding the automated test arguments
        - COVERITY_SCAN_BUILD_COMMAND="make -C obj-x86_64-linux-gnu"
        # Name of the project
        - COVERITY_SCAN_PROJECT_NAME="bareos/bareos"
        # Email address for notifications related to this build
        - COVERITY_SCAN_NOTIFICATION_EMAIL="coverity@bareos.org"
        # Regular expression selects on which branches to run analysis
        # Be aware of quotas. Do not run on every branch/commit
        - COVERITY_SCAN_BRANCH_PATTERN="master"
        # COVERITY_SCAN_TOKEN: is set as secure settings in the travis-ci.org configuration
        - COVERITY_SCAN_BUILD_URL="https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh"
        - COVERITY_SCAN_BUILD="curl -s $COVERITY_SCAN_BUILD_URL | bash"
        # -- END Coverity Scan ENV

jobs:
  include:
    - os: linux
      dist: focal
      addons:
        # The travis focal dist from 03 Nov 2020 fails
        # with the default postgresql installation.
        # However, Postgresql 13 does work.
        # This entry can be removed, as soon,
        # as the default postgresql installation works again.
        postgresql: "13"
    - os: linux
      dist: bionic
    # disabled, because cmake is too old.
    #- os: linux
    #  dist: trusty
    - compiler: clang
    - env: COVERITY_SCAN=true
    - env: BUILD_WEBUI=true
      addons:
        sauce_connect: true

  allow_failures:
    - env: COVERITY_SCAN=true
    - env: BUILD_WEBUI=true

before_install:
    # install build dependencies
    - .travis/travis_before_install.sh

before_script:
    # changelog file is required (and normally generated by Jenkins)
    - cmake -P write_version_files.cmake
    - BAREOS_VERSION=$(cmake -P get_version.cmake | sed -e 's/-- //')
    - printf "bareos (%s) unstable; urgency=low\n\n  * dummy\n\n -- nobody <nobody@example.com>  %s\n\n" "${BAREOS_VERSION}" "${NOW}" | tee debian/changelog
    # build and install Bareos packages
    - .travis/travis_before_script.sh

script:
    # run test script
    - if [ -z "${COVERITY_SCAN:-}" ]; then sudo -E $PWD/.travis/all; fi
