.. code-block:: none
   :caption: /var/log/syslog

   Mar 20 11:19:27 ting avahi-daemon[1218]: Interface wlp59s0.IPv6 no longer relevant for mDNS.
   Mar 20 11:19:27 ting systemd[1]: Starting Network Manager Script Dispatcher Service...
   Mar 20 11:19:27 ting dbus-daemon[1263]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
   Mar 20 11:19:27 ting systemd[1]: Started Network Manager Script Dispatcher Service.
