<?php

/**
 *
 * Barbossa - A Web-Frontend to manage Bareos
 * 
 * @link      http://github.com/fbergkemper/barbossa for the canonical source repository
 * @copyright Copyright (c) 2013-2014 dass-IT GmbH (http://www.dass-it.de/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
 
$title = 'Statistics';
$this->headTitle($title);

?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<ul class="nav nav-tabs">
	<li><a href="<?php echo $this->url('statistics', array('action'=>'index')); ?>"><?php echo $this->translate('Job status'); ?></a></li>
	<!--<li><a href="<?php echo $this->url('statistics', array('action'=>'stored')); ?>"><?php echo $this->translate('Stored bytes'); ?></a></li>-->
	<!--<li><a href="<?php echo $this->url('statistics', array('action'=>'client')); ?>"><?php echo $this->translate('Client'); ?></a></li>-->
	<!--<li><a href="<?php echo $this->url('statistics', array('action'=>'backupjob')); ?>"><?php echo $this->translate('Backup job'); ?></a></li>-->
	<li class="active"><a href="<?php echo $this->url('statistics', array('action'=>'catalog')); ?>"><?php echo $this->translate('Catalog'); ?></a></li>
</ul>

<br />

<div class="row">

<!-- CATALOG STATISTICS -->
<div class="col-md-4">
        
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
	    	<span class="glyphicon glyphicon-stats"></span>
		<?php echo $this->translate('Catalog overview') ?>
		</h3>
            </div>
            
            <div class="panel-body">
                        
	      <table class="table table-striped table-hover" style="font-size: 9pt;">
		<tr><td><?php echo $this->translate("Total clients"); ?></td><td><span class="badge"><?php echo $this->clientNum; ?></span></td></tr>
		<tr><td><?php echo $this->translate("Total filesets"); ?></td><td><span class="badge"><?php echo $this->filesetNum; ?></span></td></tr>
		<tr><td><?php echo $this->translate("Total pools"); ?></td><td><span class="badge"><?php echo $this->poolNum; ?></span></td></tr>
		<tr><td><?php echo $this->translate("Total volumes"); ?></td><td><span class="badge"><?php echo $this->volumeNum; ?></span></td></tr>
		<tr><td><?php echo $this->translate("Total jobs"); ?></td><td><span class="badge"><?php echo $this->jobNum; ?></span></td></tr>
		<tr><td><?php echo $this->translate("Total files"); ?></td><td><span class="badge"><?php echo $this->fileNum; ?></span></td></tr>
		<tr><td><?php echo $this->translate("Total logs"); ?></td><td><span class="badge"><?php echo $this->logNum; ?></span></td></tr>
	      </table>
            
            </div>
            
        </div>
        
</div>

</div>
