<?php
  $title = 'Statistics';
  $this->headTitle($title);
?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<script type="text/javascript">

    function chart1() {

      var data = [
	  ['Running', <?php echo $this->jobsRunning; ?>],
	  ['Completed successful', <?php echo $this->jobsTerminated; ?>],
	  ['Terminated with Errors', <?php echo $this->jobsTerminatedWithErrors; ?>],
	  ['Non-fatal Errors', <?php echo $this->jobsWithNonFatalErrors; ?>],
	  ['Fatal Errors', <?php echo $this->jobsWithFatalErrors; ?>],
	  ['Canceled by user', <?php echo $this->jobsCanceled; ?>],
	  ['Verify found difference', <?php echo $this->jobsVerifyFoundDiff; ?>],
	  ['Waiting for Client', <?php echo $this->jobsWaitingForClient; ?>],
	  ['Waiting for Storage daemon', <?php echo $this->jobsWaitingForStorageDaemon; ?>],
	  ['Waiting for new media', <?php echo $this->jobsWaitingForNewMedia; ?>],
	  ['Waiting for media mount', <?php echo $this->jobsWaitingForMediaMount; ?>],
	  ['Waiting for storage resource', <?php echo $this->jobsWaitingForStorageResource; ?>],
	  ['Waiting for job resource', <?php echo $this->jobsWaitingForJobResource; ?>],
	  ['Waiting for client resource', <?php echo $this->jobsWaitingForClientResource; ?>],
	  ['Waiting on maximum jobs', <?php echo $this->jobsWaitingOnMaximumJobs; ?>],
	  ['Waiting on start time', <?php echo $this->jobsWaitingOnStartTime; ?>],
	  ['Waiting on higher priority jobs', <?php echo $this->jobsWaitingOnHigherPriorityJobs; ?>],
	  ['SD despooling attributes', <?php echo $this->jobsSDdespoolingAttributes; ?>],
	  ['Doing batch insert file records', <?php echo $this->jobsBatchInsertFileRecords; ?>],
	  ['Created not yet running', <?php echo $this->jobsCreatedNotRunning; ?>],
	  ['Blocked', <?php echo $this->jobsBlocked; ?>]
      ];
      
      var plot1 = jQuery.jqplot('chart1',[data],
      {
	seriesDefaults: {
	  renderer: jQuery.jqplot.PieRenderer,
	  rendererOptions: { 
	    showDataLabels: true
	  }
      },
	legend:{ 
	  show: true,
	  location: 'w'
	},
	grid: {
	  drawGridLines: true
        }
      });
      
    }

    $(document).ready(
      function(){
	chart1();
      }
    );

</script>

<!-- JOB STATISTICS -->
<div class="row">

<div class="col-md-9">
        
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
	    	<span class="glyphicon glyphicon-stats"></span>
		<?php echo $this->translate('Job statistic (last 24 hours)') ?>
		</h3>
            </div>
            
            <div class="panel-body">
            
            <div class="col-md-4">
            
	      <table class="table table-striped table-hover" style="font-size: 9pt;">
		<tr><td><?php echo $this->translate("Running"); ?></td><td><?php echo $this->jobsRunning; ?></td></tr>
		<tr><td><?php echo $this->translate("Completed successful"); ?></td><td><?php echo $this->jobsTerminated; ?></td></tr>
		<tr><td><?php echo $this->translate("Terminated with errors"); ?></td><td><?php echo $this->jobsTerminatedWithErrors; ?></td></tr>
		<tr><td><?php echo $this->translate("Non-fatal errors"); ?></td><td><?php echo $this->jobsWithNonFatalErrors; ?></td></tr>
		<tr><td><?php echo $this->translate("Fatal errors"); ?></td><td><?php echo $this->jobsWithFatalErrors; ?></td></tr>
		<tr><td><?php echo $this->translate("Canceled by user"); ?></td><td><?php echo $this->jobsCanceled; ?></td></tr>
		<tr><td><?php echo $this->translate("Verify found difference"); ?></td><td><?php echo $this->jobsVerifyFoundDiff; ?></td></tr>
		<tr><td><?php echo $this->translate("Waiting for client"); ?></td><td><?php echo $this->jobsWaitingForClient; ?></td></tr>
		<tr><td><?php echo $this->translate("Waiting for storage daemon"); ?></td><td><?php echo $this->jobsWaitingForStorageDaemon; ?></td></tr>
		<tr><td><?php echo $this->translate("Waiting for new media"); ?></td><td><?php echo $this->jobsWaitingForNewMedia; ?></td></tr>
		<tr><td><?php echo $this->translate("Waiting for media mount"); ?></td><td><?php echo $this->jobsWaitingForMediaMount; ?></td></tr>
		<tr><td><?php echo $this->translate("Waiting for storage resource"); ?></td><td><?php echo $this->jobsWaitingForStorageResource; ?></td></tr>
		<tr><td><?php echo $this->translate("Waiting for job resource"); ?></td><td><?php echo $this->jobsWaitingForJobResource; ?></td></tr>
		<tr><td><?php echo $this->translate("Waiting for client resource"); ?></td><td><?php echo $this->jobsWaitingForClientResource; ?></td></tr>
		<tr><td><?php echo $this->translate("Waiting on maximum jobs"); ?></td><td><?php echo $this->jobsWaitingOnMaximumJobs; ?></td></tr>
		<tr><td><?php echo $this->translate("Waiting on start time"); ?></td><td><?php echo $this->jobsWaitingOnStartTime; ?></td></tr>
		<tr><td><?php echo $this->translate("Waiting on higher priority jobs"); ?></td><td><?php echo $this->jobsWaitingOnHigherPriorityJobs; ?></td></tr>
		<tr><td><?php echo $this->translate("SD despooling attributes"); ?></td><td><?php echo $this->jobsSDdespoolingAttributes; ?></td></tr>
		<tr><td><?php echo $this->translate("Doing batch insert file records"); ?></td><td><?php echo $this->jobsBatchInsertFileRecords; ?></td></tr>
		<tr><td><?php echo $this->translate("Created not yet running"); ?></td><td><?php echo $this->jobsCreatedNotRunning; ?></td></tr>
		<tr><td><?php echo $this->translate("Blocked"); ?></td><td><?php echo $this->jobsBlocked; ?></td></tr>
	      </table>
	      
            </div>
            
            <div class="col-md-5">
            
	      <div id="chart1" style="width:500px; height:500px;"></div>
            
            </div>
            
            </div>
            
        </div>
        
</div>
    
<!-- CATALOG STATISTICS -->
<div class="col-md-3">
        
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
	    	<span class="glyphicon glyphicon-stats"></span>
		<?php echo $this->translate('Catalog statistic') ?>
		</h3>
            </div>
            
            <div class="panel-body">
                        
	      <table class="table table-striped table-hover" style="font-size: 9pt;">
		<tr><td><?php echo $this->translate("Total clients"); ?></td><td><span class="badge"><?php echo $this->clientNum; ?></span></td></tr>
		<tr><td><?php echo $this->translate("Total filesets"); ?></td><td><span class="badge"><?php echo $this->filesetNum; ?></span></td></tr>
		<tr><td><?php echo $this->translate("Total pools"); ?></td><td><span class="badge"><?php echo $this->poolNum; ?></span></td></tr>
		<tr><td><?php echo $this->translate("Total volumes"); ?></td><td><span class="badge"><?php echo $this->volumeNum; ?></span></td></tr>
		<tr><td><?php echo $this->translate("Total jobs"); ?></td><td><span class="badge"><?php echo $this->jobNum; ?></span></td></tr>
		<tr><td><?php echo $this->translate("Total files"); ?></td><td><span class="badge"><?php echo $this->fileNum; ?></span></td></tr>
		<tr><td><?php echo $this->translate("Total logs"); ?></td><td><span class="badge"><?php echo $this->logNum; ?></span></td></tr>
	      </table>
            
            </div>
            
        </div>
        
</div>

</div>
