<?php
  $title = 'Statistics';
  $this->headTitle($title);
?>

<h3 class="text-muted"><?php echo $title; ?></h3>
<hr />

<ul class="nav nav-tabs">
	<li><a href="<?php echo $this->url('statistics', array('action'=>'index')); ?>"><?php echo $this->translate('Job status'); ?></a></li>
	<li class="active"><a href="<?php echo $this->url('statistics', array('action'=>'stored')); ?>"><?php echo $this->translate('Stored bytes'); ?></a></li>
	<li><a href="<?php echo $this->url('statistics', array('action'=>'client')); ?>"><?php echo $this->translate('Client'); ?></a></li>
	<li><a href="<?php echo $this->url('statistics', array('action'=>'backupjob')); ?>"><?php echo $this->translate('Backup job'); ?></a></li>
	<li><a href="<?php echo $this->url('statistics', array('action'=>'catalog')); ?>"><?php echo $this->translate('Catalog'); ?></a></li>
</ul>

<br />

<div class="row">

<div class="col-md-12">
        
        <div class="panel panel-default">
        
            <div class="panel-heading">
                <h3 class="panel-title">
	    	<span class="glyphicon glyphicon-stats"></span>
		<?php echo $this->translate('Stored bytes (last 24 hours)') ?>
		</h3>
            </div>
            
            <div class="panel-body">
            </div>
            
        </div>

</div>

</div>

<div class="row">

<div class="col-md-12">
        
        <div class="panel panel-default">
        
            <div class="panel-heading">
                <h3 class="panel-title">
	    	<span class="glyphicon glyphicon-stats"></span>
		<?php echo $this->translate('Stored bytes (last 7 days)') ?>
		</h3>
            </div>
            
            <div class="panel-body">
            </div>
            
        </div>

</div>

</div>

<div class="row">

<div class="col-md-12">
        
        <div class="panel panel-default">
        
            <div class="panel-heading">
                <h3 class="panel-title">
	    	<span class="glyphicon glyphicon-stats"></span>
		<?php echo $this->translate('Stored bytes (last 14 days)') ?>
		</h3>
            </div>
            
            <div class="panel-body">
            </div>
            
        </div>

</div>

</div>
